### ISSUE TITLE
Retire affixes on cs:et-al

### ISSUE THREAD

**Issue by rmzelle** [citation-style-language/schema#101]
As described at http://xbiblio-devel.2463403.n2.nabble.com/Retire-affixes-on-cs-et-al-td7578167.html and https://bitbucket.org/fbennett/citeproc-js/issue/141/affixes-on-cs-et-al-are-ignored , affixes on cs:et-al seem to be a remnant of CSL development we can safely do without. (direct affixes can always be defined within the term, and the delimiter with the preceding name is controlled by delimiter-precedes-et-al (CSL 1.0.1 feature))

**Comment by bwiernik** [comment]
Agreed this should go into 1.1

**Comment by denismaier** [comment]
That's done right?

**Comment by bwiernik** [comment]
Yep, thanks.
