### ISSUE TITLE
Add "op. cit." term

### ISSUE THREAD

**Issue by rmzelle** [citation-style-language/schema#103]
See http://forums.zotero.org/discussion/24804/some-csl-lithuanian-locale-translation-problems/#Item_21

**Comment by denismaier** [comment]
"Op. cit." and "loc. cit." are evil. And they are not the same as "ibid". See: https://en.wikipedia.org/wiki/Op._cit.

Ibid. => the same citation as cited immediately before.
Op. cit. => the cited work (by a given author); replaces publication details given in a prior full citation, would take effect on `position="subsequent"`.
loc. cit. => basically the same as "op. cit." but replaces also the page number.

The problem with them is that they are/were sometimes used in more complex ways:

```
1. John Doe, Book A (Location: Publisher).
2. John Doe, Book B (Location: Publisher).
3. Doe, Book A, op. cit.
4. Doe, Book B., op. cit.
5. Jane Smith, Book C (Location: Publisher).
6. Doe, op. cit. => This refers to Doe, Book B
7. Doe, Book A, op. cit.
```

So, to support this we'd have to introduce new options for position. (e.g. `position="subsequent-same-title-as-last-title-by-same-author"`)

**Comment by bdarcus** [comment]
When we add this to the documentation, I suggest we recommend against its use, and cite Chicago (quoted in the wikipedia article denis links to). It really doesn't belong in 21st century texts.

**Comment by denismaier** [comment]
And we have to keep in mind that the term is only part of the solution.
