### ISSUE TITLE
Proposal: "language" to be testable

### ISSUE THREAD

**Issue by f-mb** [citation-style-language/schema#110]
Following #55 that make "language"a CSL variable.

A good idea would be to have "language" testable, like locutor or position, within "choose". Then, testing language, we could change title rendering. Also, for legal_case, bill and legislation, testing language could help to determine citation format (and jurisdiction); specially between common-law and civil-law citation.

As you know capitalizing rules vary from one language to an other, even within the same citation style (ex: McGill French or Lluelles).

I looked into csl schema and that doesn't seem that hard (also that seems backward compatible).

Any opinion/objection/idea ? (@fbennett @adam3smith)

PS: I don't know if I should post that on xbiblio-devel list, or here is the right place.

**Comment by rmzelle** [comment]
(I think we'd want to keep this issue open)

**Comment by f-mb** [comment]
OK ;)

**Comment by denismaier** [comment]
Related to https://github.com/citation-style-language/schema/issues/63

As per @rmzelle allowing for multiple `layouts` may not be enough:

> the reason why I haven't been pushing for incorporation of Frank's solution in official CSL: by solely relying on cs:locale elements, there is no straight-forward way to specify item-language-specific settings for options that only exist on cs:style, cs:citation, and cs:bibliography.

**Comment by denismaier** [comment]
Closing this in favor of https://github.com/citation-style-language/schema/issues/63
