### ISSUE TITLE
Proposal: Add "volume-title" as a CSL variable

### ISSUE THREAD

**Issue by njbart** [citation-style-language/schema#111]
I'd like to repeat a proposal first made by adam3smith in Jan 2013 at https://github.com/ajlyon/zotero-bits/issues/54, which apparently has not been posted on a CSL list or issue tracker before.

The proposal is to add "volume-title" as a CSL variable, intended to hold (a) the title of a single volume that is itself part of a multi-volume monograph, or (b) the title of a special issue of a journal.

Rationale: CMoS requires the distinction between the title of a single volume (CSL: "volume-title") and the title of a multi-volume monograph (CSL: "title", or "container-title" for book chapters etc.), and both need to be distinguished from series (CSL: "collection-title").

adam3smith's original post follows:

> http://forums.zotero.org/discussion/26476/helpfeature-request-individual-volumes-as-parts-of-multivolume-works/#Item_3
> 
> Examples from Chicago Manual include:
> Pelikan, Jaroslav. The Christian Tradition: A History of the Development of Doctrine. Vol. 1, The Emergence of the Catholic Tradition (100–600). Chicago: University of Chicago Press, 1971.
> 
> http://www.chicagomanualofstyle.org/16/ch14/ch14_sec124.html
> 
> and
> 
> Barrows, Herbert. Reading the Short Story. Vol. 1 of An Introduction to Literature, edited by Gordon N. Ray. Boston: Houghton Mifflin, 1959.
> 
> http://www.chicagomanualofstyle.org/16/ch14/ch14_sec127.html
> 
> Note that these are different from (and can, in fact co-occur with) series and series title.
> 
> Proposal: add a field "Volume Title" to Book and Book Section, map it to new CSL variable "volume-title"
> 
> This could be combined with #36 - if we create a field "Issue Title" we can use that as an indicator of a special issue and map it to the same volume-title CSL variable.

**Comment by nickbart1980** [comment]
I'd like to invite everyone to reconsider: I have come to the conclusion that introducing `volume-title` is not the optimal solution.
Reason: For a book (a single volume that is part of a multivolume monograph) with a `title` and a `volume-title`, the `title` – quite irregularly – will *not* be the title of the smallest, most specific unit involved. Also, `title-short` will no longer be a convenient, i.e., specific shorthand to refer to this item – the shortest unique from will always have to include a volume number, e.g. “*Collected Works*, Vol. 3”.

My revised proposal is to introduce a new CSL variable for holding the title of the multivolume monograph (e.g. “*Collected Works*”), and keep the CSL `title` variable for the the title of the single volume (e.g., “*Tragedies*”). Assuming we call the new CSL variable `collective-title`, as many library catalogues do, this is what it would look like in CSL:
- `title` (e.g. “Tragedies”)
- `collective-title` (e.g., “Collected Works”)
- `collection-title` (e.g., “Oxbridge Classical Texts”)

and for chapters:
- `title` (e.g. “Macbeth”)
- `container-title` (e.g. “Tragedies”)
- `collective-title` (e.g., “Collected Works”)
- `collection-title` (e.g., “Oxbridge Classical Texts”)

(`collective-title` of course is very similar to `collection-title`; other candidates are `main-title`, or `multivolume-title`.)

This, by the way, corresponds to the approach taken by biblatex, which has, for books:
- title (e.g. “Tragedies”)
- maintitle (e.g., “Collected Works”)
- series (e.g., “Oxbridge Classical Texts”)

and for chapters:
- title (e.g. “Macbeth”)
- booktitle (e.g. “Tragedies”)
- maintitle (e.g., “Collected Works”)
- series (e.g., “Oxbridge Classical Texts”)

**Comment by gracile-fr** [comment]
Just to clarify: what was the consensus? What's the difference?

**Comment by eu-genia** [comment]
I am not sure that jumping in is allowed for non-developers - i was looking for an answer to this question and came across the thread - just in case there is work going on, i believe the very last consideration is not quite fitting, and volume-title is a far better and much expected solution - as it would also work for cases where volume-title does not work independently from the book title. 
E.g. Sources of Japanese Tradition (title), I (volume number): From Earliest Times to 1600 (volume title); Sources of Japanese Tradition, II: 1600 to 2000, etc. Such cases cannot be inverted to "From Earliest Times..., Vol. 1 of ...".
Feel free to delete this observation if out of place!

**Comment by bdarcus** [comment]
> Assuming we call the new CSL variable `collective-title`, as many library catalogues do, this is what it would look like in CSL:

I'm struggling to understand how to explain the difference between this and `collection-title.` 

Can someone clarify, perhaps in spec language?

**Comment by denismaier** [comment]
I can try later, but what is spec language?

Would `multivolume-title` be better?

**Comment by bdarcus** [comment]
Just the sentence or two we could use to explain it, so the distinctions
make sense to all of us in the future.

Volume is a more narrow concept that we typically use in CSL.

But multi something might be more clear.

**Comment by bwiernik** [comment]
`collection-title` is for a book series. `collective-title` would replace `container-title` for `multivolume-works`. 

So, for a `chapter` in a single-volume work or a work where volumes are simply numbered, the proposal is:
`title`: Chapter title
`container-title`: Title of book
`collection-title`: Title of book series

For a multivolume work with separately-titled volumes, it would instead be
`title`: Chapter title
`container-title`: Volume title
`collective-title` or `multivolume-title`: Title of complete multivolume book
`collection-title`: Title of book series

I really don't think that `collective-title` is a good idea, especially when considering book chapters.

For example, [this item](https://sk.sagepub.com/reference/the-sage-handbook-of-industrial-work-and-org-psychology-vol3/i5402.xml) has metadata:

**Title:** Careers, career development, and career management
**Volume:** 3
**Volume title:** Managerial psychology and organizational approaches
**(Multivolume) Book title:** The SAGE Handbook of Industrial, Work and Organizational Psychology
**Book series title:** SAGE Handbooks

This book is marketed and sold as _"The SAGE Handbook of Industrial, Work and Organizational Psychology"_. Readers would search for the book using this title. Many citation styles don't include volume titles at all (they would just say "Vol. 3"), so the volume title is really secondary to "The SAGE Handbook…" as identifying the container holding the chapter. The same logic applies to Nick's example of "The Collected Works of William Shakespeare". 

Another consideration is that all current CSL styles are built around `container-title` being the major title of the work (e.g., what `editor` refers to). Switching to `container-title` sometimes referring to the volume and sometimes referring to the book would be a ton of work for updating styles. I think is is also more confusing than just adding `volume-title` as an intermediary level.

**Comment by adam3smith** [comment]
To add to Brenton's argument, the conceptual case for volume title is that title may not be the smallest title unit, but is the _principal_ title of a work (i.e. how people most commonly refer to it).

I think that's also supported by cataloging, although that's a bit uneven IIRC. But for the example in CMoS cited above, 
https://lccn.loc.gov/79142042
and https://lccn.loc.gov/59001583  both have the "collective-title" as the main title and only has the volume titles listed as part

Given all this -- I'd suggest we go with volume-title

**Comment by bdarcus** [comment]
> Given all this -- I'd suggest we go with volume-title

So to the question from @denismaier NOT `multivolume-title`?

From what @bwiernik wrote, it seems like that would be more clear than `volume-title`?

And to go back to spec language, here's the definition for collection-title in the 1.0.1 spec:

>  title of the collection holding the item (e.g. the series title for a book)

So how, if at all, does that definition change with this addition, and what definition are we adding for the new one?

Essentially it's like a specific kind of subcollection title?

**Comment by adam3smith** [comment]
Suggested spec language would be:

> The title of an individual volume of a multi-volume work

I think volume-title (i.e. the title of a specific volume) just like is much clearer than multivolume title (which could be read as both referring to the title of the multi-volume work or the title of the individual work within a multi-volume one.

**Comment by bwiernik** [comment]
Agreed. I like that language.

**Comment by bdarcus** [comment]
Seems github is buggy today, so not sure if this posted or not.

Trying again:

So if `volume-title`, then conceptually it is, in fact, a more specific kind of `container-title`; right?

Again, the spec:

> **collection-title**
>
> title of the collection holding the item (e.g. the series title for a book)
>
> **container-title**
>
> title of the container holding the item (e.g. the book title for a book chapter, the journal title for a journal article)

So maybe to tweak the language, we end up with this?

> **volume-title**
>
> A kind of container title to represent the title of an individual volume in a multi-volume work

Does it apply to examples other than books? Music? Something else?

**Comment by bwiernik** [comment]
Sure, so for music:

`title`: Track title
`container-title`: Album title
`volume-title:` Individual volume title 

Some journals give individual titles to volumes or issues.

**Comment by denismaier** [comment]
Could be also used for articles in special issues.
`volume-title` = Title of the issue
`container-title` = Title of the journal

**Comment by bwiernik** [comment]
Currently, Zotero stores Special Issue titles in fields mapped to `collection-title`. I think that probably makes better sense for that case. But the relationship of `collection-title`, `volume-title`, and `issue-title` for `article-journal` items will need to be worked out at some point.

**Comment by bwiernik** [comment]
There was a discussion about including both `volume-title` and `issue-title` at some point, but I can't find it at the moment. I remember that consensus reached a need for both for clarity.

**Comment by denismaier** [comment]
> Currently, Zotero stores Special Issue titles in fields mapped to `collection-title`. I think that probably makes better sense for that case.

Really, where can you see that?
I think mapping a Special Issue Title to `collection-title` would be not a good choice. Isn't a collection supposed to be broader than a container?

**Comment by denismaier** [comment]
So, it looks like most seem to favor `volume-title`. Can we say the decision is finally made?

**Comment by bwiernik** [comment]
> Really, where can you see that?
> I think mapping a Special Issue Title to collection-title would be not a good choice. Isn't a collection supposed to be broader than a container?

Zotero has **series** and **seriesTitle** fields (their distinction is ambiguous), both mapped to `collection-title`. These fields are intended hold things like the title of an ongoing article series, a special issue or section title, a "Research Topic" (which at some publishers are like special issues that might be added to over time). All of these are collections of multiple articles, so I think `collection-title` is appropriate. 

I don't think that we need to think about `collection-title` as being necessarily hierarchically related to `container-title`. That is the case for books/chapters and book series, but it doesn't have to be the case for journal articles, speeches, etc.

**Comment by denismaier** [comment]
> I don't think that we need to think about `collection-title` as being necessarily hierarchically related to `container-title`. That is the case for books/chapters and book series, but it doesn't have to be the case for journal articles, speeches, etc.

Yes, doesn't have to be the case. But I think it will make coding styles easier. 
If `collection-title` is sometimes above sometimes below `container-title`, won't this entail the need for more if-else manoeuvres?

**Comment by bdarcus** [comment]
I'm pretty sure yes.

Why I've been leery about this.

**Comment by bwiernik** [comment]
It's not really a question of above/below, but rather type of item. Chicago, for example, puts book series after the book title, but puts special issue information in brackets after article title. There would need to be if/else stuff whether special issue information were stored in collection-title or in volume-title.

**Comment by bdarcus** [comment]
Maybe we're just thinking differently, but from my perspective, they
absolutely are hierarchical levels.

So low/high is appropriate metaphor.

**Comment by bwiernik** [comment]
I think they clearly are for books, but I don't think that's for articles or presentations. For a journal article, the thing being collected is articles, not journals. A collection of articles might be contained all in one issue/volume (e.g., a special issue or special section), or they might be spread across multiple volumes (e.g., a Frontiers "Research Topic" or the "Methodological Myths and Urban Legends" series published recurrently in _Organizational Research Methods_). For a presentation, a collection might be something like a recurring lecture series. That wouldn't be nested within a `container-title` or an `event`.

All this being said, I really don't think this is a distinction we need to be concerned with. Citation of collection information is generally differentiated by item type. For example, APA 6th edition cited book series information in some cases for books, but never cited special issue information for a journal article.

**Comment by bdarcus** [comment]
> I think they clearly are for books, but I don't think that's for articles or presentations. For a journal article, the thing being collected is articles, not journals. A collection of articles might be contained all in one issue/volume (e.g., a special issue or special section), or they might be spread across multiple volumes (e.g., a Frontiers "Research Topic" or the "Methodological Myths and Urban Legends" series published recurrently in _Organizational Research Methods_). For a presentation, a collection might be something like a recurring lecture series. That wouldn't be nested within a `container-title` or an `event`.

The above conceptual discussion matters, in part because we need to explain it as clearly as possible in documentation.

When I characterize what the design is, I am not saying it was the correct design; I am simply saying what we were thinking when we designed it.

Indeed, what you're pointing out is what I worried about at the very beginning above: that we made some mistakes, and that they are exposed here, such that an existing problem will get magnified. But ...
 
> All this being said, I really don't think this is a distinction we need to be concerned with. Citation of collection information is generally differentiated by item type. For example, APA 6th edition cited book series information in some cases for books, but never cited special issue information for a journal article. Most styles don't cite this sort of information at all. So, there is relatively little concern about complexity of styles here; there is going to be some amount of condition logic somewhere, and those cases are pretty much all already written into existing styles like Chicago, MLA, etc.

This is probably right.

**Comment by bwiernik** [comment]
See also this comment:
https://github.com/citation-style-language/schema/pull/183#discussion_r415139248

**Comment by denismaier** [comment]
So, no `issue-title` this time. I won't insist on adding it. In case in turns out we need it, we can always add it later.
