### ISSUE TITLE
proposal: Add more names to support Council of Science Editors

### ISSUE THREAD

**Issue by serpodrick** [citation-style-language/schema#115]
I would like to have these name variables added to CSL:

volume-editor
compiler
editor-translator

**Comment by denismaier** [comment]
Shouldn't we add a `volume-editor`.
Or, should this be covered with `@relation`?
@bwiernik @bdarcus

**Comment by bwiernik** [comment]
volume-editor is fine.

**Comment by bdarcus** [comment]
> Or, should this be covered with `@relation`?

It's a relation.

**Comment by bwiernik** [comment]
I’m thinking of things like big multivolume encyclopedias where there is an editor in chief and an editor for each volume. Right now, we just enter both as editor.

**Comment by denismaier** [comment]
> I’m thinking of things like big multivolume encyclopedias where there is an editor in chief and an editor for each volume. Right now, we just enter both as editor.

Yes. That's the use case. The question is just if we introduce a new variable `volume-editor`, or if we do `names variable="editor" relation="volume"/>`. I think we should do the latter if we introduce the data-model with relations. Otherwise, `volume-editor` seems to be an obvious addition.

**Comment by bwiernik** [comment]
Let's add `volume-editor`. I don't think we should rely on the hierarchical data structure more than is necessary.

**Comment by bdarcus** [comment]
I think we should first settle the relation discussion, and the impact on
the data model, before deciding this.

**Comment by denismaier** [comment]
> Let's add `volume-editor`. I don't think we should rely on the hierarchical data structure more than is necessary.

Let's say we did it like this. What about translators? We will need `container-translator`and `volume-translator`. That will get pretty messy...

**Comment by bwiernik** [comment]
Honestly, I think any of these beyond vanilla `editor` and `translator` are rare enough to be edge cases. Translators especially so. I think we should not overthink this.

**Comment by denismaier** [comment]
> Honestly, I think any of these beyond vanilla `editor` and `translator` are rare enough to be edge cases. Translators especially so. I think we should not overthink this.

That's why I think they are a good fit for the relation syntax. So we don't have to argue over `volume-compiler`, but the variable would still be available if someone needs it. It seems to me that this is the major advantage of this syntax.

**Comment by bwiernik** [comment]
Yes. volume-editor is one that is fairly common and should be available regardless of whether there is a hierarchical data model

**Comment by bdarcus** [comment]
I'm going to repeat, I want us to resolve the data model question first.

Because as a part of that, I think we should remove exactly these sorts of
variables.

Once we settle that, we can settle this.

**Comment by bwiernik** [comment]
Sure wasn’t exactly sure what your comment was referring to.

— My view any hierarchical data structure should be an optional thing available for complex cases like original, reviewed, alternative languages, and unusual container styles, but that syntax and most item data should continue to use the flat data model. 

As Bruce has stated before, CSL could have started with a hierarchical model, but it opted for flat `container-title`, etc. instead. I think that was a good design choice. 

For typical cases, it is much easier to express items flatly, and I don’t think we should abandon that. If hierarchical structures are adopted optionally, in styles, we should still use the "container-title", "volume-title", etc. syntax. It’s just not going to happen to rewrite every single style to use a different structure.

**Comment by bwiernik** [comment]
So to make this proposal specific—relations are for different items entirely that are related to the current item: reviewed, original, retracted, etc. 

I don’t think we should adopt an accompanying hierarchy for all potential fields and components of a single item.

**Comment by denismaier** [comment]
> So to make this proposal specific—relations are for different items entirely that are related to the current item: reviewed, original, retracted, etc.
> 
> I don’t think we should adopt an accompanying hierarchy for all potential fields and components of a single item.

So, you have changed your mind regarding containers? I thought [here](https://github.com/citation-style-language/schema/issues/167#issuecomment-650593872) you were proposing to extend relations to containers as well.

**Comment by bwiernik** [comment]
I think specifying container like that should be an optional thing, potentially just with a `container` element giving an id.

**Comment by denismaier** [comment]
Related question: how should we deal with second order relations like `reviewed-container-title`? Should that be
a) `variable="title" relation="reviewed-container"`
b) `variable="container-title" relation="reviewed"`

The answer to this question will probably also partly answer the more general question regarding `@related`

Going all the way with relations would mean we should adopt a), @bwiernik's proposal would lead us to version b).

**Comment by bwiernik** [comment]
Sorry for the long post here.

I am not a fan of the `variable="container-title" relation="reviewed"` syntax, particularly if it is going to be applied to within-item relations like container or volume. For related variables, I think we should adopt one or both of the following syntaxes:

1. `reviewed-*`:
   1. The prefix `reviewed-` indicates to pull the variable from the children of `reviewed` element of the input data.
   1. With this syntax, any `reviewed-` variable can be called like a normal variable.
   1. This maintains compatibility with all existing variables and permits simple calls in styles where only a limited number of fields is needed (e.g., just citing `original-date`).
1. `cs:related`:
   1. Add a new `cs:related` element with a `relation` attribute: `<related relation="reviewed">`
   1. The `cs:related` element changes the `"context"` to be the contents of `relation`.
   1. Children of `cs:related` use the context-specific variables when they are called in:
      - e.g., if `context="reviewed"`, `text variable="title"` renders `reviewed-title`
    1. `context` is a testable attribute:
       - `<if context="reviewed">`
       - Tests for context can be included as part of macros or layouts to allow different formatting across contexts.
       - For example, APA style wants journal article titles to be in quotes only in reviewed or original titles. That could be coded as:
         ```
         <if context="reviewed original" match="any">
           <text variable="title" quotes="true"/>
         </if>
         <else>
           <text variable="title"/>
         </else>
         ```
      1. This syntax is used when more complete references to reviewed, original, etc. works are needed. It also can easily be extended to things like multilingual support. 
     1. This syntax is a more flexible take on the CSLm `cs:alternative`

(One other roadblock we are at is, although `collection` and `container` don't currently exist in CSL 1.0.2 as separate variables [now that `container` has been removed as a date variable], `volume`, `part`, `issue`, etc. do--they are the number variables for these components [e.g., had a hierarchical data model been used originally, they would have been named `volume-number`, `part-number`, `issue-number`, etc.]. That poses a data compatibility challenge to making them the hierarchical node variable.

**Comment by bdarcus** [comment]
> I am not a fan of the `variable="container-title" relation="reviewed"` syntax, particularly if it is going to be applied to within-item relations like container or volume.

What do you mean by the last fragment?

And to be clear, we're only here talking about the CSL style syntax; right? We're not discussing the input model, which is related, but not the same thing.

**Comment by bwiernik** [comment]
Yes, we are talking about the style syntax.

By the last part, I mean I don't want to replace:
`<text variable="container-title"/>`

with:
`<text variable="title" relation="container"/>`

**Comment by bdarcus** [comment]
Got it.

Yeah, while there's a logical reason to consider that, I was leaning towards not, just because it makes the input model more complex again, without obvious benefit on the style end.

To remind you, and fill in some backstory:

I am pretty sure my first prototype DID have a hierarchical model, in part because I was working a lot with MODS at the time.

I recall we made a conscious decision to flatten it, though, and the convention we adopted was the hyphens represented the core level distinctions.

Hence `container-title` and such.

To my point above, then, I might argue to remove some variables from the input side, but they might stay here, per your proposal.

**Comment by bwiernik** [comment]
Yeah, I think that's reasonable, ideally if we still allow the flat hyphen structure as an input option, at least for some/all of the legacy flat variables?

**Comment by denismaier** [comment]
Won't this again lead to the explosion of variables that we've had with my script and that https://github.com/citation-style-language/schema/pull/268 was trying to solve?

**Comment by bwiernik** [comment]
I think we can recognize and validate by pattern rather than enumeration. It would also not have an explosion in the JSON schema. 

What do you mean by 2 and 3 here?

**Comment by denismaier** [comment]
2. = `cs:related`
3. should have been 2. iv. `context` is a testable attribute
(sorry for the confusion.)

**Comment by bdarcus** [comment]
I'm working on the related PR now, and will push something to discuss soon,
but would just say this:

For me, an important priority is the UX of editing styles in a validating
editor.

I'm pretty sure using patterns undermines that.

Priority on input changed is similar; to take what was initially more for
machines and make it nice for humans.

**Comment by bdarcus** [comment]
Ugh; just lost all my work.

May be a little while longer ;-)

**Comment by bwiernik** [comment]
What UX are you thinking about though? I’ve never really used autocomplete when editing styles, and I don’t know how much that needs be to a concern if that’s the barrier.

**Comment by bdarcus** [comment]
Auto-completion. I would never edit an XML file without it.

It absolutely is a concern; always has been, from the very beginning.

**Comment by bwiernik** [comment]
But remember we are talking about the related-* variables. If we lose autocompletion on them (and I’m not sure we would), I don’t think that’s a big deal.

**Comment by denismaier** [comment]
Maybe a stupid question: but doesn't autocompletion depend on validation somehow? Can a sttle that uses a variable that isn't accessible in autocompletion still be validated?

**Comment by bdarcus** [comment]
We can only know if we test.

That's why I qualifed my statement.

**Comment by bdarcus** [comment]
Auto is built on top of validation, but a specific name value can be
auto-completed, while I suspect a pattern thrown in will cause confusion,
for tool and human.

**Comment by denismaier** [comment]
Maybe a stupid question, but is there still anything we need to do about this here? The initially requested variables (`volume-editor`, 
`compiler`, `editor-translator`) have been added somewhere, the discussion regarding data structure has been continued elsewhere. So best seems to close this...
