### ISSUE TITLE
Allow range formatting for all numbers (esp. dates)

### ISSUE THREAD

**Issue by adunning** [citation-style-language/schema#122]
The `page-range-format` attribute only applies to page numbers (as one would expect), but style guides typically extend these rules to all numbers. This is most notably an issue with date ranges; for example, the following citation (using [Chicago author-date](http://www.chicagomanualofstyle.org/16/ch15/ch15_sec039.html)) is currently impossible to achieve with CSL:

> Karenberg, Axel. 2012–13. ‘The World of Gods and the Body of Man: Mythological Origins of Modern Anatomical Terms’. _Anatomy_ 6–7: 7–22. doi:10.2399/ana.11.142.

I originally proposed on [xbiblio-devel](http://xbiblio-devel.2463403.n2.nabble.com/Expanding-Page-Range-Formats-td7579124.html) to simply extend the `page-range-format` attribute to all numbers, but @rmzelle noted the following:

> My gut feeling is that it's better to have separate definitions of range formatting for dates and all other numbers, so that they can be configured separately. Volume, issue, and series number ranges don't come up very often (in practice and in citation manuals), so we haven't really thought about whether the page-range-format should affect them.

This is an issue, for example, in the [OUP House Style](http://global.oup.com/uk/academic/authors/AuthorGuidelinesMain/HouseStyle/#lev21), where dates use a different formatting scheme from other numbers.

**Comment by denismaier** [comment]
Isn't that something we could add now? @bwiernik ?

**Comment by bdarcus** [comment]
I think so.

**Comment by bwiernik** [comment]
I think that `page-range-delimiter` can probably apply to volume ranges, issue ranges, etc. (so number ranges generally). Date ranges should have their own delimiter as suggested.

**Comment by denismaier** [comment]
> Date ranges should have their own delimiter as suggested.

Absolutely. Would we actually need more than one delimiter for date ranges? Like "2012/13", but "2012-2018"?

**Comment by bwiernik** [comment]
I'm not following what the distinction there is?

**Comment by denismaier** [comment]
If we have one year and the immediately following year: use a slash; if we have more year: use a dash.

**Comment by bwiernik** [comment]
Oh, I see. I could see that.

**Comment by denismaier** [comment]
The question is if that is a realistic requirement. I think I have already seen this. (But I don't remember where...)

**Comment by bwiernik** [comment]
Seems like more than a delimiter issue, but rather a whole collapse-year-range formatting question? Compared to the cite collapsing within author and year?

**Comment by denismaier** [comment]
Seems so.

**Comment by bwiernik** [comment]
So let’s do a PR to extend page-range-delimiter to all number variables and add date-range-delimiter? We can consider additional date range formatting options as a separate issue.

**Comment by bwiernik** [comment]
We might also consider renaming `page-range-delimiter` to `number-range-delimiter`.

**Comment by denismaier** [comment]
Ok, so we do this:

1. rename `page-name-delimiter` to `number-range-delimiter`, which will affect all number variables.
2. add `date-range-delimiter`
3. add `collapse-year-range`

**Comment by bwiernik** [comment]
Let's do 1 and 2 for now. We may need to consider more fully what date range attributes are needed.

**Comment by denismaier** [comment]
The third question is not solved yet. Or should we open a new issue for that?

**Comment by bwiernik** [comment]
Let's open a new issue.
