### ISSUE TITLE
Expand options available for `page-range-format`

### ISSUE THREAD

**Issue by adunning** [citation-style-language/schema#123]
It would be very useful to have the following additions to the options for `page-range-format`:
- The [MHRA format](http://www.mhra.org.uk/Publications/Books/StyleGuide/StyleGuideV3_1.pdf) (see p. 47 of the guide), which is like `chicago` but wants a leading zero, e.g. 13–15, 44–47, 100–22, 104–08, 1933–39 but 1098–1101.
- The [OUP format](http://global.oup.com/uk/academic/authors/AuthorGuidelinesMain/HouseStyle/#lev20), which is like the `minimal` style but requests, 'Do not omit digits between 10 and 19 in any hundred.’ I believe this is supposed to fit with English pronunciation (cf. a [similar style guide](http://www.pims.ca/pdf/bw-stylesheet.pdf)).

I have also seen a variant on the 'minimal-two’ style that avoids leading zeros, but I have not yet found a style guide that actually requires it.

(This was originally proposed on [xbiblio-devel](http://xbiblio-devel.2463403.n2.nabble.com/Expanding-Page-Range-Formats-td7579124.html).)

**Comment by denismaier** [comment]
I think we should do this now since it's a trivial addition. Question is just if we should a pattern syntax instead of the current options. Could be more flexible.

**Comment by bdarcus** [comment]
But adding a general solution is inherently more complicated, and I'm
not convinced necessary.

I agree; let's add these.

**Comment by denismaier** [comment]
> But adding a general solution is inherently more complicated

True.

So, let's just add those.
