### ISSUE TITLE
AD/BC (better: CE/BCE): terms, position of AD/AH, separating space

### ISSUE THREAD

**Issue by carlfhooper** [citation-style-language/schema#124]
The specs regarding calendar era (http://citationstyles.org/downloads/specification.html#ad-and-bc) are incorrect on two points, and problematic on another one:
(1) There should always be a (protected) space between year and term (Chicago Manual of Style, 16th ed., 9.35 “Eras”).
(2) “Note that the Latin abbreviations AD and AH precede the year number, whereas the others follow it.” (Chicago Manual of Style, 16th ed., 9.35 “Eras”). – Examples from the Chicago Manual:

> Herod Antipas (21 BCE–39 CE) was tetrarch of Galilee from 4 BCE until his death.
> Britain was invaded successfully in 55 BC and AD 1066.

(3) “AD/BC” is increasingly regarded as culturally and religiously insensitive. As a default, “AD/BC” should be replaced by the more neutral “CE/BCE”, and the “ad” and “bc” term labels should also be replaced by “ce” and “bce”. – I’d just like to quote Kofi Annan here:

> [T]he Christian calendar no longer belongs exclusively to Christians. People of all faiths have taken to using it simply as a matter of convenience. There is so much interaction between people of different faiths and cultures – different civilizations, if you like – that some shared way of reckoning time is a necessity. And so the Christian Era has become the Common Era. (Quoted in https://en.wikipedia.org/wiki/Common_Era)

**Comment by rmzelle** [comment]
@carlfhooper, thanks for bringing up the issue. We'll take a look at this for the next CSL release. Just note that it's already possible to redefine the translations for the "AD" and "BC" terms to use common era terms in any style, so (3) is mostly taken care of already. Although I imagine we might want to introduce dedicated "CE" and "BCE" terms in the future, and a toggle in styles on whether to use the "AD"/"BC" or "CE"/"BCE" system.

@adam3smith, I'm pretty sure there have been previous discussions on CE/BCE vs. AD/BC, but I couldn't find them (or any existing open tickets). Do you remember where we had these?

**Comment by adam3smith** [comment]
I don't remember any discussion beyond the ability to customize via changed terms, no. 
We could already change the default translations of the terms for en-US, where I think @carlfhooper is right about CE/BCE being more widely accepted. 
I don't know about en-GB and my approach would be entirely pragmatic, i.e. we pick the default that's most widely used in academia in any given locale. I'd maybe see if MHRA and OSCOLA or the British archaeological society (whatever it's called) have a preference and follow that. 

This also would have the advantage of getting the placement right, if not the spacing. Also, we should look at whether everyone agrees with Chicago and placment and spacing. Otherwise we may have to allow styles to customize that, too.

**Comment by bwiernik** [comment]
@denismaier Could you look into the @adam3smith's two questions there?

**Comment by denismaier** [comment]
Sure, but what exactly is the question?

**Comment by bwiernik** [comment]
> I don't know about en-GB and my approach would be entirely pragmatic, i.e. we pick the default that's most widely used in academia in any given locale. I'd maybe see if MHRA and OSCOLA or the British archaeological society (whatever it's called) have a preference and follow that.

Do MHRA, OSCOLA, British archaeological society prefer BC/AD or CE/BCE?

**Comment by bwiernik** [comment]
And
> Also, we should look at whether everyone agrees with Chicago and placment and spacing.

**Comment by denismaier** [comment]
MHRA: In citations of the era, ‘bc’, ‘bce’, ‘ce’, and ‘ah’ follow the year and ‘ad’ precedes it, and small capitals without full stops are used. (http://www.mhra.org.uk/style/8.1)

OSCOLA: I could not find anything about that matter in their [guide](https://www.law.ox.ac.uk/sites/files/oxlaw/oscola_4th_edn_hart_2012.pdf). In their list of abbreviations "Borough Council" stands for "Borough Council".

[British Archeological Society](https://thebaa.org/publications-resources/preparation-of-material-for-the-journal-and-the-transactions-instructions-for-authors-journal/): Dates BC should be given as ’27 BC’, and dates AD as ‘AD 320’, that is without full points and in small capitals. Papers dealing entirely with dates AD need not specify.

**Comment by bwiernik** [comment]
Okay, so in English, AD should go before the year, others after. However, this isn’t consistent. In French, “apr. J.C.” comes after the year. So placement needs to be controllable as well as terminology. 

(MHRA and Chicago disagree about AH, but that’s a different calendar system, so we wouldn’t really be able to support it without a more robust date system exists ala Jurism’s Japanese Imperial dates. This might be nice, but is out of scope for this issue.)

It seems like en-GB should use AD/BC.

To switch between systems, `cs:date` gets a new inheritable attribute, `era-notation` which can take values `"ce"` (default) or `"ad"`. These switch between using CE/BCE and AD/BC respectively. This option can also be specified in the `date` section of a locale file or section.

To control placement of era terms, `cs:date` gets a `cs:era` child element (similar to `cs:et-al`). This takes the form:
`<era term="ad"/>`
`<era term="bc ce bce"/>`

This indicates the placement of the terms in a date (if present). Terms are a space delimited list. `cs:era` can take text formatting attributes. 

So, total changes:
- add terms `ce` and `bce`
- add `cs:era` element 
- add `era-notation` attribute to `cs:date`

**Comment by bdarcus** [comment]
Just noting here the recent addition of #284.

**Comment by bwiernik** [comment]
What exactly are the implications of that for era notation?

**Comment by bdarcus** [comment]
I didn't read the thread closely, but noted it just because a negative year
is BC.

>

**Comment by bwiernik** [comment]
Okay, this thread is about specifying whether to use AD/BC or CE/BCE notation and how to position those terms.

**Comment by denismaier** [comment]
Would be good to add this now, wouldn't it?

**Comment by bwiernik** [comment]
Thanks.

**Comment by denismaier** [comment]
> To control placement of era terms, `cs:date` gets a `cs:era` child element (similar to `cs:et-al`). This takes the form:
> `<era term="ad"/>`
> `<era term="bc ce bce"/>`
> 
> This indicates the placement of the terms in a date (if present).

Trying to figure out how your suggestion should work, I struggle a bit to understand how this will indicate placement of terms?

**Comment by bwiernik** [comment]
So, the en-us locale would be updated to look like this:
```
  <date form="text" era-notation="ce">
    <date-part name="month" suffix=" "/>
    <date-part name="day" suffix=", "/>
    <era term="ad"/>
    <date-part name="year"/>
    <era term="bc ce bce"/>
  </date>
```

**Comment by denismaier** [comment]
Should `era-notation` be required?

**Comment by bwiernik** [comment]
Yes, but it should be inheritable and inherited from the locale.

**Comment by denismaier** [comment]
> So, the en-us locale would be updated to look like this:
> 
> ```
>   <date form="text" era-notation="ce">
>     <date-part name="month" suffix=" "/>
>     <date-part name="day" suffix=", "/>
>     <era term="ad" suffix=" "/>
>     <date-part name="year"/>
>     <era term="bc ce bce" prefix=" "/>
>   </date>
> ```
> 
> The position of the terms in the date form indicates their position in the rendered date. Here, "ad" comes before the year, but "bc", "ce", and "bce" all come after.

Would you indeed have all of the terms in that definition? Isn't that redundant given that there is also `era-notation` already?

**Comment by bwiernik** [comment]
In a style, I should just be able to write:
```
<date form="text" era-notation="ad"/>
```

And have it have the terms placed correctly. These should inherit from the locales to give a seamless experience.

**Comment by denismaier** [comment]
> In a style, I should just be able to write:
> 
> ```
> <date form="text" era-notation="ad"/>
> ```
> 
> And have it have the terms placed correctly. These should inherit from the locales to give a seamless experience.

Do you think there's a need for switching between era notations in a given style? I'd say one style either uses "ad" or "ce", right?

**Comment by bwiernik** [comment]
No, it could be a style option.

**Comment by denismaier** [comment]
Ok, playing this through:

Currently, we have this in locales:

```
  <date form="text">
    <date-part name="month" suffix=" "/>
    <date-part name="day" suffix=", "/>
    <date-part name="year"/>
  </date>
  <date form="numeric">
    <date-part name="month" form="numeric-leading-zeros" suffix="/"/>
    <date-part name="day" form="numeric-leading-zeros" suffix="/"/>
    <date-part name="year"/>
  </date>
```

In a style you then call dates with:

```
<date variable="issued" form="text"/>
```

You suggested to add this to locales:

```
<date form="text" era-notation="ce">
  <date-part name="month" suffix=" "/>
  <date-part name="day" suffix=", "/>
  <era term="ad" suffix=" "/>
  <date-part name="year"/>
  <era term="bc ce bce" prefix=" "/>
</date>
```

Why is there this `<era term="ad" suffix=" "/> when `era-notation="ce"`? That doesn't make sense to me.

It would make sense to make to define two patterns for `era-notation` like we do for `form`:

```
<date form="text" era-notation="ce">
  <date-part name="month" suffix=" "/>
  <date-part name="day" suffix=", "/>
  <date-part name="year"/>
  <era term="ce bce" prefix=" "/>
</date>
<date form="text" era-notation="ad">
  <date-part name="month" suffix=" "/>
  <date-part name="day" suffix=", "/>
  <era term="ad" suffix=" "/>
  <date-part name="year"/>
  <era term="bc" prefix=" "/>
</date>
```

And the equivalent for `form="numeric"`.
Styles could then call this with <date form="text" era-notation="ad"/> as you've suggested.

But, that means 4 patterns, and decision which to use happens on a per-variable basis. (I'm probably misunderstanding your suggestion here, right?)

I don't think you'll mix ce and ad notation in one style, right. You'll either use one or the other. So, couldn't we just define this in locales:

```
  <date form="text">
    <date-part name="month" suffix=" "/>
    <date-part name="day" suffix=", "/>
    <era term="ad" suffix=" "/>
    <date-part name="year"/>
    <era term="bc" prefix=" "/>
  </date>
  <date form="numeric">
    <date-part name="month" form="numeric-leading-zeros" suffix="/"/>
    <date-part name="day" form="numeric-leading-zeros" suffix="/"/>
    <era term="ad" suffix=" "/>
    <date-part name="year"/>
    <era term="bc" prefix=" "/>
  </date>
```

Then you'd just call the variable with `<date variable="issued" form="text"/>` as always.

**Comment by denismaier** [comment]
Or this:

```
<style-options era-notation="ad"/>
<date form="text">
  <date-part name="month" suffix=" "/>
  <date-part name="day" suffix=", "/>
  <era term="ad" suffix=" "/>
  <date-part name="year"/>
  <era term="bc ce bce" prefix=" "/>
</date>
<date form="numeric">
  <date-part name="month" form="numeric-leading-zeros" suffix="/"/>
  <date-part name="day" form="numeric-leading-zeros" suffix="/"/>
  <date-part name="year"/>
</date>
```

In this model, you'd define the placement of all terms, but you'd select an era-notation-scheme with `era-notation` as a style option. Each locale would also have a default.

**Comment by bwiernik** [comment]
You’re overthinking this. The `era` element just controls _where_ the terms are placed, not _which_ terms are used. It’s “if the ad term is shown, put it here”. That let’s a locale specify the position of all four terms, so styles virtually never have to change that and can just set the era-notation preference.

**Comment by denismaier** [comment]
> The second one you describe is my original proposal.

Yes, but it had `@era-notation` on `cs:date` itself, which is why I got confused.

**Comment by denismaier** [comment]
> > The second one you describe is my original proposal.
> 
> Yes, but it had `@era-notation` on `cs:date` itself, which is why I got confused. (Probably I'm still confused...)

**Comment by bwiernik** [comment]
Basically, I expect "era" to almost never be given in a style, but only in locales.
