### ISSUE TITLE
Allow 'ed. and trans.' to be attached to primary credit

### ISSUE THREAD

**Issue by adunning** [citation-style-language/schema#128]
As indicated [on the Zotero forums](https://forums.zotero.org/discussion/28514/single-person-as-editor-and-translator-mla/), it isn't currently possible to get a proper citation for a work on which the editor and translator are the same person, and receives the primary credit – a common situation if one is dealing with an anonymous text. A human would probably write this:
- Bloggs, Joe, ed. and trans. _An Anonymous Classical Work_. […]

Instead, due to the structure of CSL, this is evidently the best one can do:
- Bloggs, Joe, ed. _An Anonymous Classical Work_. Translated by Joe Bloggs. […]

I'm still thinking about the simplest method for solving this: it seems that we need a mechanism to display this information conditionally based on whether the identities of these roles match.

**Comment by denismaier** [comment]
Closing in favour of https://github.com/citation-style-language/csl-evolution/issues/7
