### ISSUE TITLE
Make year-suffix localizable

### ISSUE THREAD

**Issue by rmzelle** [citation-style-language/schema#136]
Year suffixes for disambiguation (e.g. "2000a, 2000b") are currently hard-coded in the specification as Latin characters ("a" through "z", "aa" through "zz", etc.). I'm not aware of any other common schemes in English, but we got a report that in Farsi, the Farsi alphabet should be used (see the discussion at https://github.com/citation-style-language/locales/pull/157#issuecomment-277882223). We should check what happens in other languages with non-Latin alphabets, but it might be enough to introduce year suffix terms. We would need at least one term for each alphabet letter, though. Or we could introduce a preference to just select an alphabet.

**Comment by bwiernik** [comment]
I think a preference just for the alphabet would be much better.

**Comment by hamedheydari** [comment]
@rmzelle What's up??!

**Comment by rmzelle** [comment]
@hamedheydari, don't expect this to be implemented soon. We probably first want to check how year suffixes work in some other non-Latin languages like Russian and Chinese.

**Comment by bwiernik** [comment]
Chinese journals usually use latin letters like English.

**Comment by rmzelle** [comment]
@hamedheydari, I have two questions for you. (I uploaded your screenshots to GitHub so they won't get lost in time)

![image](https://user-images.githubusercontent.com/77951/33054590-0e61ab1a-ce72-11e7-8b38-d3ae52f73684.png)

In https://github.com/citation-style-language/locales/pull/157#issuecomment-278203008, you write "And 26 letters (English) or 28 (Abjad) or 32 (Persian) would be more than enough.". But in the example above you restart counting after 26 letters ("الفالف" instead of the English "aa"). Just to make sure, you would normally want to finish out the entire Abjad or Persian alphabet before restarting counting, right?

![image](https://user-images.githubusercontent.com/77951/33054615-39489d5c-ce72-11e7-8d84-916fb968b00a.png)

In https://github.com/citation-style-language/locales/pull/157#issuecomment-277942142, you asked whether it's possible to put an en-dash before the year-suffix. How typical is it to use one of those (or a hyphen or something similar) in e.g. Persian? Always? Sometimes?

**Comment by hamedheydari** [comment]
@rmzelle
1. Yes. But I deleted 2 letters from Abjad from end. Because I was thinking that will be introduced as year-suffix terms, and will be limited to 26 letters.
(In addition, Abjad is preferable to Persian.)
2. Sometimes. By the way this was removed In new style for many unviersities of Iran.

**Comment by rmzelle** [comment]
@hamedheydari, okay, thanks for confirming.

**Comment by bwiernik** [comment]
@bdarcus @denismaier @rmzelle Rather than specifying 26+ discrete terms, could we just do this as a regex range of unicode characters, so: `/[a-z]/` or '/[\u00d8-\u00f6]/'?

**Comment by denismaier** [comment]
I think specifying the alphabet should work.  
Just: Hebrew is also an abjad.
Also, ideally this should work on a per-item basis.

**Comment by bwiernik** [comment]
> Also, ideally this should work on a per-item basis. Something like the CSLm solution where you can have multiple cs:layout elements.

That would work just by making this set on the locale.

**Comment by bwiernik** [comment]
> Just: Hebrew is also an abjad.

So "arabic" instead?

**Comment by denismaier** [comment]
> So "arabic" instead?

Yes.

**Comment by denismaier** [comment]
> > Also, ideally this should work on a per-item basis. Something like the CSLm solution where you can have multiple cs:layout elements.
> 
> That would work just by making this set on the locale.

What do you mean? Can you give an example?

**Comment by bwiernik** [comment]
In the PR, this is a locale option. So, this would be customizable by locale in exactly the same way as the "editor" term is customizable by locale in multilingual layouts.

**Comment by denismaier** [comment]
> In the PR, this is a locale option. So, this would be customizable by locale in exactly the same way as the "editor" term is customizable by locale in multilingual layouts.

Ah yes. So if we just added multilingual layouts that would work immediately, right?

**Comment by bwiernik** [comment]
Yeah.
