### ISSUE TITLE
Make "and" attribute in name lists more configurable

### ISSUE THREAD

**Issue by rmzelle** [citation-style-language/schema#137]
The current definition of the "and" attribute in the specification is:

> Specifies the delimiter between the second to last and last name of the names in a name variable. Allowed values are “text” (selects the “and” term, e.g. “Doe, Johnson and Smith”) and “symbol” (selects the ampersand, e.g. “Doe, Johnson & Smith”).

So there are only two options: the "long" form of the "and" term or the hardcoded ampersand. There have been several reports that this is too limited. Some languages don't seem to use ampersands at all (we received some private communication from @cpina that this is e.g. the case for Spanish and Catalan: '"y" (and) and in Catalan they do like in Spanish ("i", it's "and" in Catalan).'), and some styles require different text forms between the in-text citations and bibliography, e.g. an abbreviated and unabbreviated form (see https://github.com/citation-style-language/styles/pull/2571#issuecomment-287253895).

Most of this could be solved by changing the spec to have `and="symbol"` select the "symbol" form of the "and" term, and by defining the ampersand as translation for this term form in the locale files, which is a relatively easy fix.

A larger but more flexible change would be to make it possible to also e.g. choose the "short" form of the "and" term. This would be possible by e.g. having the "and" attribute directly select the desired term-form, with e.g. attribute values "long", "short", and "symbol" (`and="long"` would replace `and="text"`). Might also want to rename the attribute to "and-form", although I don't think that's very pretty.

**Comment by bwiernik** [comment]
I don't know that `and="short"` is particularly meaningful, but permitting it would let `and=` render like any other term, simplifying processor code. And some user style might have some use for three `and` forms.

**Comment by denismaier** [comment]
In German, I could imagine having three `and` forms: 
long => und
short  => u.
symbol => ampersand

**Comment by bdarcus** [comment]
So the proposal is to add a "short" attribute option to this variable, and revise the spec to make clear the symbol can be configurable?

So the schema change is minor. I'll add a PR.

**Comment by bdarcus** [comment]
Actually, current default is "text." Hmm.

**Comment by bwiernik** [comment]
See https://github.com/citation-style-language/schema/commit/fb65fc0f3217793ac809afd155a4ae8a37c0e2c6#r39420127

**Comment by denismaier** [comment]
This is done, right?
