### ISSUE TITLE
Create terms for "no place" and "no name"

### ISSUE THREAD

**Issue by rmzelle** [citation-style-language/schema#138]
(a.k.a. "sine loco"/"sine nomine")

See https://github.com/citation-style-language/styles/pull/2722/files/0d1487e66c6c73bce8fa6358cb3094701e9023ec#r122593750 and https://github.com/citation-style-language/schema/issues/90#issuecomment-4329346.

**Comment by denismaier** [comment]
@bwiernik What do you think about this? Is that still relevant?

**Comment by bwiernik** [comment]
Yep

**Comment by bdarcus** [comment]
To  clarify, these don't literally mean "no", but rather "unknown"?
