### ISSUE TITLE
Contribution request: Typescript type definitions 

### ISSUE THREAD

**Issue by dsifford** [citation-style-language/schema#139]
Hi there,

I've got some type definitions that I use in multiple projects for the CSL specification and it's become sort of a pain for me to manually copy and paste them between projects.

I'm opening this issue to see what you all would feel about me submitting a pull request with both the typescript definitions and a package.json file so that users can install them using npm.

Let me know! Thanks.

**Comment by rmzelle** [comment]
We got a similar request for the "styles" repo for PHP with [Composer](https://getcomposer.org/): https://github.com/citation-style-language/styles/pull/2706 and https://github.com/citation-style-language/distribution-updater/pull/3

Would this be limited to the "schema" repo? If things don't get too messy I don't see a reason not to take a PR. I assume you'd want to target the "1.0.1" release (currently just tagged at https://github.com/citation-style-language/schema/tree/v1.0.1, so we might need to give that a branch)?

**Comment by dsifford** [comment]
@rmzelle Yes, all the PR would be doing is adding a type definition file that describes the structure of both `CSL.Citation` and `CSL.Data` and the package.json would simply be there in order to allow users to install using npm.

Does the CSL team have a registered npm org name yet? (i.e. `@citation-style-language/some-package`) 

If not, I'd recommend creating one for free so that packages can be installed using the `citation-style-language` namespace. In other words, you could create an npm package for the types and whatever else for this repo at `@citation-style-language/schema`, etc. Just a recommendation. No big deal if you'd prefer to wait for now.

Re: `1.0.1` version target: Here's an example of the types I have defined currently for `CSL.Data`. Let me know if you see anything incorrect. https://github.com/dsifford/astrocite/blob/master/packages/astrocite-eutils/src/globals.d.ts

**Comment by bdarcus** [comment]
> ... you could create an npm package for the types and whatever else for this repo at @citation-style-language/schema, etc. Just a recommendation.

This was closed a few years ago, but two things:

First, I had missed this earlier but it's related to the question I asked recently in #430, which I just closed after creating the org.

Also, separately, but connected to Typescript, I've been working on an experiment @dsifford:

https://github.com/bdarcus/csl-next.js
