### ISSUE TITLE
control structure for context (narrative vs parenthetical)

### ISSUE THREAD

**Issue by mbroedl** [citation-style-language/schema#140]
APA (and probably other citation styles) require to have an 'and' for narrative and an '&' for parenthetical citations[1]. (See also #137, which goes a bit further than this.)

A context-dependent control structure would solve this issue, but this is not possible at the moment.

[1] e.g. <https://en.wikipedia.org/wiki/APA_style#In-text_citations>

**Comment by mbroedl** [comment]
On the mailinglist, @bdarcus replied:
""CSL has no concept of a "narrative citation," which would explain why there's no way to distinguish formatting based on it.""

**Comment by bdarcus** [comment]
Tied to broader issue #141. That problem would need to be solved before this one could be.

**Comment by bwiernik** [comment]
See the discussion here: https://github.com/zotero/zotero/issues/1580

**Comment by denismaier** [comment]
Should we close this issue? More or less a duplicate...

**Comment by bdarcus** [comment]
Not sure.

I do think I linked it to the newer one, and that in turn to the PR. So I
think if the PR is merged and closed, these two would be as well?

**Comment by denismaier** [comment]
Closing this. (Closed by https://github.com/citation-style-language/schema/pull/193)
