### ISSUE TITLE
Season Ranges

### ISSUE THREAD

**Issue by inukshuk** [citation-style-language/schema#148]
I was wondering whether or not season ranges are currently supported by CSL?

This requires an input format that supports setting the season of both the beginning and the end of a range; I think this is currently not possible using CSL input data (because the season number is set on the date and not the respective `date-parts`); it will likely be possible when using the upcoming ISO 8601 standard (something like `2018-21/2018-23`). Assuming that the `range-delimiter` is taken from the `date-part[name="month"]` I think that CSL already handlese season ranges just fine, but it does not seem possible to input a season range with the current data format, or am I missing something?

Thanks!

**Comment by njbart** [comment]
citeproc-js accepts pseudo months `13` to `16`, so “Spring 2013 to Winter 2014” can be expressed as:

```
[
  {
    "id": "item1",
    "issued": {
      "date-parts": [
        [
          2013,
          13
        ],
        [
          2014,
          16
        ]
      ]
    },
    "type": "webpage"
  }
]
```

pandoc-citeproc accepts this, plus the ISO 8601 seasons/pseudo months `21` to `24`, plus its own CSL YAML date format, e.g.,

```
---
references:
- id: item1
  type: webpage
  issued:
  - year: 2013
    season: 1
  - year: 2014
    season: 4
...
```

See also my [request to have citeproc-js accept pseudo months `21` to `24`, too](https://github.com/Juris-M/citeproc-js/issues/61).

**Comment by inukshuk** [comment]
Ah, that explains it, thanks! Will make sure to support the same in citeproc-ruby.
