### ISSUE TITLE
How to tell whether citation is in the [@ref-id] context or @ref-id context?

### ISSUE THREAD

**Issue by sanchom** [citation-style-language/schema#152]
[PANDOC ]( https://pandoc.org/MANUAL.html#citations) says this:

A minus sign (-) before the @ will suppress mention of the author in the citation. This can be useful when the author is already mentioned in the text:

```
Smith says blah [-@smith04].
```

You can also write an in-text citation, as follows:

```
@smith04 says blah.

@smith04 [p. 33] says blah.
```
-----------------

How do I use CSL to indicate that a citation should be rendered differently in each of these contexts?

**Comment by rmzelle** [comment]
It's my understanding that pandoc automatically takes care of this, based on the way you cite a given item. The current version of CSL (1.0.1) only defines the citation format for full regular citations (such as "(Doe et al., 2007)" and leaves any tweaks to the CSL processor.

**Comment by sanchom** [comment]
@rmzelle Thanks. Yeah, I think this is a pandoc/citeproc issue.
