### ISSUE TITLE
csl-data.json: Is the author.literal definition repeated?

### ISSUE THREAD

**Issue by dhimmel** [citation-style-language/schema#154]
While working on https://github.com/greenelab/manubot/issues/47, I encountered a behavior I don't understand. Here is the code to reproduce:

```python

csl = r'''\
[
  {
    "type": "article-journal",
    "author": [
      {
        "ORCID": "http://orcid.org/0000-0002-5577-3516",
        "authenticated-orcid": false,
        "given": "Travers",
        "family": "Ching",
        "sequence": "first",
        "affiliation": []
      }
    ],
    "id": "PZMP42Ak"
  }
]
'''
csl = json.loads(csl)

url = 'https://github.com/citation-style-language/schema/raw/4846e02f0a775a8272819204379a4f8d7f45c16c/csl-data.json'
schema = jsonref.load_uri(url, jsonschema=True)  # https://github.com/Julian/jsonschema/issues/447
jsonschema.Draft3Validator.check_schema(schema)
validator = jsonschema.Draft3Validator(schema)
errors = list(validator.iter_errors(csl))
error = errors[0]
error.context
```

The final command outputs:

```
[<ValidationError: "Additional properties are not allowed ('affiliation', 'authenticated-orcid', 'ORCID', 'sequence' were unexpected)">,
 <ValidationError: "Additional properties are not allowed ('family', 'ORCID', 'given', 'authenticated-orcid', 'affiliation', 'sequence' were unexpected)">]
```

The first validation error is correct IMO. The second seems to be incorrect as the "family" and "given" fields should be part of the CSL schema for an author:

https://github.com/citation-style-language/schema/blob/4846e02f0a775a8272819204379a4f8d7f45c16c/csl-data.json#L71-L130

However, if you scroll to the bottom of the current schema, it looks like `literal` is repeated, which I believe to be causing this second ValidationError that doesn't make sense. Is this a typo?

**Comment by dhimmel** [comment]
Looks also to be [part of the CSL-M schema](https://github.com/Juris-M/schema/blob/a355cd652d0d6fc37ac18cf919468ffbc9620b3a/csl-data.json#L120-L127). @Juris-M any idea what the following is:

```json
                        {
                            "properties": {
                                "literal" : {
                                    "type": "string" 
                                } 
                            },
                            "additionalProperties" : false 
                        } 
```

**Comment by rmzelle** [comment]
It looks like I put in the repetition. It's been a few years since I worked with JSON schema, but I agree it looks rather redundant.

(as a bit of background, csl-data.json was constructed based on the CSL JSON format developed by @fbennett for citeproc-js. When I wrote the schema, I was validating the schema against the extracted CSJ JSON input snippets from the citeproc-js test suite (now at https://github.com/citation-style-language/test-suite/). Since citeproc-js was one of the first and the most popular CSL processors, other implementations have started to support this same CSL JSON format, in part by studying this schema. As far as I know we don't have any automated workflow to verifying that the test suite snippets all indeed validate against this schema, so I'm a bit hesitant to make changes to the schema without verifying that it doesn't break anything)

**Comment by dhimmel** [comment]
> As far as I know we don't have any automated workflow to verifying that the test suite snippets all indeed validate against this schema

Yeah, it seems like this would be a great place for continuous integration. At a minimum, CI could ensure that the JSON schemas were actually valid schemas. However perhaps it could also run the test suite from `citation-style-language/test-suite`. @fbennett would that make sense?

**Comment by rmzelle** [comment]
Yes, definitely. I think nobody has had the time/skills to set up CI for the test suite. There is some additional discussion at https://github.com/citation-style-language/test-suite/issues/1#issuecomment-282565231.

**Comment by dhimmel** [comment]
> I think nobody has had the time/skills to set up CI for the test suite

I'm happy to open a PR with a `.travis.yml` configuration if a maintainer enables Travis for this repo. I won't know what to test besides a basic check that the schemas are valid and linted, etcetera. However, if @fbennett provides some advice on how to run the test-suite, happy to integrate that into the travis script.

**Comment by rmzelle** [comment]
> I'm happy to open a PR with a .travis.yml configuration if a maintainer enables Travis for this repo.

Done: https://travis-ci.org/citation-style-language/schema. 

> I won't know what to test besides a basic check that the schemas are valid and linted, etcetera.

That would be a good start. Just in case it's useful, we already have some RSpec code to check whether certain files are valid JSON: https://github.com/citation-style-language/locales/blob/b8c370c8a978790d2aeefa302f05f3bfb1478e75/spec/repository_spec.rb#L34

**Comment by dhimmel** [comment]
@rmzelle opened a CI PR at https://github.com/citation-style-language/schema/pull/156
