### ISSUE TITLE
Proposal: Add "actor" name variable

### ISSUE THREAD

**Issue by avimshah** [citation-style-language/schema#157]
Add actor/performer/cast member ("actor") name variable for multimedia formats such as broadcast and motion_picture. 

For the broadcast and motion_picture mediums, the performer is not also the author. For video (YouTube, etc) and song, the performer is also the author.

Example motion picture (CSL type motion_picture) MLA citation (using director and actor):
The Usual Suspects. Directed by Bryan Singer. Performances by Kevin Spacey, Gabriel Byrne, Chazz Palminteri, Stephen Baldwin, and Benicio Del Toro. Polygram, 1995. 

(http://columbiacollege-ca.libguides.com/mla/videos)

Example video (CSL type motion_picture) MLA citation (using author):
Sethi, Ramit. "How to Write a Winning Resume, With Ramit Sethi." YouTube, 23 June 2015, www.youtube.com/watch?v=_0fjkKCsM1w. Accessed 28 June 2016.

(http://columbiacollege-ca.libguides.com/mla/videos)

Adding an "author" name variable would simplify adding support for "Performance(s) by" prefix.

**Comment by bwiernik** [comment]
APA does not require actors to be cited. It seems like citing specific actors should be something users do manually or by entering it into `note` or similar.
