### ISSUE TITLE
Define URIs for CSL reference types

### ISSUE THREAD

**Issue by nichtich** [citation-style-language/schema#159]
A simple but official URI form of CSL reference types would help to express [mapping Wikidata to CSL](https://github.com/larsgw/citation.js/issues/166). What's needed is only a stable URI prefix, for instance `https://citationstyles.org/types/`:

* https://citationstyles.org/types/article
* https://citationstyles.org/types/book
* ...

A redirect from these URLs to 
http://docs.citationstyles.org/en/stable/specification.html#appendix-iii-types would be enough to start with.

**Comment by larsgw** [comment]
Similarly, for linked data in general URI prefixes for variables would be nice too (but lower priority).

**Comment by bdarcus** [comment]
Should be closed; right?

**Comment by larsgw** [comment]
I would still like official URIs for variables in general, then we can make CSL-RDF and the like (but that also ties in to making CSL-JSON linked data).

**Comment by bdarcus** [comment]
I did help create the BIBO ontolology, but never really considered the csl input model ideal for wider use. What's the use case here that BIBO doesn't cover?

If we do want stable URIs associate with CSL, note that we just setup a subdomain for this purpose; here's the new json schema URI:

``` 
https://resource.citationstyles.org/schema/latest/input/json/csl-data.json
```

**Comment by larsgw** [comment]
That's good to know, thanks!

> What's the use case here that BIBO doesn't cover?

Well, CSL, or more specifically citeproc-js input. I made a number of crosswalks targeting CSL-JSON and I thought it would be nice to describe them with URIs.
