### ISSUE TITLE
add "available-date" date variable

### ISSUE THREAD

**Issue by rmzelle** [citation-style-language/schema#163]
Per https://github.com/citation-style-language/styles/issues/3769 (and https://github.com/citation-style-language/styles/issues/3769#issuecomment-439769732 in particular), and as requested by @proceps, some style guides require both the year of publication to be included in the reference, as well as the year of imprint (if they differ).

One open question is whether it will be enough to just add a new "imprint" date variable, or whether any testing logic will be required to determine whether the imprint and publication dates fall in different years. The Journal of the Kansas Entomological Society requirements (http://kes.allenpress.com/kes/portals/_default/instructions_for_authors.pdf) are particularly tricky, as the imprint date replaces the publication date in in-text citations:

> For articles that were printed with one year but did not appear or were not actually issued until a subsequent year, cite the correct year in brackets following the year as printed on the original publication. Refer to the printed year for all citations in the text.
>
> ...
>
> Darling, D. C.  1996 [1997].  A new species of Spalangiopelta (Hymenoptera: Pteromalidae; Ceinae) from Dominican amber: Phylogenetic and biogeographic implications. Journal of the Kansas Entomological Society, supplement 69(4): 248-259.   

The International Commission on Zoological Nomenclature's requirements (http://www.nhm.ac.uk/hosted-sites/iczn/code/index.jsp?nfv=true&article=22) are more straightforward, although there might be an implicit assumption that the imprint date is only included if it's in a different year than the publication date:

> 22A.2.3. if wishing to cite both the actual and the imprint dates, should first cite the actual date (cited as above), followed by the imprint date for information and enclosed in parentheses or other brackets and quotation marks ...
>
> Examples. Ctenotus alacer Storr, 1970 ("1969"), or Ctenotus alacer Storr, 1970 ["1969"], or Ctenotus alacer Storr, 1970 (imprint 1969), or Ctenotus alacer Storr, 1970 (not 1969), was established in a work which, although published in 1970, carried an imprint date of 1969; Anomalopus truncatus (Peters, 1876 ["1877"]) was established in a different genus from Anomalopus in a work which, although published in 1876, carried an imprint date of 1877.

The easiest solution would be to rely on the presence of the imprint date in the item metadata. Otherwise we likely need an additional test (either implicit or explicit) that determines whether the imprint date is in a different year than the date of publication.

**Comment by bdarcus** [comment]
So is the proposal to add "imprint" to the list of date types?

**Comment by bwiernik** [comment]
Almost all styles require citation by the imprint/copyright date, not any other date (e.g., when the item appears, which might be earlier or later), so that is what should be used for `issued`. 

If this is implemented, it should be in the form of the CSL-M `available-date` (https://citeproc-js.readthedocs.io/en/latest/csl-m/#available-date-extension). I don't see a problem with adding `available-date`. It will be a rarely used variable, but I don't see the harm in having it.

**Comment by bdarcus** [comment]
Thanks @bwiernik - I changed the title accordingly.

**Comment by bdarcus** [comment]
To be clear, primary use case here is things like journal articles
available before formal publication date?

**Comment by bwiernik** [comment]
That and some types of legal documents.
