### ISSUE TITLE
add additional locator variables

### ISSUE THREAD

**Issue by bwiernik** [citation-style-language/schema#166]
Current locator types are:
page
book
chapter
column
figure
folio
issue
line
note
opus
paragraph
part
section
sub-verbo
volume
verse

There are a few additional common locator types that would be good to add:
table
equation
appendix
supplement
timestamp
location (as in for e-readers)
article
rule
title
canon

There are perhaps others as well, but I can't think of any at the moment. (cf. https://forums.zotero.org/discussion/comment/326399#Comment_326399)

**Comment by bwiernik** [comment]
Also:
timestamp

**Comment by bdarcus** [comment]
I have been tagging issues with a 1.0.2 milestone, with the idea it would bundle together all the minor changes (new variables, types, etc.). Can this go there?

**Comment by bwiernik** [comment]
Yes.

**Comment by bwiernik** [comment]
Added some legal locators from CSLm

**Comment by bwiernik** [comment]
Also `canon` https://forums.zotero.org/discussion/82799/citing-references-with-specifications-other-than-page-numbers

**Comment by denismaier** [comment]
These are accepted for 1.0.2 right?
