### ISSUE TITLE
QUESTION: Status of JSON schemas (and possible alternatives))

### ISSUE THREAD

**Issue by bpj** [citation-style-language/schema#170]
I'm working on a project which will store its own structured data in YAML files — chosen as the in my opinion most reasonable compromise between human and computer readability, while sticking to a feature subset which can readily be converted to JSON — validated against a JSON schema (which is also maintained as YAML, because I prefer it and the tools used happily accept both formats). These files will contain references in the form of citation ids referencing a references.yaml file which uses the YAML equivalent of CSL which Pandoc understands. 

As part of validation there will be need to check that sources referenced in the data not only exist in the references.yaml file, but that the entries in that file are valid.  To that end I'm looking to using the JSON schema files in this repository, but I see that it says that these are not official.

So I wonder how reliable those JSON schema files are? Are they updated, for one thing? Are there repositories out there for tools using CSL which may have other, more up to date and more widely supported JSON schemas? 

Perhaps I would be better off using what Zotero and Pandoc can actually handle, since I use Zotero and text documents coming out of this project will be written and maintained as Pandoc Markdown files and then converted to HTML and/or LaTeX→PDF as needed.

Are processors supposed to ignore or complain about unknown/custom fields, and more importantly what do they do in practice? I see your JSON schemas seem to have `"additionalProperties": false` just about everywhere. The project will need to reference works with titles and authors' names in non-Latin scripts, and I would like to enter the transliterations of titles and names in separate fields for search and processing purposes. I'm afraid I may end up in a situation where I'll have to pre-process my bibliography to convert this into a single field with the original scripts in brackets for communication with standard tools. It would be much better if I could include my custom separate fields and automatically combine those in the official fields, with other tools just ignoring the custom fields. I'd be happy to remove those fields before feeding the references e.g. to Pandoc — and I guess I'll have to convert to JSON in most cases — but the schema choking on those to me vital fields is a concern. I'd rather not modify/fork any existing schema which is a moving target.

**Comment by dhimmel** [comment]
Disclaimer: I am not a maintainer of this repo, just someone who uses the schema.

> To that end I'm looking to using the JSON schema files in this repository, but I see that it says that these are not official.

I was under the impression that the schema here are official. Were did you see they were unofficial?

>  I see your JSON schemas seem to have "additionalProperties": false just about everywhere.

I agree this is not ideal for many use cases. One workaround is to use the `note` field and [this cheater syntax](https://citeproc-js.readthedocs.io/en/latest/csl-json/markup.html#cheater-syntax-for-odd-fields). Also you are probably okay setting extra fields... this won't cause most applications that use CSL to fail. What's most important is that the fields that are defined by the schema follow the types and formats specified.

> Are they updated, for one thing?

Yes, but not as much as I would like. It's not clear whether the team that has led development in the past has the bandwidth to make major changes required to keep CSL JSON as a satisfactory solution for bibliographic metadata.

> Are there repositories out there for tools using CSL

The project I help develop that uses CSL JSON is called Manubot. We have a [Python package](https://github.com/manubot/manubot) with the ability to:

- create valid CSL JSON from invalid CSL JSON (pruning)
- create CSL JSON for persistent identifiers like DOIs and PubMed IDs.
- a [CSL_Item](https://github.com/manubot/manubot/blob/0b7c14a6bbab77d6c91f0019dff524bb43587769/manubot/cite/csl_item.py) class

**Comment by bdarcus** [comment]
We've just updated the JSON schemas to draft07. It's true the team is stretched thin now, but hoping we can accept PRs for further enhancements to these schemas.
