### ISSUE TITLE
testing a new golang CSL parser

### ISSUE THREAD

**Issue by DrGo** [citation-style-language/schema#172]
Hello,
I have developed a CSL parser for golang https://github.com/DrGo/csl (WIP).
wondering if there are tests that I can translate to golang to verify completeness  and accuracy of the XML parsing

Thanks,

/salah

**Comment by bdarcus** [comment]
Very cool!

I'm not following what you're asking for. Wouldn't using a standard,
compliant, XML parser insure that's covered for you?

And you've seen this, for the actual CSL processing test suite?

**Comment by DrGo** [comment]
Thanks for the prompt reply,
For convenience (and a nice API), I am using Go structs (like Java/C++ classes) which I had to create manually because I could not find a tool that generates Go structs from CSL RELAX NG schema (there is one for XSD but could not find a CSL XSD). I am sure I am missing or misinterpreting many elements/attributes which means that although this Go package will parse a CSL file without errors, the missing elements will have no corresponding API. So I was hoping that someone knows of a test suite in any language that I can convert to Go to test that all elements/attributes etc are parsed correctly.

Best,

**Comment by bdarcus** [comment]
I don't know if this is helpful, but I converted the RNC files to XSD with Trang, and placed them [here](https://github.com/bdarcus/schema/tree/master/xsd).  If you and others find it helpful, maybe we could add it to the main repo?

**Comment by DrGo** [comment]
Thanks, very helpful
