### ISSUE TITLE
add uncertain-author

### ISSUE THREAD

**Issue by bwiernik** [citation-style-language/schema#185]
Many styles require some notation that an author is inferred, rather than known (e.g., https://forums.zotero.org/discussion/82897/author-in-square-brackets). 

I think we should add an `is-uncertain` tag to name data.

**Comment by denismaier** [comment]
Absolutely, yes.

**Comment by denismaier** [comment]
I guess we'll have to do this together with your [name data model proposal](https://github.com/citation-style-language/csl-evolution/issues/29), right?

**Comment by bwiernik** [comment]
Yeah.

**Comment by denismaier** [comment]
So better to add there and close this one?

**Comment by bwiernik** [comment]
Good point. Moved to https://github.com/citation-style-language/csl-evolution/issues/29
