### ISSUE TITLE
Switching off name disambiguation

### ISSUE THREAD

**Issue by snauhaus** [citation-style-language/schema#186]
I was asked to switch off name disambiguation entirely by my thesis committee. Apparently, most journals in my field do not use any form of name disambiguation. That is (Doe, 1950; Doe 1975) should be used, thus not distinguishing between Jane and John. 

Is it possible to accomplish this?

I've looked through the help files for `givenname-disambiguation-rule` and associated options ([here](https://github.com/citation-style-language/documentation/blob/master/specification.txt)) and saw a couple of threads on the topic as well (notably [this one](https://github.com/citation-style-language/schema/issues/76)). However, I cannot figure out how I would accomplish no disambiguation at all. 

Any help would be appreciated.

**Comment by rmzelle** [comment]
You'd want to remove any of the "disambiguate-*" attributes in the style. See https://docs.citationstyles.org/en/stable/specification.html#disambiguation

If you tell us which style you're using, we can tell you what exactly to change.

**Comment by snauhaus** [comment]
Thanks for the response!

I'm using [Academy of Management Journal](https://github.com/citation-style-language/styles/blob/master/dependent/academy-of-management-journal.csl), which is dependent on [Academy of Management Review](https://github.com/citation-style-language/styles/blob/master/academy-of-management-review.csl). I believe they should be virtually the same, though.

**Comment by rmzelle** [comment]
https://github.com/citation-style-language/styles/blob/master/academy-of-management-review.csl

`<citation et-al-min="6" et-al-use-first="1" et-al-subsequent-min="3" et-al-subsequent-use-first="1" disambiguate-add-year-suffix="true" disambiguate-add-names="true" disambiguate-add-givenname="true" collapse="year">`

should change to:

`<citation et-al-min="6" et-al-use-first="1" et-al-subsequent-min="3" et-al-subsequent-use-first="1" disambiguate-add-year-suffix="true" collapse="year">`

I created a modified version at https://gist.githubusercontent.com/rmzelle/3803965aed9eeb75a68baf39a91c97f3/raw/19cd0d5fddd583bf0eb3bd73c7d3ba94f654ff72/academy-of-management-review-no-name-disamb.csl you can use. Just right-click that page and save it to your desktop before installing it into your reference manager.

**Comment by snauhaus** [comment]
Thank you very much! That's really helpful!
