### ISSUE TITLE
test_data_schema_with_empty_date_parts is failing

### ISSUE THREAD

**Issue by dhimmel** [citation-style-language/schema#188]
continuous discussion from https://github.com/citation-style-language/schema/pull/187#issuecomment-632367201:

Currently, our CI build [is failing](https://github.com/citation-style-language/schema/runs/697807024#step:5:26) on `test_data_schema_with_empty_date_parts`:

https://github.com/citation-style-language/schema/blob/991d8f606c8193c39debfdc07de18f9f88f20205/tests/test_json.py#L100-L108

This error also happens locally for me, so I don't think it has to do with GitHub Actions, but instead with the upgrade to draft-07 breaking `date-variable` definition

**Comment by dhimmel** [comment]
The schema fails the invalid date-parts as expected on https://www.jsonschemavalidator.net/

![image](https://user-images.githubusercontent.com/1117703/82667227-66b30800-9c05-11ea-96c3-e2214c9095d8.png)

**Comment by bdarcus** [comment]
I started to work on it on the json-fix branch, and I think it's close, but I don't have confidence in my json schema knowledge, or the json schema validators I tried, to be confident in submitting this yet.

@dsifford - if you could take a look when you get a chance and let me know, that'd be great.

**Comment by dhimmel** [comment]
@bdarcus I've fixed it in PR https://github.com/citation-style-language/schema/pull/189.
