### ISSUE TITLE
add RNC schema validation check to CI

### ISSUE THREAD

**Issue by bdarcus** [citation-style-language/schema#197]
We would like to confirm that a commit to the included RNC files results in a valid `csl.rnc` schema.

We need to extend the current GitHub Actions to support this.

The only way I know to validate RNC is by running the java-based Trang. If the conversion to XML completes without error, it's valid.

This is how one does it in a terminal:

``` sh
java -jar trang.jar csl.rnc csl.rng
```

**Comment by bdarcus** [comment]
@dhimmel - is there a straightforward way to do this?

**Comment by rmzelle** [comment]
Maybe set this up in Travis CI?

https://docs.travis-ci.com/user/languages/java/
https://mvnrepository.com/artifact/org.relaxng/trang/20181222

**Comment by bdarcus** [comment]
@dhimmel removed Travis in favor of GitHub Actions. Either way, we do need this.

**Comment by dhimmel** [comment]
GitHub Actions has Java images:

https://help.github.com/en/actions/language-and-framework-guides/github-actions-for-java
https://github.com/actions/setup-java

Where does `trang.jar` come from? Is there a command to install it?

**Comment by bdarcus** [comment]
I think most package managers have trang. That's how I install it on fedora.

**Comment by bdarcus** [comment]
I think this is where the source is these days:

https://code.google.com/archive/p/jing-trang/downloads

**Comment by bdarcus** [comment]
This *should* be working now. 

Thanks much for the quick PR @dhimmel!

**Comment by bdarcus** [comment]
Example is here:

https://github.com/citation-style-language/schema/runs/707588711

**Comment by rmzelle** [comment]
> I think this is where the source is these days: https://code.google.com/archive/p/jing-trang/downloads

It moved to https://github.com/relaxng/jing-trang after Google Code shut down a few years ago, and has seen some recent development activity on GitHub.
