### ISSUE TITLE
add `exhibition` type?

### ISSUE THREAD

**Issue by bwiernik** [citation-style-language/schema#208]
Here is discussion on the Zotero forums about exhibitions/exhibition catalogs. I think that collection might be able to accommodate these. But not exactly sure. https://forums.zotero.org/search/?Search=exhibition+catalog

We should compare the citation needs for archival collections and exhibitions/catalogs (especially in Chicago, which has rules for both) and see if they can be combined.

**Comment by denismaier** [comment]
Should we do tackle this now or defer to 1.1?

**Comment by bwiernik** [comment]
By adding a `curator` curator, an exhibition catalog can be handled as a `book` with a `curator` and perhaps an `event` (for the exhibition name) and `event-date` (for the exhibition date). 

For citing the exhibit itself or an item in the exhibit, for example, MLA gives these rules for [exhibit](https://style.mla.org/citing-a-museum-exhibition/) and [artwork in an exhibit](https://style.mla.org/citing-artwork-from-an-exhibition/). 

For citing artwork in an exhibit, give the artist and artwork title, followed by the name, date, and place of the exhibit.
> Turner, Joseph Mallord William. _Dieppe: The Port from the Quai Henri IV_. _Turner’s Modern and Ancient Ports: Passages through Time_, 23 Feb. 2017- 14 May 2017, Frick Collection, New York. 

So, that similarly could be handled as `graphic` with an `event`, `event-date`, `event-place`. 

For citing a full exhibit, give the exhibit name, date, and place, potentially with the name of the featured artist:
> _Unbound: Narrative Art of the Plains_. 12 Mar.-4 Dec. 2016, National Museum of the American Indian, New York.
> Cave, Nick. Until. 15 Oct. 2016-Aug. 2017, Mass MOCA, North Adams.

So, this is citing the full event, rather than a piece of it. Potentially, we could say to use the type `collection` for an exhibition, as well as a more permanent collection (e.g., an `event-date` on a `collection` implies it is a temporary exhibit rather than a permanent collection). This makes conceptual sense to me. But, I wonder if, for people in fields where collections or exhibits are cited commonly, there is a more meaningful distinction. 

The other option would be to make a first-class `event` or `exhibition` type. This could be used for exhibits, but also for, say, citing a whole conference (e.g., a conference organizer might put this on their CV) or other event. I think this approach might make for easier style writing. Between the labels, `event` makes clear the connection with the `event` variable, but might be confusing; `exhibition` seems overly narrow as a label. Maybe `shindig`? 😝 

@bdarcus @adam3smith What do you think?

**Comment by bdarcus** [comment]
An exhibition is an event, as is a hearing. What if we just added `event` now?

**Comment by bwiernik** [comment]
`hearing` has really specific citation needs though, so that should be separate. I think `event` is fine.

**Comment by bdarcus** [comment]
I only mentioned hearing to say we have a specific event type, without a
generic one.

**Comment by bwiernik** [comment]
Oh, got it.

**Comment by denismaier** [comment]
So we add `event` now as a generic type for events, and, if that is not enough, we can still add a more specific `exhibition` type later?
