### ISSUE TITLE
create stable URIs for json schemas at citationstyle.org

### ISSUE THREAD

**Issue by bdarcus** [citation-style-language/schema#216]
> Perhaps as a separate change in the future, I wonder if it makes sense to define a URL like `csl-data-schema.citationstyles.org` that can be changed for `$id` and can be updated if the source code path or repo changes.

I think @dstillman was recommending something like this, though I think he was recommending hosting a copy of the schema files on that site.

Is it feasible for us to do both changes together? That would ensure only one breaking change, rather than two.

If we do, do we need to version the json schema URI ids?

I don't know know who maintains that site, though, or how!

_Originally posted by @bdarcus and responding to @dhimmel in https://github.com/citation-style-language/schema/pull/212#issuecomment-636482128_

**Comment by dstillman** [comment]
A subdomain seems overly specific for this, but yes, I [was suggesting](https://github.com/citation-style-language/schema/pull/212#issuecomment-636400021) a citationstyles.org URL. The point is just that a GitHub raw URL isn't appropriate for anything you want to make permanently accessible via HTTP, since it can't redirect. Note that the schema file doesn't actually have to be hosted on citationstyles.org — you could just have a URL that redirected to the current GitHub raw URL.

> I don't know know who maintains that site, though, or how!

@rmzelle does, with https://github.com/citation-style-language/citation-style-language.github.io

**Comment by rmzelle** [comment]
@bdarcus, could you restore @dstillman's comment above and add your comments as an actual comment? :)

**Comment by rmzelle** [comment]
>  >  I don't know know who maintains that site, though, or how!
>
> @rmzelle does, with https://github.com/citation-style-language/citation-style-language.github.io

RRCHNM controls the https://citationstyles.org/ domain (@dstillman is currently our main contact for CNAME changes). The main site is hosted on GitHub Pages (as are https://formatter.citationstyles.org/ and https://validator.citationstyles.org/), the https://docs.citationstyles.org/ subdomain is hosted by Read the Docs (https://readthedocs.org/), and https://discourse.citationstyles.org/ is hosted by Discourse (https://www.discourse.org/). I don't think we have any other subdomains at the moment.

**Comment by bdarcus** [comment]
I'm not sure how to do that. 

I created this issue using the "create from comment" feature on the linked PR, which is where that subthread developed.

[Here's Dan's comment](https://github.com/citation-style-language/schema/pull/212#issuecomment-636400021).

**Comment by bdarcus** [comment]
@dhimmel - if you want to propose a specific solution given the above, I'm happy to integrate it into the PR.

**Comment by dstillman** [comment]
Actually, https://stackoverflow.com/questions/9276817/301-redirect-for-site-hosted-at-github#comment57813956_32465659 suggests that `redirect_to` only creates an HTML meta redirect, not an HTTP redirect, which I guess makes sense, since this is just a static site generator. But that means this can't actually use the citationstyles.org apex domain.

If there's a strong desire for this, Zotero could host an S3 bucket for a citationstyles.org subdomain with either copies of the files or redirects to GitHub. (Again, though, we don't use this, so it doesn't matter to us one way or another.)

**Comment by dhimmel** [comment]
> A subdomain seems overly specific for this, but yes, I was suggesting a citationstyles.org URL

Agreed a URL would be better than subdomain. The challenge is technical. If you're hosting via GitHub Pages, you can't have actual redirects.

> RRCHNM controls the https://citationstyles.org/ domain

What is RRCHNM? Would they be able to provide special handling of a URL to 302 redirect?

**Comment by dstillman** [comment]
RRCHNM is no longer involved — it's just Zotero/CDS. See my S3 offer above re: redirect.

> If you have to do this via static files, you could always have CI update the file in the GitHub Pages repo.

Yes, though the goal would be to make sure it would be a permanent URL, so if there was any chance that a different URL would be wanted in the future, you wouldn't want to put it on a GH Pages domain. But if a permanent URL scheme, probably with versioning, could be agreed upon, that would certainly be easiest and cleanest.

**Comment by rmzelle** [comment]
>> What is RRCHNM?
>
> RRCHNM is no longer involved — it's just Zotero/CDS

@dhimmel, see https://rrchnm.org/zotero/. Zotero was originally created by the Roy Rosenzweig Center for History and New Media (RRCHNM). But per @dstillman, apparently the domain is now maintained by Zotero and the Corporation for Digital Scholarship (CDS; https://digitalscholar.org/).

**Comment by bdarcus** [comment]
> If there's a strong desire for this, Zotero could host an S3 bucket for a citationstyles.org subdomain with either copies of the files or redirects to GitHub. (Again, though, we don't use this, so it doesn't matter to us one way or another.)
> ...
> But if a permanent URL scheme, probably with versioning, could be agreed upon, that would certainly be easiest and cleanest.

So the idea is we'd have a subdomain something like `http://schemas.citationstyles.org`, and then a URL for the json, perhaps, like the below?

* `http://schemas.citationstyles.org/json/data/1`
* `http://schemas.citationstyles.org/json/citation/1`

So scheme would be `[format]/[name]/[version]`?

Partly thinking about versioning, BTW, because of #203.

**Comment by dstillman** [comment]
I would do singular `schema`.

But it's worth thinking whether there are other resources CSL might want to make available in a permanent (i.e., redirectable) manner.

**Comment by bdarcus** [comment]
As in, if in doubt, choose a more general term than "schema".

Anyone have any suggestions?

**Comment by rmzelle** [comment]
"resource"? E.g. "http://resource.citationstyles.org/schema/".

**Comment by dhimmel** [comment]
> So scheme would be [category]/[format]/[name]/[version]?

Is there a plan on how the schema will be versioned? Currently it seems the format might be MAJOR.MINOR.

Would the version in the permalinks be MAJOR.MINOR or just MAJOR or both. Both may be the most useful to give users the possibility of always getting the latest 1.x schema. Perhaps you'd also have a `latest` to return the latest x.x schema.

Any thoughts?

**Comment by bdarcus** [comment]
Well, in CSL, we're doing x.x.x, in part because of some decisions we made
early on.

But the style version attribute current only changes at x.x, because idea
is the minor changes involve adding strings and such, and the x.x changes
have processing implications.

Given that we define those versions with git tagging, and the json schemas
are in the same repo, I suppose the easy answer is to do the same.

I don't know about the id though.

**Comment by bdarcus** [comment]
@dstillman - since I've seen no objections, how about we take you up your offer, and setup the "resources" subdomain?

And while we figure out the versioning details, how about we just point http://resource.citationstyles.org/schema/input/json/data at master, and I use that for #212?

How would we actually modify content (files and directories and/redirects) in that subdomain? Is there a way to make that easy?

**Comment by dhimmel** [comment]
> how about we just point http://resource.citationstyles.org/schema/input/json/data and http://resource.citationstyles.org/schema/input/json/citation at master

Best to keep the filename the same and include extension, so `schema/input/json/csl-citation.json` rather than `schema/input/json/citation`. This is because if you wget or similar, you'll end up with a file on your computer with that name. Also .json extension is sometimes used to parse content.

The above URLs don't have any spot for the version. I think it's probably least confusing to have `latest` go in the version spot. This way the user just has to change the one part of the URL.

Also would be best if you could use HTTPS from the start.

**Comment by bdarcus** [comment]
That's all fine. I'll defer to you two on the details. Just trying to keep
this moving so I can close it and the related PR.

**Comment by dstillman** [comment]
https://resource.citationstyles.org/schema/input/json/csl-citation.json
https://resource.citationstyles.org/schema/input/json/csl-data.json

(For now it's actually just redirecting /schema/input/json/ to the equivalent GH raw URL, so any file in master will technically work. We can adjust as necessary after the restructuring.)

**Comment by bdarcus** [comment]
Thanks much @dstillman!

Two clarifications:

1. what about @dhillman's point about the missing version bit?
2. so to add new URLs, we'd just notify you?

**Comment by dstillman** [comment]
> 1. what about @dhimmel's point about the missing version bit?

I can put in whatever you decide. I don't really have anything to do with this stuff.

> 2. so to add new URLs, we'd just notify you?

Yes, that will be easiest.

**Comment by bdarcus** [comment]
> I can put in whatever you decide. I don't really have anything to do with this stuff.

What say you @dhimmel?

Current URLs are these:

https://resource.citationstyles.org/schema/input/json/csl-citation.json
https://resource.citationstyles.org/schema/input/json/csl-data.json

You said above that we should add "latest" to the "version spot", but that doesn't work with the file extension.

Do you want this instead then?

https://resource.citationstyles.org/schema/input/json/latest/csl-citation.json
https://resource.citationstyles.org/schema/input/json/latest/csl-data.json

**Comment by dstillman** [comment]
It would think it would make more sense to put `latest` directly after `schema`, since a later schema might support different formats.

**Comment by bdarcus** [comment]
OK, so::

https://resource.citationstyles.org/schema/latest/input/json/csl-citation.json
https://resource.citationstyles.org/schema/latest/input/json/csl-data.json

And therefore, when we get to it, 1.1 versions would be:

https://resource.citationstyles.org/schema/1.1/input/json/csl-citation.json
https://resource.citationstyles.org/schema/1.1/input/json/csl-data.json

So in the future, where would something like this end up?

https://resource.citationstyles.org/schema/1.1/

A version page that included links to all schemas; both JSON input and style XML/RNC?

**Comment by dstillman** [comment]
OK, I've updated it to use `latest` in that position.

> So in the future, where would something like this end up?
>
>https://resource.citationstyles.org/schema/1.1/
>
>A version page that included links to all schemas; both JSON input and style XML/RNC?

Nowhere, because it's not a URL that would need to be linked from anywhere?

Or a static HTML page linking to various other things, but I don't know why that'd be necessary. The only problem we're solving for here is permanent URLs for programmatic schema access.

**Comment by bdarcus** [comment]
Done. Here's the updated targets:

https://raw.githubusercontent.com/citation-style-language/schema/master/schemas/input/csl-citation.json

https://raw.githubusercontent.com/citation-style-language/schema/master/schemas/input/csl-data.json

Thanks again!

**Comment by dstillman** [comment]
Updated.
