### ISSUE TITLE
Using "and" vs "&" in APA 7th edition

### ISSUE THREAD

**Issue by coryschires** [citation-style-language/schema#219]
## Problem
I think the [CSL for APA 7th edition](https://github.com/citation-style-language/styles-distribution/blob/master/apa.csl) handles two authors incorrectly.

_Note: My analysis is based on: https://owl.purdue.edu/owl/research_and_citation/apa_style/apa_formatting_and_style_guide/in_text_citations_author_authors.html_

## Examples

First, a standard cite, which works correctly:

```
Given I am using APA 7th edition
And an in-text cite has two authors: Wegener and Petty
Then a standard cite should render as `(Wegener & Petty, 1994)`
```

Next, a composite cite, which does not work as expected:
```
Given I am using APA 7th edition
And an in-text cite has two authors: Wegener and Petty
Then a composite cite should render as `Wegener and Petty (1994)`
But instead it renders as `Wegener & Petty (1994)`
  So it's rendering `&` when it ought to render `and`
```

## Has this already been fixed?
Looking on Github, I see several issues / PRs that seem to be very related:

* [193 Add new cs:intext element](https://github.com/citation-style-language/schema/pull/193)
* [173 add cs:intext element](https://github.com/citation-style-language/schema/pull/173)
* [141 Add support for "narrative citations" (aka natbib \citet)](https://github.com/citation-style-language/schema/issues/141)
* [137 Make "and" attribute in name lists more configurable](https://github.com/citation-style-language/schema/issues/137)
* [140 control structure for context (narrative vs parenthetical)](https://github.com/citation-style-language/schema/issues/140)

## Finally, my question...
If this has been fixed, how do I ensure the correct behavior in the [APA 7th edition CSL](https://github.com/citation-style-language/styles-distribution/blob/master/apa.csl)?  Do I need to update the CSL XML? Is there something I need to set in citeproc-js?

Sorry if I'm being dense. It's just there seems to be a lot of discussion around this problem, and I'm having trouble getting it all straight in my head.

**Comment by bdarcus** [comment]
Yeah, this is addressed with the new intext element coming in 1.1.

>
