### ISSUE TITLE
Item type for classical works

### ISSUE THREAD

**Issue by bdarcus** [citation-style-language/schema#22]
In publishing on well-known classical and ancient works, a simplified citation format can be used to refer to the work, rather than a published instance of it.  One possible solution in CSL would be to provide an item type for which bibliography output is suppressed.

The following links are relevant to the issue:

**Comment thread on the Zotero forums**

http://forums.zotero.org/discussion/9293/classical-citations/

**Sections of the CMS that contain examples, although not explicit descriptions, of such citations**

http://www.chicagomanualofstyle.org/ch17/ch17_sec251.html

http://www.chicagomanualofstyle.org/ch17/ch17_sec260.html

**The xbiblio-devel discussion thread that led to the filing of this ticket**

http://sourceforge.net/mailarchive/forum.php?set=custom&viewmonth=200911&viewday=25&forum_name=xbiblio-devel&style=threaded&max_rows=25&submit=Change+View

---
- Bitbucket: https://bitbucket.org/bdarcus/csl-schema/issue/13
- Originally Reported By: Frank Bennett
- Originally Created At: 2009-11-25 21:29:26

**Comment by rmzelle** [comment]
It looks like some style formats print classical works differently in the bibliography then current literature, so reopening this. See https://github.com/citation-style-language/styles/pull/2584#issuecomment-289180427

**Comment by denismaier** [comment]
That's a complicated issue that most likely won't make it into CSL 1.1. But just a few comments:

- Classical works can be published as books, but they can also be published in collection or in journals. For biblatex, @maieul has created a [package](https://ctan.org/pkg/biblatex-bookinother) which covers these and other cases. So there seems to be some demand for this among classicists.
- For simpler cases it might be enough to use the mechanism provided by CSL-m's `classic` item type which makes it possible to exclude all such items from the bibliography. (There are standard abbreviations so no need to include them in the bibliography.) In other cases users might want a special bibliography section containing only classical works.

Tough issue...

**Comment by denismaier** [comment]
Or, in the citations you have citations like `Josephus, *J.W.*`, but in the bibliography you'd still list the consulted edition like a normal book. But: these critical editions are more complicated than what CSL can handle at the moment. (Biblatex's datamodel with `title`, `booktitle`, `maintitle`, `series` could illustrate what would be needed to cover these case, see https://github.com/citation-style-language/schema/issues/111. And yes, this is not an edge case, but common enough in certain disciplines.)

**Comment by bwiernik** [comment]
The simplest approach would be to create a `classic` type. Disciplines that render these differently can do so in styles. Styles that don't make a distinction can include `classic` in item type lists alongside `book`.

**Comment by denismaier** [comment]
I am totally in favor of adding a `classic` item type. However, I am not sure that this is already sufficient. As outlined above, a classic can be published as a book, or as a journal article. So you need author and title, but also publication infos according to the particular type.
Perhaps a hierarchical model would be best here? Or CSL-M's `alt-` mechanism.

**Comment by bwiernik** [comment]
Or, like report, song, book, a classic might have a container-title, editor, issue, etc.?

**Comment by denismaier** [comment]
Classics are complicated beasts. They can have container-titles, editors, translators, issues, volumes... Sometimes you don't include that information in your bibliographies, and for the citation you only use an obscure abbreviation, and everyone knows what it is, sometimes you do this, but you add the consulted edition to the bibliography. Sometimes you mention the consulted edition in your first footnote.

**Comment by bwiernik** [comment]
Yes, but that's not so different a case from `paper-conference`, which might be published in a periodical or book-look proceedings, `report`, which might be similar to a `book` or to a `chapter`, or `book`, which we've discussed might have a `container-title` as part of an anthology.

An alternative approach to having a `classic` type might be how CSLm handles `gazette` types. There, items of type `legislation` or `regulation` might have the variable `gazette`, which modifies the formatting behavior for items published in gazettes rather than codified. For classics, a book, article-journal, etc. could have a variable `is-classic` which if present indicates the item should have classic formatting.

**Comment by maieul** [comment]
you  may look at the "Bookinother" biblatex package I wrote concerning
such type of problem

**Comment by denismaier** [comment]
I'd prefer a `classic` item type with additional information in `alt-` variables, but perhaps there are simpler solutions....
If we adopt the `is-classic` approach, how to do you add the second title? For example, this book [here](https://www.mohrsiebeck.com/buch/das-leben-des-weisen-9783161575372?no_cache=1) has a title "Das Leben des Weisen", but you will most likely cite it as "De Abrahamo".

**Comment by denismaier** [comment]
> 
> you may look at the "Bookinother" biblatex package I wrote concerning such type of problem

Yes, I've already linked to your package [above](https://github.com/citation-style-language/schema/issues/22#issuecomment-549887905).

**Comment by bwiernik** [comment]
That's `title-short` or `<text variable="title" form="short"/>`. The style contains a conditional with formatting for `classic` versus other types. That is how it would work with either a `classic` type or `is-classic`. 

I also think that a `classic` type would be generally clearer and that nuances of classics in containers can be reasonably handled with conditional tests. Just wanted to throw out `is-classic` as an option. I imagine that there won't be many cases where scholars in fields that cite classics would be publishing with a style that didn't support the `classic` type.

**Comment by denismaier** [comment]
> That's `title-short` or `<text variable="title" form="short"/>`. The style contains a conditional with formatting for `classic` versus other types. That is how it would work with either a `classic` type or `is-classic`.

Simple enough.

> I also think that a classic type would be generally clearer and that nuances of classics in containers can be reasonably handled with conditional tests. Just wanted to throw out is-classic as an option. I imagine that there won't be many cases where scholars in fields that cite classics would be publishing with a style that didn't support the classic type.

What do you think about integrating this in generic styles. Support in Chicago and MLA won't hurt, I guess...

**Comment by bwiernik** [comment]
I think we can integrate into Chicago, MLA, APA to provide a good example for how to do this.
