### ISSUE TITLE
Add a test of csl-citation.json to the test file

### ISSUE THREAD

**Issue by bdarcus** [citation-style-language/schema#226]
Currently, the CI tests don't exercise the csl-citation.json file, and so we missed a minor bug earlier.

If you have time @dhimmel, PR welcome.

Otherwise, I'll try to figure this out when I get a chance.

Here's example of valid input data:

``` json
[
    {
        "author": [
            {
                "family": "Smith",
                "given": "John"
            }
        ],
        "id": "ITEM-1",
        "issued": {
            "date-parts": [
                [
                    2018
                ]
            ]
        },
        "title": "test book",
        "type": "book"
    }
]
```

.... and invalid:

``` json
[
    {
        "author": [
            {
                "family": "Smith",
                "given": "John"
            }
        ],
        "issued": {
            "date-parts": [
                [
                    2018
                ]
            ]
        },
        "title": "test book",
        "type": "book-comic"
    }
]
```

**Comment by dhimmel** [comment]
> If you have time @dhimmel, PR welcome. Otherwise, I'll try to figure this out when I get a chance.

Would be best for you to take the lead. Happy to review a PR or provide advice as needed.

**Comment by bdarcus** [comment]
I started on the PR, but think my json above is wrong.
