### ISSUE TITLE
Make space between initial and last name customizable

### ISSUE THREAD

**Issue by adam3smith** [citation-style-language/schema#236]
Specifically, French typography typically requires a non breaking space here, whereas US typography very much doesn't. 
I.e. `A.&nbsp;Smith` vs. `A. Smith`
The former is currently impossible in Zotero.
This should likely be a locale spec, along the lines of 
initial-last-name-delimiter=" "

**Comment by denismaier** [comment]
Ok, so what do we do about this? I don't really know what the current status is? @fbennett Can you give us some hints?

**Comment by bdarcus** [comment]
Don't we need a PR for this?

**Comment by denismaier** [comment]
Yes. Is the proposed name for that attribute ok?

**Comment by bwiernik** [comment]
Use `initial-family-name-delimiter=" "`.

**Comment by bdarcus** [comment]
Closed by #299
