### ISSUE TITLE
Modify id doc and/or pattern to encourage use of uuid

### ISSUE THREAD

**Issue by bdarcus** [citation-style-language/schema#239]
I worked with Dan on the spec language [here](https://github.com/citation-style-language/documentation/pull/82) for [this issue](https://discourse.citationstyles.org/t/proposal-make-style-ids-immutable/1478/34).

That language retains `cs:id`, but recommends new styles set that value to a uuid.

Two questions:

1. beyond changing the docstring, what, if any, change on the schema pattern?
2. which release?

On 1, there are a few options:

1. do nothing; xsd:anyURI will alllow a uuid
2. explicitly define a uuid pattern option (see below)
3. I contemplated an attribute for the type of id (like `<id type="uuid">`), but maybe overkill

I think these details primarily matter if you're a style author using a validating editor, and obviously when we want to be strict on styles for public release.

```
uuid = xsd:string { pattern = "[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}" }
```

**Comment by bwiernik** [comment]
A UUID uses hexadecimal values, so the second pattern isn't right (it's missing uppercase and lowercase a-f).

**Comment by bdarcus** [comment]
OK, let's see what they say.

It's for the repo, mainly, but I'm hoping before long we see much more distributed style distribution.

What about this pattern?

```
uuid3 = xsd:string { pattern = "[\w]{8}-[\w]{4}-[\w]{4}-[\w]{4}-[\w]{12}" }
```
