### ISSUE TITLE
Redundant id key in json schema?

### ISSUE THREAD

**Issue by bdarcus** [citation-style-language/schema#241]
Why is there this additional `id` key under `citationItems`? Isn't that redundant?

Or redundant with a purpose; easier processing?

Example:

``` json
{
   "schema":"https://resource.citationstyles.org/schema/latest/input/json/csl-citation.json",
   "citationID":"item1",
   "citationItems":[
      {
         "id":"item1",
         "itemData":{
            "id":"item1",
            "type":"book",
            "title":"test title"
         }
      }
   ]
}
```

_Originally posted by @bdarcus in https://github.com/citation-style-language/schema/pull/233_

**Comment by denismaier** [comment]
Had a look here: https://citeproc-js.readthedocs.io/en/latest/csl-json/markup.html
But it's not explained there.

**Comment by bdarcus** [comment]
@fbennett - can you answer this?

Also, while I have you, note we did some updating to the schema recently; including it schema id.

**Comment by denismaier** [comment]
I've had a look at this again: I think the reason is quite simple: 

```
{
   "schema":"https://resource.citationstyles.org/schema/latest/input/json/csl-citation.json",
   "citationID":"item1",
   "citationItems":[
      {
         "id":"item1",
         "itemData":{
            "id":"item1",
            "type":"book",
            "title":"test title"
         }
      }
   ]
}
```

Under `itemData` you really just have the complete item data, so the `id` is included here as well. One level above, you have all the information about a particular citation, locators and so. I imagine it works more or less like this: users specify the details of a citation, this gets stored directly under `citationItems`. Details about the reference item is then pulled from the database application and stored as is under `itemData`.

I am not sure, but I can imagine that tools like @rmzelle's [ref-extractor](https://rintze.zelle.me/ref-extractor/) probably rely on this. Also, this might be useful for collaboration or when your database goes corrupt.

**Comment by rmzelle** [comment]
Both Zotero and Mendeley seem to store the same value in these two "id" fields in Word citation fields, so it does appear redundant. See https://github.com/rmzelle/ref-extractor/wiki for examples.

**Comment by denismaier** [comment]
So that means we can drop one of them? Which one?
@dstillman @adomasven do you have additional input here?

**Comment by bwiernik** [comment]
What about citations with multiple items?

**Comment by denismaier** [comment]
@bwiernik what do you mean?

**Comment by bwiernik** [comment]
Oh, I see, we are talking about the `id` under `citationItems` and the `id` under `itemData`, which are redundant. Got it.

**Comment by fbennett** [comment]
(I think this is relevant, but correct me if I'm wrong.)
This data shape is a processing outcome. The `citationItems` objects initially carry just the `id`, `locator`, and `label`, and a processor will fetch `itemData` to the object as a pointer based on the `id`. In some contexts (bibliographies, sort-key generation) item data is handled as an array of objects, and the `id` needs to be in there. To remove `id` from the `itemData` segment in citations would require cloning the object, which would break pointers, raise memory consumption a bit, and run the risk that multiple metadata representations of the same item would creep into documents. Removing `id` from the parent `citationItems` objects would be to delete the `id` received on input, which might not be a good idea.

**Comment by denismaier** [comment]
Thanks @fbennett for this clarification. So this means we can close this issue as we can not remove either `id`.

**Comment by bdarcus** [comment]
> (I think this is relevant, but correct me if I'm wrong.)
> This data shape is a processing outcome. The `citationItems` objects initially carry just the `id`, `locator`, and `label`, and a processor will fetch `itemData` to the object as a pointer based on the `id`. In some contexts (bibliographies, sort-key generation) item data is handled as an array of objects, and the `id` needs to be in there. To remove `id` from the `itemData` segment in citations would require cloning the object, which would break pointers, raise memory consumption a bit, and run the risk that multiple metadata representations of the same item would creep into documents. Removing `id` from the parent `citationItems` objects would be to delete the `id` received on input, which might not be a good idea.

Can I come back to this, because I still remain slightly confused, and think we can address this by adding annotation to the schemas.

So again, let's look at this:

``` js
   "citationItems":[
      {
         "id":"item1",
         "itemData":{
            "id":"item1",
            "type":"book",
            "title":"test title"
         }
```

So the inner `id` is defined currently [here](https://github.com/citation-style-language/schema/blob/v1.1/schemas/input/csl-data.json#L319):

``` js
"id": {
  "$ref": "#/definitions/id-variable"
}
```

The id-variable definition is a string or a number.

So what is the annotation for this? This?

> The stable and unique id (for example, a UUID) for the item, which allows it to associated with a citation.

I had thought we said we want these items ids to be stable and unique; like a uuid?

Is that still the case?

And then we have [this `id` definition](https://github.com/citation-style-language/schema/blob/v1.1/schemas/input/csl-citation.json#L25), in the citation schema. Is intended to be exactly the same; a copy?

As in, maybe the annotation should say something like:

> The id for the cited item; this is the id a processor will use to associate the item data.

**Comment by bwiernik** [comment]
The `id` properties for an item should be the same both in the outer object (under `citationItems`) and the inner object (under `itemData`). Initially, the processor only has the outer `id`, which it uses to retrieve the `itemData` (which also contains the `id`--that is what is used to look up).

**Comment by bdarcus** [comment]
Yeah, I get that; I just want to add annotations for both, so the details
matter.

**Comment by bdarcus** [comment]
Also, what about citekey?

**Comment by bwiernik** [comment]
That needs to be hammered out.

**Comment by bwiernik** [comment]
@bdarcus I think the best way to approach this would be to leave citekey just in the data—Essentially as a human-readable alias for id.
