### ISSUE TITLE
add condition: year < 2000

### ISSUE THREAD

**Issue by denismaier** [citation-style-language/schema#251]
As per @georgd [here](https://discourse.citationstyles.org/t/advice-on-legal-citation-style/1632/13?u=denis_maier):

> At somoe places, years should be formtatted with two digits if year < 2000 and with four digits otherwise. Am I right in assuming that that’s not possible? At least I haven’t found it in the documentation. It’s a requirement that I met in various (legal and non-legal) styles already, especially when dealing with EU sources. 

I think that sound like a reasonable suggestion. Other opinions about this? Anyone else has seen that requirement before?
If we add this: Perhaps it should be done in a not so specific way. Rather than `if after-2000` perhaps something like "`if date-range="1900-1999"` which would be adaptable to other requirements.

**Comment by denismaier** [comment]
comment by @adam3smith 
I don't have a strong opinion on adding this, but I've seen requirements that make the inclusion of publisher place dependent on year (I think pre1900) so if we do this I think it should definitely be more flexible than just after-200

**Comment by denismaier** [comment]
Yeah, MLA does this now that they omit publisher-place for current works. Don't know what APA does in these cases.

**Comment by denismaier** [comment]
@bwiernik do you think we can combine this with #254 ?

**Comment by bwiernik** [comment]
So, one option would be:
`before-1900="issued"` and `before-2000="issued"`

That's compact and consistent with existing attributes of `cs:if`, but not very flexible (it covers only the two cases listed here; but are there really more)? 

Another option would be:
`date-before="issued 1900" and `date-after="issued 1999"`

Here, `date-before` and `date-after` are space-delimited lists with the first element being a date variable and the second a numeric year. 

Another possibility would be similar to @denismaier proposal:
`date-range="issued <1900" or `date-range="issued >1999" or `date-range="issued 1900-1999" 

Here `date-range` again takes a space-delimited list with the first element being a date variable. The second element is either a date range or `<[year]` for before or ">[year]" for after.

The key thing about either the date-before or date-range syntaxes is that they have to specify what date variable is being tested.

> Don't know what APA does in these cases.

APA never gives publisher-place. For archival works, they might give archive-place.

**Comment by bdarcus** [comment]
We need a solution that works in the context of xml processing tools. One question I was looking to find an answer for recently, but did not, was whether attribute value order is preserved in XML. Attributes order itself is NOT.

Anyway, more options:

```
date-range-key='issued' date-range-values='1900-2000'
```
... or, I think the best balance of flexibility, concisely, and processing and validation rigor:

```
date-range-key='issued' date-range-start='1900' date-range-end='2000'
```

**Comment by bwiernik** [comment]
>date-range-key='issued' date-range-start='1900' date-range-end='2000'
>date-range-key='issued' date-range-end='1900'

This looks good to me

**Comment by bdarcus** [comment]
> > date-range-key='issued' date-range-start='1900' date-range-end='2000'
> > date-range-key='issued' date-range-end='1900'
> 
> This looks good to me.
> 
> Edit: Thinking about non-programmer style writers, would `date-range-variable` be easier to understand than `date-range-key`?

Yes, I was thinking the same thing.
 
> Also, would `date-range-variable`/`date-range-key` accept multiple variables? So could I do:
> 
> > `date-range-key="issued original-date" date-range-start='1900' date-range-end='1999``
> 
> To test whether either/both of the variables given are in the range? Allowing for multiple variables would be consistent with `is-uncertain-date` behavior.

I was wondering about that too.

So yeah, the definition would be the same:

```
      attribute date-range-variable {
        list { variables.dates+ }
      }
```

**Comment by denismaier** [comment]
With EDTF we could just do `date-range="1900/1999"`

**Comment by bwiernik** [comment]
> With EDTF we could just do date-range="1900/1999"

How do we specify minimum and maximum dates then (e.g., if I just want "pre-1900")?

**Comment by denismaier** [comment]
Before 1900 `date-range="../1900`"
After 1900 `date-range="1900/.."

**Comment by denismaier** [comment]
Concering two attributes vs one atttribute: We could also just say that the test must contain at least one date-range following edtf syntax and at least one date variable:  `date-range="issued ../1900`". Processors should be able to deal with this notwithstanding the order of attribute content. Right?

Anyway, I'm a bit unsure if we should stick with the current concise syntax, or if using two attributes for a test would be better in the long term.

**Comment by bwiernik** [comment]
@bdarcus Can that structure be validated? date-range can contain date variables and 1 EDTF formatted date value?

**Comment by bdarcus** [comment]
> @bdarcus Can that structure be validated? date-range can contain date variables and 1 EDTF formatted date value?

Probably, but not 100% sure.

Are we sure we want to combine the values?

**Comment by bdarcus** [comment]
This would look for the first list item being an edtf value, and then the rest of one-or-more of the being valid variables.

So yes, it's possible. Whether wise is another question.

``` console
❯ cat test.rnc
start = element style { cs-test+ }
cs-test =
  element test {
    attribute foo {
      list { edtf, vars+ }
    }
  }
edtf = "edtf"
vars = "one" | "two"

❯ cat test.xml
<?xml version="1.0"?>
<style>
  <test foo="edtf"/>
  <test foo="one edtf"/>
</style>

❯ jing test.rng test.xml
/tmp/test.xml:3:21: error: value of attribute "foo" is invalid; missing token; must be equal to "one" or "two"
/tmp/test.xml:4:25: error: value of attribute "foo" is invalid; token "one" invalid; must be equal to "edtf"
```

**Comment by denismaier** [comment]
Ok, it's possible. Whether that's a good choice, I really don't know. Perhaps should be discussed here: https://github.com/citation-style-language/schema/issues/286

**Comment by bwiernik** [comment]
No, let's keep it here. 

Given that we also have https://github.com/citation-style-language/schema/issues/254, I'm thinking that keeping two attributes would be better.

Maybe the syntax:
```
<if if-date="issued" date-range="../1900" date-precision="month">
```

`if-date` seems clear to me, but maybe `test-date`? The latter sounds more programmer-jargony-y to me. Maybe `is-date`?

**Comment by denismaier** [comment]
Or simpler `if tested="issued" ...`

**Comment by bwiernik** [comment]
I'd be okay with a generic `tested` syntax.

**Comment by denismaier** [comment]
What do you think @bdarcus ? Would that be feasible?

**Comment by bdarcus** [comment]
I think so.

Is that self-explanatory enough? What's the docstring associated with it?

**Comment by denismaier** [comment]
> I think so.
> 
> Is that self-explanatory enough? What's the docstring associated with it?

Docstring, need to think about it. What do you mean with self-explanatory? That the test requires two attributes? Or the name of the  attribute?

**Comment by bdarcus** [comment]
The name.

>

**Comment by denismaier** [comment]
Do you have other suggestions?

**Comment by bdarcus** [comment]
Let's back up.

Here's @bwiernik's last example:

``` xml
<if if-date="issued" date-range="../1900" date-precision="month">
```

With your suggestion, this would become this?

``` xml
<if tested="issued" date-range="../1900" date-precision="month">
```

If yes, what happens if someone does this?

``` xml
<if tested="title" date-range="../1900" date-precision="month">
```

What would that mean?

**Comment by bwiernik** [comment]
How about:

Docstring:
`tested` the variable(s) other test attributes apply to. Current test attributes are: `date-range`, `date-precision`. When `tested` is specified, test attributes apply their test to each `tested` variable. If a test is applied to a variable of an incompatible type (e.g., `date-precision` applied to `title`, it returns "false".

(Alternatively, we could prevent that by validation if possible.)

**Comment by bwiernik** [comment]
Currently, we only have tests related to dates on the table, but I could imagine there being other types of tests these could apply to in the future? That might be a reason to be flexible about the `tested` variable, rather than specifically making it `tested-date`?

**Comment by denismaier** [comment]
Well, testing a title for a date range won't make much sense. As per @bwiernik we have these options:

1. It simply returns false.
2. If possible, we should prevent that by validation.

Something else?

`tested-date` could be an alternative. But with `tested` we are more flexible: We can also use the same structure for other tests, e.g. test for equality:
`if tested="author" matches="publisher"` 
(I was thinking about reducing this even more to `if variable"author" matches="publisher"`, but the obvious downside is that this will stop to work: `if variable="author" is-uncertain-date="issued"`
Alternatively, we could do: `tested-date`, `tested-variable`, `tested-name`. Here, it's clear which conditions work in each case. But I like the simplicity of `tested="variable"`.

**Comment by bdarcus** [comment]
In that case, `tested` is fine, but definitely need to constrain the validation to avoid non-sense.

**Comment by denismaier** [comment]
> In that case, `tested` is fine, but definitely need to constrain the validation to avoid non-sense.

Just the question if that works.
`if tested="issued"`=> allows test conditions for dates
`if tested="author"` => allows test conditions for names
`if tested="title"` => allows test conditions for strings 

(Some conditions will likely work in multiple contexts.)

**Comment by bdarcus** [comment]
The cool thing about RNC is it's so easy (unlike json schema) to test out the validation logic.

```
start = element style { cs-test+ }

cs-test = element test { test-dates | test-names }

test-dates =
  attribute tested { "issued" },
  attribute date-test { text }

test-names =
  attribute tested { "author" },
  attribute name-test { text }
```

**Comment by denismaier** [comment]
Also we need to make sure that there is only one `@tested` per `cs:if` or `cs:condition`

**Comment by bdarcus** [comment]
> Also we need to make sure that there is only one `@tested` per `cs:if` or `cs:condition`

I don't understand. An element can only contain one of any given attribute.

**Comment by denismaier** [comment]
> > Also we need to make sure that there is only one `@tested` per `cs:if` or `cs:condition`
> 
> I don't understand. An element can only contain one of any given attribute.

No worries. I was mixing up elements with attributes. So we're safe here.

**Comment by denismaier** [comment]
So that's the proposal:
`if tested="issued" date-range="1900/1999" date-precision="day"`
?

**Comment by bwiernik** [comment]
Yes, that's the proposal. 

(And good call on remembering the `variable="author" matches="publisher"` example)
