### ISSUE TITLE
Test for date parts

### ISSUE THREAD

**Issue by bwiernik** [citation-style-language/schema#254]
**Is your feature request related to a problem? Please describe.**
Several styles call for different date formatting depending on whether a date is year-only or has various more specific parts.

**Describe the solution you'd like**
CSLm has a solution by adding three condition attributes for `if` that test how specific a date variable is (see [here](https://citeproc-js.readthedocs.io/en/latest/csl-m/index.html#has-day-extension)):
  - `has-year-only`
  - `has-to-month-or-season` (has month or season, but no day)
  - `has-day`

I think we should adopt these attributes.

**Additional context**
Replaces https://github.com/citation-style-language/schema/issues/32#issuecomment-644727755

**Comment by bdarcus** [comment]
I agree.

**Comment by denismaier** [comment]
I agree as well.
But I don't understand the name of  `has-to-month-or-season` (why has-to?)

**Comment by bdarcus** [comment]
Makes no sense, so change it?

**Comment by bwiernik** [comment]
It makes sense because `has-month` would logically be `TRUE` for the date "March 20, 2005". The meaning of this attribute is "has month, but no day". Perhaps `has-month-and-year-only` or `has-month-year-only`?

**Comment by bwiernik** [comment]
(So, the "has-to" is "has information up to [until] month or season")

**Comment by bdarcus** [comment]
What about running it around as "missing-"?

**Comment by denismaier** [comment]
Or we check for `if date-parts=year month day`?

**Comment by bdarcus** [comment]
> Or we check for `if date-parts=year month day`?

That seems ideal; no? Just have the content be a space-separated list?

Anything we're missing with that?

**Comment by bwiernik** [comment]
Okay, let's go with:
  - `has-day`
  - `missing-day`
  - `year-only`

> space-separated list: Anything we're missing with that?

Two issues. First, how do you specify which date variable is being tested? Second, it makes for awkward tests I think because the test is usually for what's missing, so it would have be to have `match="none"`, which would make it hard to combine with other conditions.

**Comment by denismaier** [comment]
Ok with me.

Regarding:

> so it would have be to have `match="none"`, which would make it hard to combine with other conditions.

I propose to add add a easier condition syntax anyway.

**Comment by denismaier** [comment]
Just a question after reading your suggestions in the linked [issue](https://github.com/citation-style-language/schema/issues/251): Could we find a solution that aligns more with the syntax there, namely:

```
date-range-variable='issued' date-range-start='1900' date-range-end='2000'
date-range-variable='issued' date-range-end='1900'
```

So:

```
date-parts-variable="issued" date-parts="day"
date-parts-variable="issued" date-parts="month" missing-date-parts="day"
date-parts-variable="issued" missing-date-parts="month day"
```

Maybe we can align this even further:

```
date-variable="issued" date-range-start='1900' date-range-end='2000'
date-variable="issued" date-range-end='1900'
date-variable="issued" date-parts="day"
date-variable="issued" date-parts="month" missing-date-parts="day"
date-variable="issued" missing-date-parts="month day"
```

I am not sure this solution is better to what was proposed already, but I am just a bit worried by the proliferation of test conditions. Maybe we can find a more generic and extensible syntax?

I am aware that this make combining multiple test conditions more complicated. But I think this is cumbersome already, which is why I propose to [add CSL-M's condition syntax](https://github.com/citation-style-language/schema/issues/255) as well.

**Comment by bwiernik** [comment]
I'm not sure how often these two types of tests would ever be combined. 

There are already two different date test formats: 
  1. The key-value pair format for date ranges, which seems necessary
  2. The `condition="variable"` format for `is-uncertain-date="variable"`

Given that both exist, I'm not sure it matters much which format we choose for the missing part tests. So it's a choice between two new conditions `date-parts` and `missing-date-parts` vs. three `has-day`, `missing-day`, `year-only`. I do like the simplicity of your second proposal and that it could potentially be extended if more date test conditions are ever added. The only real limitation of your proposal is that you would have to use `match="all"` to test for `missing-day` or `year-only`. I'm not sure how limiting that would be.

**Comment by denismaier** [comment]
Ok, it seems to is no ideal solution – as always...

What certainly speaks for your proposal is that it's easier to combine with a test for a item types. I imagine that could happen rather often:

```xml
<choose>
  <if type="article-newspaper" has-day="issued">
    whatever...
  </if>
<choose>
```

Or could we do this?

```xml
<choose>
  <if type="article-newspaper" if type="article-newspaper" date-variable="issued" date-parts="day">
    whatever...
  </if>
<choose>
```

Could that work or would we need more complex nested logic here? Or at least the proposed extended syntax? But even that would be 

```xml
<choose>
  <if>
   <conditions match="all">
     <condition type="article-newspaper"/>
     <condition date-variable="issued" date-parts="day"/>
   </conditions>
    whatever...
  </if>
<choose>
```

---
By the way, I still find `missing-day` a bit ambiguous. This should test false if we have only a year, right?

**Comment by bwiernik** [comment]
That example isn't a problem (remember `match="all"` is default):
`<if type="article-newspaper" has-day="issued" match="all">`

but:
```
<choose>
  <if type="article-newspaper" date-variable="issued" date-parts="month" missing-date-parts="day" match="any">
    whatever...
  </if>
<choose>
```

won't work. The user here is probably expecting either newspaper articles _or_ with items with month+year to pass. 

Similarly:
```
<choose>
  <if type="article-journal" date-variable="issued" missing-date-parts="month day" match="any">
    whatever...
  </if>
<choose>
```

They probably mean this to be "journal articles or items with only year", but that won't work because `missing-date-parts` will be true if either month or day is missing alone. 

I'm not sure how common these types of combinations are. My sense is not very, so accepting nested `choose` or the complex condition syntax might be okay. Perhaps someone else has some insight on what these requirements actually are? Are requirements perhaps as simple as `year-only` or `has-month-or-day`?

---------------------------
Re: naming of `missing-day`: `has-month-no-day` or `year-month-only`?

**Comment by bwiernik** [comment]
How about `date-precision="month"` as one attribute, with possible values of `year`, `month`, `day`? This attribute indicates the highest level of precision of the date (so to-year, to-month, to-day).

**Comment by denismaier** [comment]
What will `date-precision="month"` return if we have year, month and day? True or false? (Is the test: Do we have a month? Or: Don't we have more precise information than months?)

**Comment by bwiernik** [comment]
That's `date-precision="year" match="none"`
