### ISSUE TITLE
extend condition syntax

### ISSUE THREAD

**Issue by denismaier** [citation-style-language/schema#255]
**Is your feature request related to a problem? Please describe.**

Condition statements in official CSL take a single “match” attribute, which determines how the tests will be combined. The match attribute (all, any, none) applies to all tests within the statement: grouping of tests with separate match values is not possible. This makes combining different conditions unnecessarily complicated and often leads to highly nested and unreadable structures inside `cs:if`.

**Describe the solution you'd like**

CSL-M has introduced an optional extended syntax for condition statement:
> The alternative syntax may be applied to `cs:if` or `cs:else-if` elements (the “parent node” in this description). The parent node must have no attributes, and a single cs:conditions node as its first child element. The `cs:conditions` node must have one or more cs:condition children. The `cs:condition` children each define a conditional statement with attributes specified in the CSL 1.0.1 schema and in this Supplement. The `cs:condition` statements are joined according to a mandatory “match” attribute on `cs:conditions`.

Example:
``` xml
<choose>
  <if>
    <conditions match="any">
      <condition type="chapter"/>
      <condition variable="container-title collection-title" match="nand"/>
    </conditions>
    <text macro="some-chapter-mac"/>
  </if>
</choose>
```

CSL-M also adds `match="nand"` which tests true if at least one of the tests or condition statements to which it applies returns false.

I suggest we implement this solution, or something similar.

** Current capabilities

Apart from `match="nand"`, most (all?) tests can be done with standard CSL, but they may be less readable. This

``` xml
<choose>
  <if>
    <conditions match="any">
      <condition type="chapter"/>
      <condition variable="container-title collection-title" match="nand"/>
    </conditions>
    <text macro="some-chapter-mac"/>
  </if>
</choose>
```

needs a construction like this:

```xml
<choose>
  <if type="chapter"/>
    <text macro="some-chapter-mac"/>
  </if>
  <else-if variable="container-title collection-title" match="nand">
    <text macro="some-chapter-mac"/>
  <else-if>
</choose>
```

Now a real example (taken from chicago-note-bibliography.csl):

```xml
  <macro name="collection-title">
    <choose>
      <if match="none" type="article-journal">
        <choose>
          <if match="none" is-numeric="collection-number">
            <group delimiter=", ">
              <text variable="collection-title" text-case="title"/>
              <text variable="collection-number"/>
            </group>
          </if>
          <else>
            <group delimiter=" ">
              <text variable="collection-title" text-case="title"/>
              <text variable="collection-number"/>
            </group>
          </else>
        </choose>
      </if>
    </choose>
  </macro>
```

With the extended syntax that's a bit simpler:

```xml
<macro name="collection-title">
<choose>
  <if>
    <conditions match="all">
      <condition match="none" type="article-journal"/>
      <condition match="none" is-numeric="collection-number">
    </conditions>
    <group delimiter=", ">
      <text variable="collection-title" text-case="title"/>
      <text variable="collection-number"/>
    </group>
  </if>
  <else>
    <group delimiter=" ">
      <text variable="collection-title" text-case="title"/>
      <text variable="collection-number"/>
    </group>
  </else>
<choose>
</macro>
```

Note that this extended syntax is not necessarily shorter. But it will be with a third condition, and I'd also say it is more readable and maintainability is better due to DRY (the example above needs to call the same macro twice). 

**Additional context**
see [CSL-M supplement](https://citeproc-js.readthedocs.io/en/latest/csl-m/#cs-conditions-extension) from where I have copied this request almost verbatim.

** Addendum: Possible extension of the extension:
We could go even further and allow multiple `cs:conditions`.
Think of: 
if ((x = 5 or y = 10) and ((a = 1 not b = 2)  not (c = 3 or d = 4))) 

``` xml
<choose>
  <if match="all">
    <conditions match="any">
      <condition type="chapter"/>
      <condition variable="container-title collection-title" match="nand"/>
    </conditions>
    <conditions match="any">
      <condition has-day="issued"/>
      <condition date-range-variable"'issued" date-range-end='1900'/>
    </conditions>
    <text macro="some-other-mac"/>
  </if>
</choose>
```

@bdarcus @bwiernik @adam3smith Thoughts?

**Comment by bdarcus** [comment]
Is the example you posted possible currently?

If yes, what would it look like, for comparison?

**Comment by denismaier** [comment]
Updated.
Flagging this also for @jgm and @fbennett for additional input.

**Comment by bdarcus** [comment]
> Note that this extended syntax is not necessarily shorter. But it will be with a third condition, and I'd also say it is more readable and maintainability is better due to DRY (the example above needs to call the same macro twice).

I would say, per discussion on #174, that we should not make changes for what are in effect aesthetic reasons.

We should make changes if they add new capabilities, or clearly improve existing functionality, balanced against any implementation challenges.

If my "conceptual" representation above is correct, though, the processing logic is likely not that different.

**Comment by denismaier** [comment]
> I would say, per discussion on #174, that we should not make changes for what are in effect aesthetic reasons.

Sure, this has an aesthetic component, but I don't think it is purely about aesthetics. One other aspect to keep in mind is maintainability of styles, and I imagine this could make coding a bit easier.

**Comment by bwiernik** [comment]
I don't think the examples above are particularly clear, but I see value in the `conditions` element.

The main benefit is to be able to include a combination of positive and negative conditions in one `<if>` statement, rather than requiring nested `<choose>` elements:
```
    <choose>
      <if variable="event">
        <choose>
          <if variable="collection-editor editor editorial-director issue page volume" match="none">
```

Maintaining these nested conditionals can be a pain, especially for figuring out someone else's intended logic.

The other big place where nested conditionals rear their heads is when combining `type=" "` with other conditions. If you want to test for multiple types, you then can't use `match="all"`.
```
<choose>
  <if variable="container-title">
    <choose>
      <if type="book entry entry-dictionary entry-encyclopedia" match="any">
```

**Comment by bdarcus** [comment]
I'm having problems with git today, so will just post here. Is this what we're talking about?

``` diff
--- a/schemas/styles/csl.rnc
+++ b/schemas/styles/csl.rnc
@@ -1067,19 +1067,22 @@ div {
 
 ## cs:choose - Conditional Statements"
 div {
-  rendering-element.choose =
-    
-    ## Use to conditionally render rendering elements.
-    element cs:choose { choose.if, choose.else-if*, choose.else? }
 
-  choose.if = element cs:if { condition+, match, rendering-element* }
+  rendering-element.choose =
 
+    ## Use to conditionally render rendering elements.
+    element cs:choose { choose.conditions+ }
+  choose.conditions = element cs:conditions { choose.condition+, match }
+  choose.condition =
+    element cs:condition {
+      choose.if, choose.else-if*, choose.else?, match
+    }
+  choose.if =
+    element cs:if { choose.condition.atts+, rendering-element* }
   choose.else-if =
-    element cs:else-if { condition+, match, rendering-element* }
-
+    element cs:else-if { choose.condition.atts+, rendering-element* }
   choose.else = element cs:else { rendering-element+ }
-
-  condition =
+  choose.condition.atts =
     
     ## If used, the element content is only rendered if it disambiguates two
     ## otherwise identical citations. This attempt at disambiguation is only

    
```

**Comment by denismaier** [comment]
This is the csl-m solution: https://github.com/Juris-M/schema/blob/0d1c742ead025fedd08bafc317f223c56e0a9948/csl-mlz.rnc#L199

**Comment by bdarcus** [comment]
I was experimenting with your proposal, which I think was an extension of this?

Also, I didn't aim for compatibility, so simply modified the default "simple" patterns.

Was just an effort to understand it better.

**Comment by bwiernik** [comment]
`conditions` would be a child element of `if` and `else-if`, not of `choose`

**Comment by bdarcus** [comment]
To clarify a bit more with this example:

``` xml
<if>
  <conditions match="all">
    <condition match="none" type="article-journal"/>
    <condition match="none" is-numeric="collection-number">
  </conditions>
  <group delimiter=", ">
    <text variable="collection-title" text-case="title"/>
    <text variable="collection-number"/>
  </group>
</if>
```
The `conditions` element doesn't appear necessary; could just be:

``` xml
<if match="all">
  <condition match="none" type="article-journal"/>
  <condition match="none" is-numeric="collection-number">
  <group delimiter=", ">
    <text variable="collection-title" text-case="title"/>
    <text variable="collection-number"/>
  </group>
</if>
```

Right?

So in this model, all you're doing is moving the conditional logic to the `condition` children.

And then why elements vs attributes for the conditional logic?

Answer: If you want to mix different match rules (any, none, etc.) within the same choose element, without adding nested choose descendants. So in this example, the match on `if` differs from those on the conditions.

Do I have that right now?

So then a straight xslt upgrade would copy all those attributes to a single `condition` child then, while retaining `@match` on the main element?

Logic to un-nest the choose elements would be more difficult, and would have to look for different `@match` values on descendants?

**Comment by denismaier** [comment]
> Right? Or does `group` change this so that's not practical?

Don't think `group` makes any difference here.

> In any case, in this model, all you're doing is moving the conditional logic to the `condition` children.
>
> And then why elements vs attributes for the conditional logic?
> 
> Answer: If you want to mix different match rules (any, none, etc.) within the same choose element, without adding nested choose descendants. So in this example, the match on `if` differs from those on the conditions.
> 
> Do I have that right now?

I think so, yes.

> 
> So then a straight xslt upgrade would copy all those attributes to a single `condition` child then, while retaining `@match` on the main element?
> 
> Logic to un-nest the choose elements would be more difficult, and would have to look for different `@match` values on descendants?

Question is just: Do we really have to disallow the earlier syntax? Having both could be handy in some cases. (Like when you have `match="any"` you can still have it in one `if` statement as attributes. No need for dedicated `condition` elements.

**Comment by denismaier** [comment]
> The `conditions` element doesn't appear necessary

That sounds good. The only reason for `conditions` I see would be allowing multiple conditions blocks for things like  if ((x = 5 or y = 10) and ((a = 1 not b = 2) not (c = 3 or d = 4)))
But this is not even supported in CSL-m, and I'm not sure we really need it.

**Comment by bdarcus** [comment]
> Question is just: Do we really have to disallow the earlier syntax? 

No; I just think, as I said, it's a separate question. 

Ideally I could fairly easily write the xslt to update it, in part because I think it's a test of general processing issues.

**Comment by bdarcus** [comment]
Here's Frank's approach adapted to csl, and simplified.

I also added a docstring. Is this right?

BTW, I can do the PR, But I"m thinking to use this opportunity to split this section into a separate file; say `csl-conditions.rnc`. Thoughts?

```
  choose.condition = condition.atts | condition.elem
  choose.if =
    element cs:if { choose.condition+, match, rendering-element* }
  choose.else-if =
    element cs:else-if { choose.condition+, match, rendering-element* }
  choose.else = element cs:else { rendering-element+ }

  ## This element allows for more complex conditional logic; for 
  ## example, if you need to specify mixed "match" rules.
  condition.elem = element cs:condition { match?, condition.atts }
  condition.atts =
```

**Comment by bwiernik** [comment]
1. Doesn’t matter to me. 
2. Yes, defaulting to `match="all"`. A `condition` should be self-contained. This is easier for processors (no inheritance to have to manage) and easier for style writing (fewer mistakes as styles are edited over time and conditions change).

I think the main benefit of the `conditions` element is that it forces all of the conditions to be grouped together in the style. Otherwise, someone could add a condition, a text, another condition, etc. It’s an aesthetic thing, but okay to consider because we are introducing a new element now. (also allows citeproc-js to not be modified).

**Comment by bdarcus** [comment]
We can discuss the details on the PR I will submit in a minute, but on this:

> I think the main benefit of the conditions element is that it forces all of the conditions to be grouped together in the style. Otherwise, someone could add a condition, a text, another condition, etc

... we could define so they need to be grouped first.

**Comment by fbennett** [comment]
> > The `conditions` element doesn't appear necessary
> 
> That sounds good. The only reason for `conditions` I see would be allowing multiple conditions blocks for things like if ((x = 5 or y = 10) and ((a = 1 not b = 2) not (c = 3 or d = 4)))
> But this is not even supported in CSL-m, and I'm not sure we really need it.

Oops, late to the party here, sorry. The `cs:conditions` element is useful, to evaluate the `cs:condition` children as `any`, `all`, or `none`. It adds significantly to the flexibility of the structure.

**Comment by bwiernik** [comment]
@fbennett But aren't those specified on the parent `<if>` or `<else-if>`?

**Comment by fbennett** [comment]
Ah, fair point. That will work.
