### ISSUE TITLE
hooks: permissions error on pre-commit hook

### ISSUE THREAD

**Issue by bdarcus** [citation-style-language/schema#256]
I installed the new pre-commit on my repo fork (see the config [flie](https://github.com/citation-style-language/schema/blob/master/.pre-commit-config.yaml)), and am seeing an error I haven't seen before, and don't understand: `Executable 'hooks/rnc-format-validate.py' is not executable`.

This is after running `chmod` on both this file, and (to be sure) the `/git/hooks/pre-commit` file, and happens when trying to commit against the `csl.rnc` file.

Can someone else see if this happens to them? 

Any ideas?

**Comment by bdarcus** [comment]
Seems the permissions in the repo were incorrectly set. I must have added it when the file was not set to executable.

**Comment by denismaier** [comment]
Ok. So what do I have to do to get this running?

**Comment by denismaier** [comment]
Found the information

**Comment by bdarcus** [comment]
I'm starting to think maybe modifying the files during the commit is the wrong path, as it resulted in some weirdness for me today.

Thinking it should just do what the other checks will do: warn you.

Let me know what you think as you test it.
