### ISSUE TITLE
Whitespace and attribute values

### ISSUE THREAD

**Issue by bdarcus** [citation-style-language/schema#270]
See this:

https://discourse.citationstyles.org/t/xml-normalization/1657

If we wanted to fix this, possible options:

1. Convert `@prefix` and `@suffix` to elements?
2. Keep the attributes, but replace string punctuation with tokens (`"comma space"`)?
3. ???

At minimum, we need to add a line to the spec on this.

**Comment by PaulStanley** [comment]
FWIW, in my view *if* this is behaviour that departs from the XML processor spec (and I agree it looks to be, but I easily misread these things), I'd simply note that and let it be. Tools are just tools, and if CSL requires a departure from whitespace normalization in attributes, so be it. That does not make the file invalid XML: the spec is a processor spec only. Maybe *as a general matter* attribute normalization is a good idea for most situations where XML is used, it's a bad idea for CSL processing. Making prefix and suffixes elements would introduce a mass of clutter (and you'd need to do it for lots of other things as well: `delimiter`, `range-delimiter`, and so on. Bad plan to break a system that works, and which it is obviously easy to work with.

I'd just say this. 
> CSL styles are valid XML, but CSL processors MUST NOT normalize attribute values by trimming leading or trailing whitespace from attributes which define text that is intended for output: `delimiter=","` and `delimiter=" ,"` are distinct values."

You might want to think about what to do about multiple whitespace characters. You might also want to decide what you want to do with attribute values that do not define printable characters. If I set `"form=" long "` should a processor (a) treat this as `"long"` (which is how I read the XML spec to work), or (b) treat this as an invalid value, or (c) don't care. Obviously it's going to be easier to write a processor which does (b), but I'm inclined to think that (a) would be better. If so you will need a definite list of those attributes where normalization should not occur. `prefix`, `suffix`, `delimiter`, `range-delimiter`, `initialize-with` at least, and I bet there are others.

**Comment by bdarcus** [comment]
Thanks; I just copied your suggestion to a documentation PR ;-)

**Comment by bwiernik** [comment]
See also this discussion from 2016 https://github.com/citation-style-language/schema/issues/135
