### ISSUE TITLE
Update `$id` prior to v1.0.2 release

### ISSUE THREAD

**Issue by dhimmel** [citation-style-language/schema#281]
On the v1.0 branch, I think we should update:

https://github.com/citation-style-language/schema/blob/c2b2eee63e45e964f08dc56494bea85ad2a59d51/schemas/input/csl-data.json#L4

To be `https://resource.citationstyles.org/schema/v1.0/input/json/csl-data.json`. Note that URL doesn't work, but there was discussion of enabling it I think?

**Comment by bdarcus** [comment]
@dstillman - could we please get the version plan we previously discussed
working?

Let us know what you need from us.

**Comment by dstillman** [comment]
I added redirects for v1.0, v1.1, and v1.2 for good measure.

**Comment by bdarcus** [comment]
Thank you!

>
