### ISSUE TITLE
New condition: Test for equality

### ISSUE THREAD

**Issue by denismaier** [citation-style-language/schema#285]
**Is your feature request related to a problem? Please describe.**
Some styles require special formatting if certain variables are equal. E.g., APA style wants `publisher` to be suppressed when `publisher` and `author` are the same. Other styles suppress `container-author` when `container-author` and `author` are the same. Currently, there's no way to get this result as it's not possible to test if two variables are equal. 

**Describe the solution you'd like**
We should implement a new condition that tests true if two or variables are equal. Something like:

```
<if equal="author container-author">
</if>
```

Or maybe:

```
<if variable="container-author" equals="author">
</if>
```

The second example would require a more serious revision of the conditions syntax: `@variable` would specify the variable to be tested, the second attribute would specify the test. A single `@variable` would simply return true if a variable is present (the current behaviour). I'll open a seperate issue for such a revision.

**Additional context**
supersedes https://github.com/citation-style-language/csl-evolution/issues/27

** Additional requirements as per @bwiernik 

One wrinkle is how to handle equality for name variables, of which there may be many. Let's say that we have following data:

```
author: American Psychological Association
author: National Center for Measurement in Education
author: Society for Industrial-Organizational Psychology
publisher: American Psychological Association
```

Should 
```
<if variable="author" equals="publisher">
</if>
```

return TRUE or FALSE here? I'm not sure what, for example, what APA would prefer here. In the case of both a persona and corporate author, I suspect they would say TRUE:

```
author: Smith || John
author: American Psychological Association
publisher: American Psychological Association
```

If we decide that it should return FALSE, then that makes this a problem:
```
author: American Psychological Association
author: National Center for Measurement in Education
author: Society for Industrial-Organizational Psychology
publisher: American Psychological Association; National Center for Measurement in Education; Society for Industrial-Organizational Psychology
```

So, we would need `publisher` to behave like a `names` variable and accept multiple values. That is probably a good idea anyway.

_Originally posted by @bwiernik in https://github.com/citation-style-language/csl-evolution/issues/27#issuecomment-617259512_

**Comment by denismaier** [comment]
Concerning @bwiernik's question above: Perhaps this warrants for an additional test like: 

```
variable="publisher" contained-in="author"
variable="publisher" part-of="author"
```

Or: 
```
variable="author" contains="publisher"
```

That would be less strict than a test for equality: These would return true if the publisher element is also part of the `author`. But testing for strict equality would return false.

**Comment by bwiernik** [comment]
(I don't think this necessarily has anything to do with https://github.com/citation-style-language/schema/issues/13 )

**Comment by denismaier** [comment]
> (I don't think this necessarily has anything to do with #13 )

What do you mean? There's no link to #13 in the OP...

**Comment by denismaier** [comment]
Oh, my bad. No I see there is a link. That shouldn't be there of course...
