### ISSUE TITLE
Extended/revised condition syntax?

### ISSUE THREAD

**Issue by denismaier** [citation-style-language/schema#286]
Should we revision/extend the syntax for conditons? The current syntax is based on the principle that the attribute name represents the condition, the content represents the variable to be tested. This works fine in many cases and it's concise, but it may be not ideal for cases that require more complex testing logic. Here I imagine using two attributes for one condition could be easier. Like :

```
variable="issued" date-range="../1900"
variable="author" equal-with="publisher"
variable="publisher" contained-in="author"
```

Opinions?

**Comment by denismaier** [comment]
Current idea for multi-attribute tests is to use `@tested` for the variable to be tested:

**Comment by denismaier** [comment]
What do citeproc devs think about this @fbennett @jgm?

**Comment by fbennett** [comment]
Tests for variable equivalence would open up lots of edge cases that users would encounter as about.
1. Can `publisher` and `author` match if `author` is not set to "single-field mode?"
2. Is the match limited to the first-listed author, the last-listed author, any author it the series, or a lone author only?
3. Is the match case-sensitive?
4. Will variant whitespace in the input (thinspace, non-breaking space) affect the match?
5. Is there to be provision for wildcarding (match-from-front, match-from-back)?
6. Will the Unicode form (composed vs. decomposed) affect the match? Will processors be expected to normalize Unicode input for the match? Should normalization affect processor output?
7. If the element has form="short", will abbreviation affect the match?

Overall, I'm not a fan of testing for equivalence of free-form inputs. It could be useful, though, where a field is validated to a limited list of fixed values, such as item types, ISO language codes, jurisdiction identifiers, or a specified set of status values or identifier types.

**Comment by denismaier** [comment]
> Tests for variable equivalence would open up lots of edge cases that users would encounter as about.

Yes, there will be a lot of edge cases that need to be sorted out. Difficult.

What do you think about the syntax with a two attribute test syntax? (`@tested` or `@variable` + test)

**Comment by bwiernik** [comment]
I think only institutional authors would be comparable to publisher. The question of multi-length authors/publishers is resolvable I think. 

With respect to these:
> 1. Is the match case-sensitive?
> 1. Will variant whitespace in the input (thinspace, non-breaking space) affect the match?
> 1. Is there to be provision for wildcarding (match-from-front, match-from-back)?
> 1. Will the Unicode form (composed vs. decomposed) affect the match? Will processors be expected to normalize Unicode input for the match? Should normalization affect processor output?

@fbennett How are these handled for `editortranslator`?

**Comment by denismaier** [comment]
> I think only institutional authors would be comparable to publisher.

What about self-published books?

**Comment by bwiernik** [comment]
How are those actually cited?

**Comment by denismaier** [comment]
And apart from equality tests: Do you think we should consolidate the testing syntax into variations of `if variable="variable"` or is `if tested="variable` the better choice.

**Comment by bwiernik** [comment]
I think we should keep `if variable=""` as its present meaning for existence and use `tested=""` for the testing attribute.

**Comment by denismaier** [comment]
> How are those actually cited? My inclination is that either those should be cited with the distribution platform as the publisher (e.g., Amazon Self-Publishing) or have no publisher. In any case, that would require being able to structure `publisher` as a `names` array, which I'd rather not do and which we seemed to be moving away from in this thread.

Chicago suggests adding the plattform and a phrase like "self-published" or "printed by the author". (Maybe a term to be added? `self-pub`?)

**Comment by denismaier** [comment]
> I think we should keep `if variable=""` as its present meaning for existence and use `tested=""` for the testing attribute.

Ok.

**Comment by bwiernik** [comment]
> Chicago suggests adding the plattform and a phrase like "self-published" or "printed by the author".

That could probably just be data entry. It is rare enough to not be worth anything more I think?

**Comment by denismaier** [comment]
> > Chicago suggests adding the plattform and a phrase like "self-published" or "printed by the author".
> 
> That could probably just be data entry. It is rare enough to not be worth anything more I think?

With a term and the proposed term syntax data entry could be `term:self-pub`. Would be language agnostic and the costs for adding a term are low. But yes, it's quite rare.

**Comment by fbennett** [comment]
> @fbennett How are these handled for `editortranslator`?
> 
> > 1. Is the match case-sensitive?

Yes.

> > 2. Will variant whitespace in the input (thinspace, non-breaking space) affect the match?

Yes.

> > 3. Is there to be provision for wildcarding (match-from-front, match-from-back)?

No such provision.

> > 4. Will the Unicode form (composed vs. decomposed) affect the match? Will processors be expected to normalize Unicode input for the match? Should normalization affect processor output?

The processor doesn't normalize input itself, it's left up to the calling application (Zotero does this), so the match would fail.

**Comment by bwiernik** [comment]
I think we can follow all of those same choices for equality tests.

**Comment by fbennett** [comment]
As a further self-sourced response to my own skepticism, the CSL-M parallel-citation mechanism also depends on comparison of raw input values.

**Comment by bwiernik** [comment]
@denismaier I think this can be closed?
