### ISSUE TITLE
Extend cs:substitute to work with other/all variables?

### ISSUE THREAD

**Issue by denismaier** [citation-style-language/schema#287]
Currently, `cs:substitute` can only be used as a child element of `cs:names`. Would it make sense to extend this to other/ types of variables? Think of:

```xml
<text variable="title>
  <substitute>
    <text variable="genre"/>
  </substitute>
</text>

**Comment by bdarcus** [comment]
IDK; @fbennett?

It would make clear it's syntactic sugar for `choose`; no?

**Comment by fbennett** [comment]
The usage of `cs:substitute` on text or numeric variables would not be symmetric with its use on `cs:names`, since in the former cases the parent would not provide any options to control the rendering of a child `cs:names` node. So you would need to ban `cs:names` in the scope of `cs:substitute` as child of `cs:text` or `cs:number`, but not as child of `cs:names`. Are there enough use cases for it in the wild to justify the added complexity in the schema?

**Comment by denismaier** [comment]
> Are there enough use cases for it in the wild to justify the added complexity in the schema?

Hmm, I was primarily thinking about title/genre and issued/original-date.

**Comment by bwiernik** [comment]
issued/accessed/original-date typically needs more complex logic than that. 

For title/genre, it's a simple `choose` element: `if title else genre`. That is as simple to write and understand as the `substitute` construction, so I don't really see a benefit to `substitute` here, at least not enough to justify the increase in complexity. 

The main reason for substitute on names is (1) to inherit the names formatting so it doesn't have to be repeated for every variable and (2) to suppress a variable that is substituted if it would repeat later in the citation. The former isn't relevant at all here. The latter isn't that big of a deal; something like title/genre substitution usually happens in in-text citations (e.g., for items without an author). In the bibliography, most styles with genre print title, then genre right after each other, so no choose or substitution is needed at all. So, yeah, I don't see enough need to justify the increase in schema complexity.

**Comment by denismaier** [comment]
> For title/genre, it's a simple `choose` element: `if title else genre`. That is as simple to write and understand as the `substitute` construction, so I don't really see a benefit to `substitute` here, at least not enough to justify the increase in complexity.

The benefit here would be that you need the only need conditional logic once. Otherwise you will need it twice: 
1. If title -> title
   else -> genre
2. if not title -> nil
    else -> genre
With a substitute like approach you wouldn't need the second conditional, since genre would be printed only once.
Might not be enough to justify the increased complexity, though.

**Comment by denismaier** [comment]
Looks like we're not going to extend `cs:substitute` to all variables. But should we now consider the `suppress-subsequent` approach or general one time rendering?

**Comment by bwiernik** [comment]
There was another thread where we discussed general one time rendering. Where was that?

**Comment by denismaier** [comment]
The discussion was on discourse: https://discourse.citationstyles.org/t/dropping-cs-substitute/697/52

Looks like we did agree on introducing general one time rendering, and a forced re-rendering with an attribute `repeatable=true`.

**Comment by denismaier** [comment]
@bdarcus @bwiernik Can you link the PR #329 to this issue? (That way the PR will appear in the milestone overview.

**Comment by bwiernik** [comment]
Can't link a closed PR to an issue. But the PR has the milestone attached.

**Comment by denismaier** [comment]
I'll just close this as we have adopted a different solution anyway.
