### ISSUE TITLE
Add more locator terms (act and scene)

### ISSUE THREAD

**Issue by denismaier** [citation-style-language/schema#288]
`act` and `scene` are still missing in the list of locator terms. We should add them.

**Comment by denismaier** [comment]
Can we still add this to 1.0.2 or will this be for 1.1?

**Comment by bdarcus** [comment]
1.1.

**Comment by bwiernik** [comment]
Closed by #290

**Comment by denismaier** [comment]
Looks like issues won't get closed automatically if the corresponding PR is merged into a branch.,

**Comment by bwiernik** [comment]
> Clsoes 

No, it looks like you just misspelled closes

**Comment by denismaier** [comment]
> > Clsoes
> 
> No, it looks like you just misspelled closes

Ha. That's a better explanation...
