### ISSUE TITLE
Revise name data model

### ISSUE THREAD

**Issue by denismaier** [citation-style-language/schema#291]
See https://github.com/citation-style-language/csl-evolution/issues/29

I'm just adding this here, so we can add it to the 1.1 milestone.

@bwiernik Do you still think this should be in 1.1?

Closes https://github.com/citation-style-language/csl-evolution/issues/3#issuecomment-651939406

**Comment by bwiernik** [comment]
Yes.

**Comment by bwiernik** [comment]
A specific use case for the `label` specification required in a style manual: https://forums.zotero.org/discussion/84042/tromso-recommendations-for-citation-of-research-data-in-linguistics#latest

**Comment by denismaier** [comment]
This can be closed, right?
