### ISSUE TITLE
add new creator types

### ISSUE THREAD

**Issue by bwiernik** [citation-style-language/schema#293]
Replaces and updates https://github.com/citation-style-language/csl-evolution/issues/33

Some additional creator types we might consider adding. 

This one should be added for book items and the like:
  - `narrator`
    - as for an audiobook
    - similar level of contribution as `illustrator`

These should be added for media items. They finish out the media roles that currently exist in `director`, `producer`, `executive-producer`, and `performer`:
  - `writer`
    - as in a screenwriter for media items
    - distinguished from `author` in that it has parity with `director` and `producer`, whereas `author` would be more analogous to a `creator` with responsibility for the whole work
  - `creator`
    - often cited for media items
    - conceptually really similar to `author` or `container-author` I'd argue, but with a different label
    - I thought about whether we could just use `author` and set the localized labels to be "creator" and "created by", but that would cause a lot of problems
  - `host` 
    - for a regular broadcast
    - more appropriate than `director`; perhaps is analogous to `author`, but `author` might better be conceived
  - `guest`
    - for a broadcast

Basically, what I am realizing is that media creators are a rather different beast from other types of citations. We might create a new variable class `variables.media-creator` with processing rules similar to `editortranslator`. The same could be done with `author` and `illustrator`. That would address most, if not all, of the issues addressed by https://github.com/citation-style-language/csl-evolution/issues/7

There are a few other name labels that have been requested. I'm less sure on these:
  - `principal-investigator`
    - for a grant
    - these are cited very often in grant applications, so some way to formally include them would be good
    - a grant would be cited as a `report`
    - might be best covered by adding a `label` element to names data
  - `co-investigator`
    - same as `principal-investigator` above
  - `cartographer`
    - unclear how necessary this is; geography and related fields don't use this label (they just use `author`)
    - we've only seen it called for in the Vancouver style manual, but outside of public health, who in biomedical research is going to cite a map?

We might address these by adding a `label` element to names data (see ) and allowing for localized terms to appear in input data (see https://github.com/citation-style-language/schema/issues/240)

**Comment by bwiernik** [comment]
@adam3smith What are your thoughts on `principal-investigator`? It is something I run into all the time for grant applications. Should we add it as a variable or look for some other solution?

**Comment by adam3smith** [comment]
Do you have an example for a citation with PI? I've not seen this

**Comment by bwiernik** [comment]
So, for example, from the APA manual:
Blair, C. B. (Principle​ ​Investigator). (2015). Stress, self-regulation and psychopathology in middle childhood (Project No. 5R01HD081252-04) [Grant]. Eunice Kennedy Shriver National Institute of Child Health & Human Development. https://projectreporter.nih.gov/project_info_details.dm?aid=9473071&icde=40092311

This is a typical requirement for NSF and NIH grant applications--you often cite your previous grants received relevant to the application, indicating the investigator roles.

**Comment by adam3smith** [comment]
Interesting. I've obviously written prior support sections, but I've never seen them included as citations. 
I don't have an objection to adding PI and am OK doing this for 1.0.2, but especially [given the recent thread over at Zotero](https://forums.zotero.org/discussion/84042/tromso-recommendations-for-citation-of-research-data-in-linguistics) I'm wondering if this is another area where we'd need to think more systematically; the ontology listed there might be a good place to start.

**Comment by bdarcus** [comment]
When people start citing MARC, they're usually coming from a library
cataloguing perspective, which has different priorities that those for
scholarly citations.

**Comment by bwiernik** [comment]
The ontology listed there is rather specific to linguistics. This ontology has gotten some traction more broadly in other fields: https://casrai.org/credit/

My thinking on this front is that in either of these ontologies, the roles are fundamentally `author`, with more specific labels. I'd say we could potentially adopt that with a new structure or system.

I'd say for now let's add PI, then consider the author-role issue more in the future.

**Comment by bwiernik** [comment]
For an example of how those types of roles might be handled, if we adopted a `label` element in the `names` data model (see [here](https://github.com/citation-style-language/schema/issues/291)), a user could add the contributorship roles as labels in their item data. Within a program like Zotero, including those role labels in generated CSL could be toggled by a plugin.

**Comment by bdarcus** [comment]
I don't support adding this on 1.0.2, mostly because the time for adding more stuff has closed as far as I'm concerned, and because we don't now have a "grant" type, which this is a contributor on, and so I think we need.

I'm less concerned with @adam3smith's question on citations. It's true they are typically not cited in publications, but they are included in grant apps and CVs, and it seems we should support those use cases.

> For an example of how those types of roles might be handled, if we adopted a label element in the names data model (see here), a user could add the contributorship roles as labels in their item data. 

The current contributors are roles; they are relations, in fact (a different modelling than in MARC/MODS).

I think one path is to allow subtyping of those relations, something like:

``` yaml
researcher:
    subtype: principal-investigator
    name: Jane Doe
```

But I'm also open to having PI has a primary contributor relation, if we have a "project" or "grant-funded project" sort of type.

**Comment by bdarcus** [comment]
Also, if we support grants, we need more than just the variable and type.

**Comment by adam3smith** [comment]
> But I'm also open to having PI has a primary contributor relation, if we have a "project" or "grant-funded project" sort of type.

I was wondering about the same thing. Adding PI without an item type that it's really suitable for seems a bit weird. So maybe wait until 1.1 with this.

> For an example of how those types of roles might be handled, if we adopted a label element in the names data model (see here), a user could add the contributorship roles as labels in their item data.

I think this is right and you two are actually saying the same thing here. You'd have to define someone's role for citation purposes but could then add a custom label (which is basically a subtype). Since I don't think we'll be able to predict all those labels, I'd expect those to be free form, which means we'll still want to make sure we capture all relevant roles in the CSL schema. PI is on the borderline here and I could go either way.

Yeah, I generally agree that trying to at CREDIT or similar roles into human readable citations is misguided and I don't expect it to take off. They should be available via the PID (i.e. the DOI in most cases) rather than overburdening bibliographies.

**Comment by bwiernik** [comment]
`subtype` might be a better term for what I was thinking than `label`. 

A though I had for this sort of case would be to adopt a syntax like `term:cartographer`, where this would be interpreted as "if encountered, replace this with the localized term". We could create terms for CREDIT roles plus maybe a few others (e.g., `participant` for the linguistics "Speaker" role). That would cover a huge possible range to keep freeform entry still localizable.

> but some citation styles are doing weird things

I can understand the thinking in linguistics and anthropology, where there is concern about giving more acknowledgment to the (often Indigenous) people who contribute to a project by providing data or cultural insight.

**Comment by bwiernik** [comment]
> mostly because the time for adding more stuff

I think it would be okay to add a variable and type at this point before cutting the final 1.0.2. Not necessary, but not problematic either.

**Comment by denismaier** [comment]
Where are we here? Should be in 1.1 right? @bwiernik you are working on a PR?
