### ISSUE TITLE
Add positions for op. cit./loc. cit.

### ISSUE THREAD

**Issue by denismaier** [citation-style-language/schema#294]
**Is your feature request related to a problem? Please describe.**

We've added terms for "op. cit."  and "loc. cit." in https://github.com/citation-style-language/schema/issues/103

As said [here](https://github.com/citation-style-language/schema/issues/103#issuecomment-644743043), the problem with them is that they are/were sometimes used in more complex ways:

```
1. John Doe, Book A (Location: Publisher).
2. John Doe, Book B (Location: Publisher).
3. Doe, Book A, op. cit.
4. Doe, Book B., op. cit.
5. Jane Smith, Book C (Location: Publisher).
6. Doe, op. cit. => This refers to Doe, Book B
7. Doe, Book A, op. cit.
```

This is arguably hostile to readers, but given we already have the terms, we might want to consider adding new options for position to support this kind of behaviour (e.g. `position="subsequent-same-title-as-last-title-by-same-author"` or just `position="opcit"`).

**Comment by bdarcus** [comment]
What happens if we do nothing?

Am not convinced by the "since we did x we should do y" argument ;-)

>

**Comment by denismaier** [comment]
Most likely, something between not much and nothing.

It may be that the terms are already sufficient to satisfy most requirements from those who still use those terms. I just don't know for sure.

So doing nothing might be good move. Especially given the other open issues.

**Comment by bwiernik** [comment]
Yeah, "op cit." in position="subsequent" is one thing. The position="subsequent-same-title-as-last-title-by-same-author" seems really really hostile to readers and not something I think is worth the increased processor difficulty to support.

**Comment by bdarcus** [comment]
Isn't it potentially less hostile to readers than the default?

Not saying that justifies the complexity; just clarifying.

**Comment by denismaier** [comment]
> Isn't it potentially less hostile to readers than the default?
What do you mean?

**Comment by bwiernik** [comment]
> Isn't it potentially less hostile to readers than the default?

I'm not following

**Comment by bdarcus** [comment]
Nevermind; I obviously missed a nuance.
