### ISSUE TITLE
add `citation-label` syntax

### ISSUE THREAD

**Issue by bwiernik** [citation-style-language/schema#295]
Replaces https://github.com/citation-style-language/csl-evolution/issues/30

Currently, `citation-label` is either provided in item metadata or generated using a pattern specified by the citation processor. This makes it difficult for users to change label formats for different label CSL styles.

Here is some discussion between @cormacrelf and me on an interface for specifying `citation-label` formats: https://discourse.citationstyles.org/t/citation-label-formatting/1585/2

citeproc-js provides this format for automatically-generated labels: `Aaaa00:AaAa00:AaAA00:AAAA00`

@cormacrelf implemented that format into citeproc-rs, generalizing it to any number of authors. 

I think this is a good format to build on. The one question is how to specify what variables to use/fallback to to produce the `citation-label`. Here is what I propose.

A new element `cs:citation-label` sibling to `cs:citation` with a required `format` attribute (we could also use `value`).
1. `format` will look something like this `format="Aaaa0:AaAa0:AaAA0:AAAA0"`
    - `format` is a colon-delimited list with the format to use for an item with `names` input that is length 1, length 2, etc. The last value is for its position or more names (e.g., here for 4+ names).
    - `format` can be any length
    - `A` indicates first letter of creator’s family name
    - `a` indicates subsequent letters of that creator’s family name
    - `0` indicates the output of the `date` element
    - Other characters are treated literally, Literal `A`, `a`, `0` can be given by escaping with `\` (e.g., `\A`)

`cs:citation-label` can have two children
1. A `<names>` element used to provide the input for the `Aa` parts of the format
    - Can contain a `substitute` child. Other `cs:names` children are ignored.
1. An optional `<date>` element to provide the input for the `0` parts of the format
    - Output is inserted into the label 
    - Can take all of the normal children of `cs:date`
    - e.g., for two digits, specify `<date-part name="year" form="short"/>`

If the item data contains a `citation-label` value, this overrides the automatically-generated value from `cs:citation-label`.

Citation processors should no longer automatically generate `citation-label` if a syntax is not provided in the style. This will enable meaningful tests for the presence of `variable="citation-label"`. cf. https://github.com/citation-style-language/csl-evolution/issues/37

This approach rests on existing `cs:names` and `cs:date` structures while still being flexible for users.

**Comment by bdarcus** [comment]
This is one option, but have you considered an approach more like how we handle range-collapsing; an itemized list of algorithms?

**Comment by bwiernik** [comment]
That’s possible, but I‘m not sure there is a small enough discrete set of algorithms. I’ve seen a lot of variation in styles for the label (e.g., for authors: three-character, four-character, whole first author name, all author first initials; for years: two or four digits; combinations of all of those).

**Comment by bwiernik** [comment]
Okay, I dived into BibLaTeX's structure for this (Section 4.5.5, starting on p. 208 [here](https://mirror.las.iastate.edu/tex-archive/macros/latex/contrib/biblatex/doc/biblatex.pdf)). 

BibLaTeX provides for the following options:
1. Specifying which variables to use to construct a label
1. Specifying the length of each variable to use (e.g., first letter or first three letters) of an author's name.
    1. For names, separate options can be given for name lists of varying lengths (default has different formats for 1 and >1).
    1. For names, there are attributes analogous to et-al-min and et-al-use-first to control the number of names to show.
1. Disambiguation 3 disambiguation rules for names
    1. An option to `disambiguate-add-given-names`: Add additional letters to author names if two labels or names are ambiguous.
    1. An option to disambiguate names either:
        1. based on the whole citation label (e.g., two "ACE" are disambiguated, but "ACE" and "ACL" are not).
        1. based on same letter in same position (e.g., "AChE"/"AConE"/"ACouE" or "ACEd"/"ACEn")
    1. Maximum number of letters to add for disambiguation
    1. Whether to keep labels the same width
1. Other name formatting option
    1. Treat compound names separated by a hyphen/space as two separate names when constructing the label (e.g., "Mercado Martinez" becomes "MM" not "M").
    1. Option to add "+" or other symbol for "et al"
    1. Option to add year-suffix for disambiguation.
    1. Casing for variables.
1. Regex to remove things from variables before including in labels (e.g., usually periods and spaces).

The default bibtex/bibtex style is:
1. If a single author: First three letters of family name + 2-digit year
1. If 2+ authors: First letter of each + 2-digit year
1. No et-al-min
1. Compound names are treated as two names

In BibLaTeX styles (e.g., https://www.ctan.org/pkg/biblatex-iso690), options beyond those defaults are left to TeX users to specify in their document templates.

Thinking about these options, we could do one of two things:
1. Specify a discrete list of options (e.g., bibtex default style, 3-letter and 4-letter styles following the CSL pattern).
1. Use existing rendering-element attributes plus 1-3 addition attributes (`width`, `disambiguate-max-width`, `strip-spaces`) to pretty much completely reproduce BibTeX's options.

**Comment by bdarcus** [comment]
Thanks for tracking that down, and summarizing it.

On 2, you mean something like this?

``` xml
<macro name="citation-label">
  <text macro="author-short" width="4" disambiguate-max-width="2"/>
</macro>
```

How would you do a year with last two digits?

And what would strip-spaces be used for?

Finally, if we went with option 1, what's your sense of how long the list of options would be? Five or less?

**Comment by bwiernik** [comment]
### Option 2

For 2, it might look something like this:

```
<citation-label-format>
  <names variable="author" form="short" width="1" width-single="3" et-al-min="3" et-al-use-first="3" disambiguate-add-letters="true" label-disambiguation-rule="all-names" disambiguate-max-letters="3" fixed-width="false" split-compound-names="true" and="none">
    <substitute>
      <names variable="editor"/>
      <text variable="title" form="short"/>
    </substitute>
    <et-al term="none"/>
  </names>
  <date variable="issued" form="short" date-parts="year"/>
</citation-label-format>
```

That would give:
  1. Smith, 1999
      - Smi99
  1. Smith and Jones 2000
      - SJ00
  1. Smith, Jones, and Watson 2010
      - SJW10
  1. Smith, Nkomo, and Jones 1999
      - SNkJ99
  1. Smith, Neal, and Gardner 2013
      - SNeG13
  1. _A theory of everything_ 2000
      - ATOE00
  1. _Reflections_ 2015
      - Ref15

So we add a `cs:citation-label-format` element that is sibling to `cs:citation`. That indicates that the processor should automatically generate `citation-label` if it is missing (otherwise the processor does not) and provides the formatting instructions.

In `citation-label-format`, for `names` and `text`, the `width` attribute indicates how many letters to retain from each element of the variable list. For `date`, two digits of the year is `<date form="short" date-parts="year"/>`

I realized that we wouldn't need strip-spaces (it would have been for something like stripping spaces out of a short title). 

### Option 1

I'm not really sure. Because these formats in Bib(La)TeX are specified by users, its hard to see the variety. I think have seen at least the following:
  1. Three-letter citeproc style
  1. Four-letter citeproc style
  1. BibTeX default style without disambiguation
  1. BibTeX default style with disambiguation, not fixed-width
  1. BibTeX default style with disambiguation, fixed-width

If we went with this option, we might do something like this:
```
<citation-label-format form="bibtex"/>
  <text macro="author-short-with-substitute"/>
  <date variable="issued" form="short" date-parts="year"/>
</citation>
```

Here, we add a `cs:citation-label-format` element that is sibling to `cs:citation`. That indicates that the processor should automatically generate `citation-label` if it is missing (otherwise the processor does not) and gives one of the 5ish form options. Then, two elements are required: (1) a `names` element or a macro containing a `names` element and (2) a `date` element or a macro containing a `date` element. Those provide the input that the form is applied to.

**Comment by bwiernik** [comment]
(I'm almost done with a PR for Option 2 so you can see what it would look like.)

**Comment by bdarcus** [comment]
> That indicates that the processor should automatically generate `citation-label` if it is missing (otherwise the processor does not) and provides the formatting instructions.

Why this? Wouldn't the point be that the style overrides what the client provides?

You can address that in the PR.

And on 1, why not simply this? That's what I was originally meaning in my question.

``` xml
<citation label-style="citeproc-3">
```

It occurs to me it's possible these aren't mutually-exclusive. Option 1 has a large advantage in ease and brevity, while 2 in flexibility.

**Comment by bwiernik** [comment]
> Why this? Wouldn't the point be that the style overrides what the client provides?

My expectation would be: If the client provides `citation-label`, that is used regardless of what the style says (that is the BibTeX behavior). Not generating citation-labels automatically unless there is a `citation-label-format` element means that a style could use `citation-label` in condition tests. For example, some of the examples Denis has talked about, if I am reviewing a book and want to refer to that by its citation-label, but not other items, I could test:

```
<choose>
  <if variable="citation-label"/>
    <text variable="citation-label"/>
  </if>
  <else>
    <text macro="citation-subsequent"/>
  </else>
</choose>
```

> `<citation label-style="citeproc-3">`

What exactly are the name variables that populate the first part of the label? `author` with `substitute`: `editor`, `translator`, `title-short`? (same as the default macro for `cs:intext`).

> It occurs to me it's possible these aren't mutually-exclusive. Option 1 has a large advantage in ease and brevity, while 2 in flexibility.

That's a good point, we could at least specify "citeproc-4" and "bibtex-default", with the default creator macro, as simple options.

**Comment by bwiernik** [comment]
Opened a PR. Actually worked out pretty smoothly to just have attributes on `cs:citation-label-format`.
