### ISSUE TITLE
input: Remove "references" property?

### ISSUE THREAD

**Issue by bdarcus** [citation-style-language/schema#309]
There's a string property in the json schema whose purposes is unclear to me.

Do we need this, particularly if we merge #268?

**Comment by bwiernik** [comment]
I’d rather just leave it available for use as a simple string variable to indicate comments or notes on the procedural or publication history of an item that don’t fit into the @related model or for which support would be a major undertaking that CSL isn’t getting into (parallel legal citation).

Currently, it’s used for things like simple relations for legal cases (e.g., to indicate an affirming case) and patents (to cite related patent numbers) without needing full parallel legal citation support and in apa.csl to indicate related items, “conference canceled”, etc.
