### ISSUE TITLE
Clearly define CSL input format

### ISSUE THREAD

**Issue by bdarcus** [citation-style-language/schema#31]
The CSL input format is described in the CSL specification (the CSL data model), in the citeproc-js documentation (the CSL/JSON variant) and in the RELAX NG file (the CSL/XML variant). All should be losslessly mappable to each other but there are some differences.
1. The non-dropping-particle from citeproc-js is called prefix in csl-data.rnc - this is not a problem but may be confusing.
2. In csl-data.rnc a reference is identified by an URI but in citeproc-js by a simple string of any form.
3. I could not find the 'container-uri' property from csl-data.rnc in citeproc-js
4. csl-data.rnc seems to allow multiple dates of the same type and dates with   different type in start-date and end-date.
5. In csl-data.rnc the value-space of a year is xsd:gYear but in citeproc-js it is a non-zero integer.
6. In csl-data.rnc the value-space of month and day is 00..99 instead o 1..12 and 1..31.
7. In csl-data.rnc a date may have a day but no month at the same time.
8. In csl-data.rnc a season cannot be of any literal form like in citeproc-js
9. In citeproc-js the season is a property of the whole date variable but in csl-data.rnc it applies to a start and/or an end-date
10. In citeproc-js the circa flag is a property of a whole date variable but in csl-data.rnc the circa flag applies to a start-date and/or an end-date.
11. It is not clear how open-ended date ranges are encoded in csl-data.rnc
12. In citeproc.js the list of allowed markup tags in rich text variables is
    
    i, b, sup, sup, sc, span@nocase, span@nodecor, ", '

plus locale quotes plus the tags can be nested (?) but in csl-data.rnc the
tags can not be nested, there are no local quotes and the list of tags is:

```
i, b, sup, sub, abbr, cite, cite@part, span, span@protect
```

Citeproc-js almost complies to the specification but point 8 (and maybe 9). Point 10,11 and maybe 2 can be solved by better documentation. The other points require a refactoring of csl-data.rnc

---
- Bitbucket: https://bitbucket.org/bdarcus/csl-schema/issue/22
- Originally Reported By: Jakob Voss
- Originally Created At: 2010-06-22 00:29:20

**Comment by bwiernik** [comment]
As far as I can see, these are the remaining things here:

1. In csl-data.rnc a reference is identified by an URI but in citeproc-js by a simple string of any form.

1. I could not find the 'container-uri' property from csl-data.rnc in citeproc-js

@bdarcus I'm not sure what these mean. Do we need to fix anything still?

**Comment by bdarcus** [comment]
This is nine years old at this point. Maybe we should just close it as stale, and likely out of date anyway?

1. we should maybe remove the csl-data.rnc file?

**Comment by bwiernik** [comment]
Oh, I didn't notice that was there. We should remove that from 1.1 and 1.02.
