### ISSUE TITLE
Why is Mendely CSL-JSON part of the README file?

### ISSUE THREAD

**Issue by zuphilip** [citation-style-language/schema#313]
First, the restructure, clean-up work and automate of workflow looks good for me in general. Thank you for all that work!

For giving you some more feedback, I read now the README in more details (not sure I did that even before). The README makes sense and is clear until the point when Mendeley CSL-JSON is mentioned.

When I read "Mendeley provided the following documentation on their use of CSL-JSON" and what folows, then I ask myself:
- Is this then only an application profile of the schema? Or is this actually a variant of the (not yet normative) CSL-JSON from the repo?
- Why is Mendeley CSL-JSON explained such prominently? Does there exists something like Zotero CSL-JSON etc.?
- Is it within the scope of the CSL schema repo to explain how Mendeley CSL-JSON looks like?
- What is the conclusion if we see Mendeley CSL-JSON and have the schema for CSL-JSON in this repo?

Maybe, it makes more sense to move this part about Mendeley CSL-JSON into a separate file or even move it to a wiki page or something similar. Alternatively, make it more clear, how it is connected to the rest.

**Comment by bdarcus** [comment]
Yes, I was thinking this too. I think the wiki is a good place to put it.

**Comment by bdarcus** [comment]
I just moved it.

I think it was there for historical reasons.
