### ISSUE TITLE
Date formatting to depend on elements available

### ISSUE THREAD

**Issue by bdarcus** [citation-style-language/schema#32]
Permitting macros to be tested for output would cover this use case:

http://forums.zotero.org/discussion/11912?page=1#Item_2

---
- Bitbucket: https://bitbucket.org/bdarcus/csl-schema/issue/20
- Originally Reported By: Frank Bennett
- Originally Created At: 2010-03-23 05:43:57

**Comment by bwiernik** [comment]
See https://github.com/citation-style-language/csl-evolution/issues/8 for discussion of implementation in CSLm

**Comment by denismaier** [comment]
I think we should adopt the CSL-M extension here. (but rename `has-to-month-or-season` to `has-month-or-season` as suggested by @cormacrelf)

**Comment by denismaier** [comment]
Adding the 1.1 label. To be discussed...

**Comment by bdarcus** [comment]
> I think we should adopt the CSL-M extension here. (but rename `has-to-month-or-season` to `has-month-or-season` as suggested by @cormacrelf)

These long, and old, threads get difficult to follow. 

Maybe you could create a new issue that summarizes where you think we are in 2020, and what we should do, and link to this, but close?

**Comment by bwiernik** [comment]
Done.

**Comment by denismaier** [comment]
Thanks.
