### ISSUE TITLE
Do we need volume-editor-translator and editor-container-translator

### ISSUE THREAD

**Issue by denismaier** [citation-style-language/schema#360]
https://github.com/citation-style-language/schema/pull/336 has added new roles: `container-translator`, `volume-editor`, and `volume-translator`.
If `volume-editor`, and `volume-translator` are identical the behavior should be similar to current editortranslator behavior. Also, if `editor` and `container-translator` are identical.

To handle this, do we need new roles `volume-editor-translator` and `editor-container-translator`? And terms?

**Comment by bwiernik** [comment]
I don't think so. `editor-translator` is a role that is created by the processor, so we can just define when it is created from these.

**Comment by denismaier** [comment]
But if you test for `editor-translator` that should not test true if `volume-editor` and `volume-translator` are identical.

**Comment by denismaier** [comment]
> But, of course, you can also just use the new equality test here.
> 
> `if variable="volume-editor" matches="volume-translator"`. That should be good enough.

Strictly speaking, we probably don't even need the `editor-translator`, at least not for the testing purposes. (Although it's a nice shorthand, of course.)

**Comment by bwiernik** [comment]
That's probably right, but I think the shorthand is good to have for that case.

**Comment by denismaier** [comment]
> That's probably right, but I think the shorthand is good to have for that case.

Yeah, it's common enough, and keeping it poses no problem.
