### ISSUE TITLE
input: new yaml citation format

### ISSUE THREAD

**Issue by bdarcus** [citation-style-language/schema#373]
Not sure whether or how this might touch CSL, but we should be aware of this, as it appears fairly well-designed at first glance, with obvious overlap with our yaml input version.

https://citation-file-format.github.io/

**Comment by bwiernik** [comment]
Looks nice, though brings to mind: https://xkcd.com/927/

**Comment by bdarcus** [comment]
:-)

I also realized it's mainly for documenting software products.

**Comment by the-solipsist** [comment]
I just wanted to note that this issue exists in the CFF issue tracker: [Support CSL](https://github.com/citation-file-format/citation-file-format/issues/28)

**Comment by sdruskat** [comment]
Hello, co-lead of the Citation File Format project here. Had a good wee giggle at https://github.com/citation-style-language/schema/issues/373#issuecomment-687627451, but believe that thankfully this isn't the case for the CFF-CSL relation :slightly_smiling_face:, as while CSL is concerned with the [_formatting_](https://docs.citationstyles.org/en/1.0.1/specification.html#introduction) of citation metadata, CFF is concerned with their _provision_ (for software, and in the future for datasets).

Also, the scope of the issue regarding CSL over at our repo (https://github.com/citation-file-format/citation-file-format/issues/28) doesn't actually touch CSL as such (I have realized). Instead, I believe we need to address CSL processors in different languages (as listed here) to provide CFF importers for their libraries.

In any case, thanks for creating CSL and congratulations on the enormous success!
