### ISSUE TITLE
Oxford/Hart’s Rules style page range formatting

### ISSUE THREAD

**Issue by dpk** [citation-style-language/schema#385]
There should be an `oxford` or `hartsrules` abbreviation style for page ranges. This is like the `minimal` style but is designed for English, and doesn’t allow the numbers 11 through 19 to be split if that’s not how they’re pronounced.

E.g. 21–4 is okay for 21 to 24, but 12–9 is not; 117 to 119 is abbreviated 117–19, not 117–9; likewise for very large numbers, 11123–2345 would not be okay for 11123 to 12345 because the word ‘eleven’ in ‘eleven thousand’ cannot be split.

**Comment by bwiernik** [comment]
This was apparently already closed by https://github.com/citation-style-language/schema/pull/302
