### ISSUE TITLE
Expand number variables to match locator types

### ISSUE THREAD

**Issue by badumont** [citation-style-language/schema#389]
It is possible to refer to a wide variety of locator types in a citation, but in the bibliography we are stuck with `page`, `volume`, `chapter-number`, `part-number` and `section` (in 1.0.2). In History, I can find at least two frequent cases where it is problematic:
  * An item in a manuscript (where we count with folios, not with pages): Procopius Gazaeus, *Letters*, *Marc. gr. Z.* 521, ff. 109v-111;
  * An opus or an article in a volume that has no pages, but columns: John Chrysostom, *Homily 64 on John*, *Patrologia graeca* 59, cols. 353‑360. 

Would it be possible to create one number variable for each locator type to allow for their use also in bibliography?

**Comment by bwiernik** [comment]
This is being done all as part of the `page` variable in CSL 1.1.
