### ISSUE TITLE
Add `insert` type for package/prescription inserts?

### ISSUE THREAD

**Issue by wiseth** [citation-style-language/schema#394]
The 11th edition of the AMA manual includes specifications for citing a package insert:

<img width="789" alt="Screen Shot 2021-07-26 at 1 54 45 PM" src="https://user-images.githubusercontent.com/24906038/127043282-a27db39f-2072-46ea-baa6-92d1d0bb3b2d.png">

However, I have had trouble finding an existing reference type that will allow for the proper formatting, as most alternatives will either (1) not include the `publisher`, or (2) italicize the `title`. For instance, if I use a type of `report`, with "Zithromax. Prescribing information" as the `title`, I get

> *Zithromax. Prescribing information.* Pfizer; 2017. Accessed June 23, 2019. https://www.pfizermedicalinformation.com/en-us/zithromax

This is incorrect, as "Zithromax. Prescribing information" should not be italicized. However, I have been unable to identify an alternative to `report` that would yield better results. Thus, I suggest adding a new type, `insert` (or something similar, such as `product_info`), to the schema so that the unique formatting of package inserts can be defined.

Alternatively, if I have overlooked an existing possibility, please let me know!

**Comment by bwiernik** [comment]
Ah, this is one of these frustratingly specific item types 

I would enter the drug name as the `title` and the type of insert like "Package insert" as `genre`. `report` is the item type I would use for this sort of item generally, though `pamphlet` or `document` (introduced in CSL 1.0.2) could also work. The title won't be italicized in the current AMA style with either pamphlet or document.
