### ISSUE TITLE
Author lists in bibliography without "and" or "?"

### ISSUE THREAD

**Issue by mcranium** [citation-style-language/schema#402]
**Is your feature request related to a problem? Please describe.**
I was working on a CSL style for a journal that requires to have the bibliography in the following format:

Baker, A.J., Brown, P,T, Bullock, J.T, 2020, Title of the manuscript, ...

I could not find any solution that would allow me to achieve this format. As I understand it, this is because in the CSL schema `and` can only hold the values `text` and `symbol`.

**Describe the solution you'd like**
Would it be possible to add a third option like `and=none`?

**Describe alternatives you've considered**
I can set `and=""`, which works out for me locally, using Zotero and Libreoffice, however it doesn't comply with the CSL schema.

**Additional context**
See the author instructions here: http://boletinsgm.igeolcu.unam.mx/bsgm/index.php/instrucciones-instructions#new

Best wishes,
Mario

**Comment by bdarcus** [comment]
> Would it be possible to add a third option like `and=none`?

In retrospect, seems surprising we didn't!

This seems sensible to me to include in 1.1. WDYT @bwiernik @denismaier?

**Comment by bwiernik** [comment]
Yeah totally. Can you make that change Bruce?

**Comment by bdarcus** [comment]
> Yeah totally. Can you make that change Bruce?

I'll do a PR, just so people can review. I want to make a change that could benefit from some additional eyes.

**Comment by cormacrelf** [comment]
I thought you could just *not specify* an `and="..."` attribute?

**Comment by bdarcus** [comment]
> I thought you could just _not specify_ an `and="..."` attribute? **Edit**: This doesn't work for overriding the name format, but at least if you never specify an `and` anywhere then you can avoid it today. Right? If that's the case then adding a `none` option is still helpful, but you don't have to wait for 1.1

Oh, duh; too much grading today.

@mcranium  - can you try that?

**Comment by mcranium** [comment]
Thanks so much!
@bdarcus I just tried it and it works as expected, it also shows no CSL schema errors in the online validation tool (https://validator.citationstyles.org/). However, its impractical as a workaround because the journal wants an "and" in the inline citations with 2 authors. For now I will stick to my initial workaround (`and=""`).
When will 1.1 be available? So that I can make the changes in the journal style file?

**Comment by bdarcus** [comment]
> However, its impractical as a workaround because the journal wants an "and" in the inline citations with 2 authors.

Gotcha.

> When will 1.1 be available?

Good question. IDK.

Probably depends in part on the project that @cormacrelf  is working on.

**Comment by adam3smith** [comment]
Could we please revert this? There's no need for this:

As @cormacrelf says above, just omitting and does exactly the same as the planned `and="none"`

And it's already possible to have a different style for authors in in-text citations: you just define them in a different macro. There are, in fact dozens of styles that work as described above, e.g. https://www.zotero.org/styles?q=id%3Aelsevier-harvard

I have to say I'm a bit worried by the activism reacting to schema change requests. I fundamentally disagree with the implicit assumption that we're not changing our schema quickly enough and I'm worried that the fact that this is done without any input from anyone who has one maintenance on styles (other than Brenton on APA) will cause oversights and impractical changes.

**Comment by bdarcus** [comment]
Yes, I can revert it.

Before I do, any objections?

**Comment by bdarcus** [comment]
Partially reverted at https://github.com/citation-style-language/schema/commit/7d47514e4bf8339f1072c07e6b09fef6e490844e.
