### ISSUE TITLE
Add `custom` property to 1.0 input schema

### ISSUE THREAD

**Issue by bdarcus** [citation-style-language/schema#425]
Is there any reason _not_ to do this @dstillman @cormacrelf @retorquere?

See #277 and https://github.com/jgm/citeproc/issues/93#issuecomment-944456413

cc @bwiernik

**Comment by retorquere** [comment]
No reason, I think it is a good idea.

**Comment by bwiernik** [comment]
Agreed. We should add this to 1.0

**Comment by bdarcus** [comment]
Duh; we already added this!

https://github.com/citation-style-language/schema/commit/fde9bd61264c9bfab71f95dba4dc4ddbf8158561
