### ISSUE TITLE
multi-section bibliographies

### ISSUE THREAD

**Issue by bdarcus** [citation-style-language/schema#43]
This has come up a number of times, with this being the latest:

http://forums.zotero.org/discussion/16531/sort-bibliography-by-reference-type/

My thought its that this is out of scope for CSL per se, and that it's better to adopt an approach with named reference groups.

But it's worth discussing.

**Comment by manuelmeister** [comment]
I think this would be really great addition.

 F. e. to differentiate between primary and secondary sources or literature and internet sources.

**Comment by bdarcus** [comment]
The discussions about this are spread across different places, but the consensus has been that while it's an important feature, it is indeed out of scope for CSL.

Put differently, the right place for the feature to be implemented is in the citation processing tool (Zotero, pandoc-citeproc, Mendeley, etc.).

**Comment by denismaier** [comment]
Well, now that we are discussing a CSL API we could perhaps consider the feature request in that context. Like, calling applications should be able to request multiple bibliographies with different selection criteria.

**Comment by bdarcus** [comment]
That's a good point.

Maybe we can add an issue on the documentation repo tracker for this?
