### ISSUE TITLE
APA: “et al.” should be abbreviated from two or more names

### ISSUE THREAD

**Issue by zepinglee** [citation-style-language/schema#431]
See <https://apastyle.apa.org/style-grammar-guidelines/citations/basic-principles/same-year-first-author>. APA requires that if only one name is about to be abbreviate to "et al.", it should be printed out instead because the Latin term "et al." is plural.

The example provided in the link does not actually reflect the rule. The first three names are the same and the last name is written out for distinguish the cites not because of the plural "et al." rule.

> Hasan, Liang, Kahn, and Jones-Miller (2015)
Hasan, Liang, Kahn, and Weintraub (2015)

I've a test fixture from  <https://github.com/plk/biblatex/issues/1298#issuecomment-1654258314>. The current citeproc-js implementation gives:

```
      + expected - actual

      -(Anderson, Brown, Cranshaw, et al., 2020)
      -(Anderson, Brown, Danforth, et al., 2020)
      +(Anderson, Brown, Cranshaw, and Ellison, 2020)
      +(Anderson, Brown, Danforth, and Ellison, 2020)
``` 

```
>>===== MODE =====>>
citation
<<===== MODE =====<<


>>===== RESULT =====>>
(Anderson, Brown, Cranshaw, and Ellison, 2020)
(Anderson, Brown, Danforth, and Ellison, 2020)
<<===== RESULT =====<<


>>===== CITATION-ITEMS =====>>
[
    [
        {
            "id": "ITEM-1"
        }
    ],
    [
        {
            "id": "ITEM-2"
        }
    ]
]
<<===== CITATION-ITEMS =====<<


>>===== CSL =====>>
<style
      xmlns="http://purl.org/net/xbiblio/csl"
      class="in-text"
      version="1.0">
  <info>
    <id />
    <title />
    <updated>2023-07-29T16:22:11+08:00</updated>
  </info>
  <citation et-al-min="3" et-al-use-first="1" disambiguate-add-year-suffix="true" disambiguate-add-names="true" disambiguate-add-givenname="true" collapse="year" givenname-disambiguation-rule="primary-name-with-initials">
    <layout prefix="(" suffix=")" delimiter="; ">
      <group delimiter=", ">
        <names variable="author">
          <name form="short" and="symbol" delimiter=", " initialize-with=". "/>
        </names>
        <date variable="issued">
          <date-part name="year"/>
        </date>
      </group>
    </layout>
  </citation>
</style>
<<===== CSL =====<<


>>===== INPUT =====>>
[
    {
        "id": "ITEM-1",
        "type": "book",
        "author": [
            {
                "family": "Anderson",
                "given": "Arthur"
            },
            {
                "family": "Brown",
                "given": "Brian"
            },
            {
                "family": "Cranshaw",
                "given": "Cuthbert"
            },
            {
                "family": "Ellison",
                "given": "Edward"
            }
        ],
        "issued": {
            "date-parts": [
                [
                    2020
                ]
            ]
        },
        "title": "A title 1"
    },
    {
        "id": "ITEM-2",
        "type": "book",
        "author": [
            {
                "family": "Anderson",
                "given": "Arthur"
            },
            {
                "family": "Brown",
                "given": "Brian"
            },
            {
                "family": "Danforth",
                "given": "Daniel"
            },
            {
                "family": "Ellison",
                "given": "Edward"
            }
        ],
        "issued": {
            "date-parts": [
                [
                    2020
                ]
            ]
        },
        "title": "A title 2"
    }
]
<<===== INPUT =====<<


>>===== VERSION =====>>
1.0
<<===== VERSION =====<<
```

**Describe the solution you'd like**

I suggest adding a option `et-al-plural="true"/"false"` in the attributes of `<name>` to control if this rule is applied. Like `et-al-use-last`, it is inheritable from parent `<citation>`, `<bibliography>`, and `<style>` elements.

**Comment by bwiernik** [comment]
The reasoning for this rule is erroneous--"et al" is not inherently plural. It is short for either "et alia" (plural, "and others") or "et alium/alius" (singular, "and another"). So there is really no inherent problem with substituting "et al" for one name. 

As far as I am aware, only APA style has this rule--other style guides rightly recognize that "et al" can be singular or plural. 

And even APA journals don't usually follow this rule--every time I have tried to follow it in an APA journal, I have had to argue with the copyeditor who replaced the name with "et al". 

Given all of that (and considering that as of APA 7 it only comes up in the rare situation of disambiguating multiple items with a partially overlapping author set), I don't think we should add the complexity to the schema/processor/style syntax to accommodate this rule.

**Comment by zepinglee** [comment]
> The reasoning for this rule is erroneous--"et al" is not inherently plural. It is short for either "et alia" (plural, "and others") or "et alium/alius" (singular, "and another"). So there is really no inherent problem with substituting "et al" for one name.

Thanks for clarifying that.

I still add the reference in Merriam-Webster (<https://www.merriam-webster.com/dictionary/et%20al.>):

> *Et al.* typically stands in for two or more names, especially in bibliographical information.

> And even APA journals don't usually follow this rule--every time I have tried to follow it in an APA journal, I have had to argue with the copyeditor who replaced the name with "et al".

Uh...

> Given all of that (and considering that as of APA 7 it only comes up in the rare situation of disambiguating multiple items with a partially overlapping author set), I don't think we should add the complexity to the schema/processor/style syntax to accommodate this rule.

I agree.
