### ISSUE TITLE
Access status variable 

### ISSUE THREAD

**Issue by extua** [citation-style-language/schema#434]
I would like to indicate whether a work is open access, mainly inspired by the access parameter(s) in [Wikipedia Citation Style 1](https://en.wikipedia.org/wiki/Help:Citation_Style_1#Registration_or_subscription_required).

As an example, _Citation Style 1_ names four standard keywords for different levels of access:

* free
* registration
* limited
* subscription

These are used to show variations on the [Open Access logo](https://en.wikipedia.org/wiki/Open_access) against references.

Access indicators are mainly aimed at journal articles, but could also apply to other media, such as news websites (if they're behind a paywall), or podcasts (for episodes only available to paid subscribers).

**Comment by bwiernik** [comment]
The `license` variable is a good fit for this information.
