### ISSUE TITLE
Provide explicit delimiter for author groups or collapsed cites within cs:citation

### ISSUE THREAD

**Issue by fbennett** [citation-style-language/schema#52]
When citations are collapsed, the behavior at CSL 1.0 is to set an implicit comma-space delimiter as the default for joining the collapsed elements. Discussion in [this thread](https://github.com/citation-style-language/schema/issues/40) recommends that this delimiter be made explicit, either for author-collapsed cites, or for groups of cites which share the same author element.

**Comment by bdarcus** [comment]
Per the link issue, seems we may still have some tweaks needed here?

I'm hoping to wrap up work on the schema in the next few days, so if either of you have a suggestion, now would be a great time.

**Comment by bwiernik** [comment]
@bdarcus I don't really understand the rush to push out the 1.1 release. Let's just take the time to get it done.

**Comment by bdarcus** [comment]
As I said earlier, I just have a feeling I won't have much time to dedicate
to this going forward.

The other, more important, issue is I don't think we should overload the
release with too many features, lest it to be too much work to implement.

But clearly there are a few things we need to finish, and get right.
