### ISSUE TITLE
Configurable range delimiters

### ISSUE THREAD

**Issue by fbennett** [citation-style-language/schema#56]
This issue has been raised in a [thread on the Zotero forums](http://forums.zotero.org/discussion/18480/endash-instead-of-hyphen-in-collapsed-numeric-citations/#Item_5).

Currently, based on discussions on xbiblio-devel, `citeproc-js` and the test suite assume en-dash as the delimiter for collapsed ranges. This applies to page numbers, and also to citation numbers and year-suffixes.

However, according to the thread linked above, Russian orthography apparently permits only em-dash (not en-dash). To support that use case (Russian support), some method of configuring the range delimiter seems to be needed.

A simple approach would be to allow the range-delimiter attribute on cs:layout under cs:citation.

(This ticket has a sister ticket in the documentation tracker, [here](https://github.com/citation-style-language/documentation/issues/15).)

**Comment by bwiernik** [comment]
I can't tell. Has this been implemented now already in 1.0.1? @denismaier @bdarcus

**Comment by denismaier** [comment]
According to https://docs.citationstyles.org/en/stable/specification.html#page-ranges this should be there already:

> page-range-format
> Activates expansion or collapsing of page ranges: “chicago” (“321–28”), “expanded” (e.g. “321–328”), “minimal” (“321–8”), or “minimal-two” (“321–28”) (see also Appendix V - Page Range Formats). Delimits page ranges with the “page-range-delimiter” term (introduced with CSL 1.0.1, and defaults to an en-dash). If the attribute is not set, page ranges are rendered without reformatting.


But on https://docs.citationstyles.org/en/stable/specification.html#range-delimiters it says:

> The “locator” variable is always rendered with an en-dash replacing any hyphens. For the “page” variable, this replacement is only performed if the page-range-format attribute is set on cs:style (see Page Ranges).

I'm not entirely sure what that means... @rmzelle ?

**Comment by denismaier** [comment]
I think we can close this. `page-range-delimiter` is already there (now renamed to `number-range-delimiter` in #355). Also, #355 adds a new term `date-range-delimiter`.
