### ISSUE TITLE
Rename variables, types and terms to use consistent punctuation

### ISSUE THREAD

**Issue by bdarcus** [citation-style-language/schema#6]
The editortranslator term was a product of the flurry of activity in the push toward CSL 1.0.  Since it's meant to be called internally by the processor, and is not normally used directly in CSL style files, it should be possible to change its name without creating serious confusion.

For consistency with the hyphenating convention use in other variables and terms, it could changed to editor-translator, or (possibly more clear) editor-and-translator.

---
- Bitbucket: https://bitbucket.org/bdarcus/csl-schema/issue/24
- Originally Reported By: Frank Bennett
- Originally Created At: 2010-08-01 00:29:18

**Comment by denismaier** [comment]
Is renaming variables,types and terms still on the table?

**Comment by denismaier** [comment]
So, should we do this in 1.1, defer or just close this?

**Comment by denismaier** [comment]
I'm actually not sure we should change whitespace-like punctuation in each case to a hyphen:
E.g., `motion_picture` and `article-journal` are not identical: In `article-journal` the hyphen delimits a subtype, `motion_picture` is just a single term. Perhaps it might make sense to keep this distinction?

**Comment by bdarcus** [comment]
Yes, underscores and hyphens are a deliberate and meaningful distinction.

**Comment by denismaier** [comment]
Editor-and-translator seems a good idea.

**Comment by denismaier** [comment]
@bwiernik What do you think about this one? Do we need to address this now, or can we just close the issue?

**Comment by bwiernik** [comment]
The only think I think we would consider changing is the `editortranslator` term to `editor-translator` to match the variable or the terms with spaces to be tokens. I don't see a major reason to do either, so I suggest we close.

**Comment by denismaier** [comment]
Concerning `editor-translator` vs `editortranslator`: I think we can just remove `editortranslator`.

The current definition is:

```
terms =
    terms.gender-assignable
    | terms.gender-variants
    | terms.locator
    | item-types
    | 
      ## Contributor roles
      variables.names
    | "editortranslator"
    |
```

With `editor-translator` now being a regular name variable, this here should not be necessary anymore.

**Comment by denismaier** [comment]
> terms with spaces to be tokens

I'll open a PR. We can decide whether there's any value in tokenizing the terms. Closing here anyway.
