### ISSUE TITLE
proposal: allow extended ordinal suffix terms in locale

### ISSUE THREAD

**Issue by fbennett** [citation-style-language/schema#66]
This is a placeholder, to be replaced by a description of Sylvester's strategy for flexible ordinal assignment.

**Comment by bwiernik** [comment]
@denismaier Bumping this for current discussion

**Comment by denismaier** [comment]
Wow, that's much information to digest---too much for me now. Do you grasp the main points here?

**Comment by bwiernik** [comment]
Oh, actually, this all appears to have been resolved in CSL 1.0.1.
