### ISSUE TITLE
proposal: allow extended numeric variable term labels in locale

### ISSUE THREAD

**Issue by fbennett** [citation-style-language/schema#67]
Together with #62, this would allow assignment of custom document identifier labels, eliminating the demand for extending identifiers in #33.

**Comment by bwiernik** [comment]
@fbennett Can you elaborate on what this means and whether you think it is still a good proposal? My inclination would be to stick with the current approach using genre+number for specific types of identifiers like UN document numbers. This helps to ensure transportability of data across styles.

**Comment by fbennett** [comment]
Wow, that's a flash from the past. Assuming that it's [this one](https://github.com/citation-style-language/documentation/issues/21), this discussion can be closed. Jurisdiction identifiers are recognized in CSL-M, not as conditionals, but as structured keys that invoke bespoke CSL-M modules referenced by the item type and jurisdiction. The linked proposal contemplated the use of conditions embedded in the "parent" style itself, and experience taught that that approach leads to bloated styles that cannot be easily maintained.

**Comment by bwiernik** [comment]
@fbennett I think this was more for allowing styles to specify terms for things like "UN Document No. 12345". cf. https://github.com/citation-style-language/schema/issues/33

**Comment by fbennett** [comment]
Hmm. I don't fully understand what I had in mind there either. In any case, the issue is rendered moot in CSL-M by a couple of things:
* Modular legal style support
* Label short-codes, recognized (IIRC) on page, locator, and number variables.
Neither of those features in mainstream CSL, but if it's not an active issue for CSL style authors, it can be dropped. I think you can close this.

**Comment by denismaier** [comment]
>
