### ISSUE TITLE
rename "sub verbo" term to "sub-verbo"

### ISSUE THREAD

**Issue by rmzelle** [citation-style-language/schema#72]
As discussed in http://sourceforge.net/mailarchive/message.php?msg_id=27419940 , having a space in term names gives problem with conditional testing, so we should migrate "sub verbo" to "sub-verbo".

**Comment by bdarcus** [comment]
So now almost a decade later, what should we finally do about this?

It seems the primary concern is about breaking style and relates files.

So one easy break point would be a release that requires new style version?

Maybe a v2.0?

Aside: this is an embarrassing bug, I really hope we can fix!

**Comment by denismaier** [comment]
We should possible tokenize other terms as well once we do that.
