### ISSUE TITLE
Require that numeric variables be rendered with cs:number

### ISSUE THREAD

**Issue by fbennett** [citation-style-language/schema#79]
Requiring that numeric variables be rendered with cs:number would make it easier to assure that input produces results of consistent quality across styles. The essential problem is that cs:number (both in its original form and after some recent changes to its behavior in the citeproc-js processor) will sometimes remove characters from the input string, while cs:text will not. Users that build their databases for use with styles that rely on one or the other for rendering (some or all) numeric fields will get unexpected results when their item content is run through a style that uses the other. This will be much less difficult to control if the same node is used for these variables everywhere.

Here is the patch I've applied to the MLZ extended schema:

``` diff
diff --git a/csl-variables.rnc b/csl-variables.rnc
index 0d69138..7104f5b 100644
--- a/csl-variables.rnc
+++ b/csl-variables.rnc
@@ -42,7 +42,7 @@ div {

 ## standard variables
 div {
-  cs-variables =
+  cs-strings =
     "abstract"
     | "annote"
     | "archive"
@@ -82,6 +82,12 @@ div {
     | "URL"
     | "version"
     | "year-suffix"
+}
+
+## standard variables
+div {
+  cs-variables =
+    cs-strings
     |
       ## number variables
       cs-numbers
diff --git a/csl.rnc b/csl.rnc
index 0c038e5..bd69789 100644
--- a/csl.rnc
+++ b/csl.rnc
@@ -719,7 +719,7 @@ div {
                attribute value { text }
              | (
                 ## render variable
-                attribute variable { cs-variables },
+                attribute variable { cs-strings },
                 attribute form { "short" | "long" }?,
                 attribute leading-noise-words { "drop" | "demote" }?))
         }
```

**Comment by bwiernik** [comment]
Consensus seems to have emerged that we do not want to impose this constraint. I'm not sure what specifically @fbennett is alluding to, but we want to be able to maintain the flexibility of numbers being renderable using both `cs:text` and `cs:number`.

**Comment by denismaier** [comment]
I'd also say that users rely on styles producing the correct output. I guess they will be ok with correct results produced by `cs:text`. Or am I missing something?
