### ISSUE TITLE
Add a type: video

### ISSUE THREAD

**Issue by fbennett** [citation-style-language/schema#95]
At least two major styles alter the form of citation to multimedia items depending on the mode of distribution. We currently distinguish between "broadcast" and other forms of distribution. Adding a "video" type would extend that distinction to cover theater releases vs video distribution (or non-distribution).

For Chicago, Elena notes that Chicago places the title first in the cite for theater releases, but not for videos. This would be directly addressed by adding a "video" type:

  http://forums.zotero.org/discussion/12507/film-and-chicago-style/#Item_4

For Bluebook: A Uniform System of Citation (R), the form of citation to video items varies radically depending on a dog's breakfast of factors; but the hardest distinction to handle, within the current framework, is that between a theater release and a private video. Examples given include:
- <span style="font-variant:small-caps;font-size:larger;">Airplane!</span> (Paramount Pictures 1980).
- Videotape: Installing Your CLS-2009 (Emily Weiss Electric Co. 1995).

(It doesn't show up here, but "Airplane!" is set in small-caps as for a book, while "Installing Your CLS-2009" is set in ordinary roman type.)

To discriminate between these two forms when they share a common motion_picture type, we either need to turn the distinction on the presence of a "medium" (Videotape here), or on the type of creator (Paramount Pictures vs Emily Weiss Electric Co. here). Neither approach is satisfactory, unfortunately. In the first case, it is possible that a "medium" will be present in the metadata for a film (Panavision, Superscope, etc.). In the second case, Emily Weiss Electric Co. could be set as the "author" rather than the "publisher" (reasoning that the item is unpublished, and so should not have a publisher). That distinction is not intuitive in the UI, however, and requires complex code in the CSL to produce correctly formatted output.

Adding a "video" type would simplify the CSL for both of these cases.

**Comment by bwiernik** [comment]
This distinction seems pretty absurd, but could reasonably be accommodated by testing for `medium` in `motion_picture`. I don't think that "Superscope" would be recorded under `medium`; that isn't information that would appear in citations ever. Additionally testing for `URL` and `DOI` would distinguish theatrical releases from things like YouTube videos if these somehow didn't have a `medium` field.

I suggest we close this.

**Comment by denismaier** [comment]
I'm not sure here. I have just checked what Turabian says on this and they distinguish between movies and other similar items. For one, the director is the primary contributor for movies, TV stuff gets cited by title. Fo videos and podcasts they use the artist as the primary contributor. 
Each item can have `medium` and/or `URL` variables. These don't seem to work as indicators here.

**Comment by bwiernik** [comment]
TV shows is `broadcast` anyway, so that's a different issue if anything. 

Regarding the others, that's just a question of whether the item data contains `author` vs `director`, no?

**Comment by denismaier** [comment]
> Regarding the others, that's just a question of whether the item data contains `author` vs `director`, no?

It could be both.

**Comment by denismaier** [comment]
> I'm not sure here. I have just checked what Turabian says on this and they distinguish between movies and other similar items. For one, the director is the primary contributor for movies, TV stuff gets cited by title. Fo videos and podcasts they use the artist as the primary contributor.

Actually not true what I was saying here:
Movies are cited by title, then director and actors.
Artists as primary contributor for videos and podcasts is true.

Beyoncé. “Sorry.” Directed by Kahlil Joseph and Beyoncé Knowles. June 22, 2016. Music video, 4:25. https://youtu.be/QxsmWxxouIM.

Dr. Strangelove, or: How I Learned ..., directed by Stanley Kubrick, featuring Peter Sellers ...

**Comment by bwiernik** [comment]
Artist that is the primary creator is `author`.  Secondary creator artists not currently supported, but will be the new `performer` variable (they are rarely cited; only in some styles like Turabian/Chicago when the specific contribution of the actor is being referenced).

**Comment by bwiernik** [comment]
> It could be both.

So, the music video there has `author: Beyoncé`, `director: Joseph || Kahlil`, and `director: Knowles || Beyoncé`. The film has `director: Kubrick || Stanley` and `performer: Sellers || Peter`.

**Comment by bdarcus** [comment]
I've always strongly opposed this request, and my thinking hasn't
really changed.

Did your thinking change from your first post here, or you two just
thinking through how to address different cases with the status quo

**Comment by bwiernik** [comment]
(I am opposed to adding `video`.)

**Comment by bdarcus** [comment]
+1.

We can close this then :-)
